//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 24/10/2024 8:54:25 AM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace v4posme_library.Models
{
    public partial class TbUserTag {

        public TbUserTag()
        {
            this.TagID = 0;
            this.CompanyID = 0;
            this.BranchID = 0;
            this.UserID = 0;
            OnCreated();
        }

        public TbUserTag(int userTagID) : this()        {
            this.UserTagID = userTagID;
        }

        [Key]
        [Required()]
        public int UserTagID { get; set; }

        [Required()]
        public int TagID { get; set; }

        [Required()]
        public int CompanyID { get; set; }

        [Required()]
        public int BranchID { get; set; }

        [Required()]
        public int UserID { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
