//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 26/9/2024 4:44:37 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace v4posme_library.Models
{
    public partial class TbCustomerCreditExternalSharon {

        public TbCustomerCreditExternalSharon()
        {
            this.FECHADEREPORTE = @"0";
            this.DEPARTAMENTO = @"0";
            this.NUMERODECEDULAORUC = @"0";
            this.NOMBREDEPERSONA = @"0";
            this.TIPODECREDITO = @"0";
            this.FECHADEDESEMBOLSO = @"0";
            this.TIPODEOBLIGACION = @"0";
            this.MONTOAUTORIZADO = 0.00m;
            this.FRECUENCIADEPAGO = @"0";
            this.SALDODEUDA = 0.00m;
            this.ESTADO = @"0";
            this.MONTOVENCIDO = 0.00m;
            this.ANTIGUEDADDEMORA = @"0";
            this.TIPODEGARANTIA = @"0";
            this.FORMADERECUPERACION = @"0";
            this.NUMERODECREDITO = @"0";
            this.VALORDELACUOTA = 0.00m;
            this.IsActive = true;
            OnCreated();
        }

        public TbCustomerCreditExternalSharon(int? companyID, string? tIPODEENTIDAD, int? pLAZO) : this()        {
            this.CompanyID = companyID;
            this.TIPODEENTIDAD = tIPODEENTIDAD;
            this.PLAZO = pLAZO;
        }

        [Required()]
        public int CustomerID { get; set; }

        public int? CompanyID { get; set; }

        [StringLength(5)]
        public string? TIPODEENTIDAD { get; set; }

        [StringLength(50)]
        [Required()]
        public string NUMEROCORRELATIVO { get; set; }

        [StringLength(50)]
        [Required()]
        public string FECHADEREPORTE { get; set; }

        [StringLength(250)]
        [Required()]
        public string DEPARTAMENTO { get; set; }

        [StringLength(250)]
        [Required()]
        public string NUMERODECEDULAORUC { get; set; }

        [StringLength(250)]
        [Required()]
        public string NOMBREDEPERSONA { get; set; }

        [StringLength(250)]
        [Required()]
        public string TIPODECREDITO { get; set; }

        [StringLength(50)]
        [Required()]
        public string FECHADEDESEMBOLSO { get; set; }

        [StringLength(50)]
        [Required()]
        public string TIPODEOBLIGACION { get; set; }

        [Required()]
        public decimal MONTOAUTORIZADO { get; set; }

        public int? PLAZO { get; set; }

        [StringLength(250)]
        [Required()]
        public string FRECUENCIADEPAGO { get; set; }

        [Required()]
        public decimal SALDODEUDA { get; set; }

        [StringLength(450)]
        [Required()]
        public string ESTADO { get; set; }

        [Required()]
        public decimal MONTOVENCIDO { get; set; }

        [StringLength(250)]
        [Required()]
        public string ANTIGUEDADDEMORA { get; set; }

        [StringLength(250)]
        [Required()]
        public string TIPODEGARANTIA { get; set; }

        [StringLength(250)]
        [Required()]
        public string FORMADERECUPERACION { get; set; }

        [StringLength(250)]
        [Required()]
        public string NUMERODECREDITO { get; set; }

        [Required()]
        public decimal VALORDELACUOTA { get; set; }

        [Required()]
        public bool IsActive { get; set; }

        [Required()]
        public DateTime CreatedOn { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
