//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2025-10-19 11:13:49
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace v4posme_library.Models
{
    public partial class TbBranch {

        public TbBranch()
        {
            this.CompanyID = 0;
            this.Name = @"N/D";
            OnCreated();
        }

        public int BranchID { get; set; }

        public int CompanyID { get; set; }

        public string Name { get; set; }

        public DateTime? CreatedOn { get; set; }

        public bool? IsActive { get; set; }

        public string? Address { get; set; }

        public string? Serie { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
