//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2025-10-19 11:13:49
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace v4posme_library.Models
{
    public partial class TbCustomerCreditDocument {

        public TbCustomerCreditDocument()
        {
            this.CompanyID = 0;
            this.EntityID = 0;
            this.CustomerCreditLineID = 0;
            this.DocumentNumber = @"0";
            this.Amount = 0.000000000m;
            this.Interes = 0.000000000m;
            this.Term = 0;
            this.Balance = 0.000000000m;
            this.BalanceProvicioned = 0.000000000m;
            this.ExchangeRate = 1.0000m;
            this.CurrencyID = 1;
            this.StatusID = 0;
            this.IsActive = false;
            this.TypeAmortization = 0;
            this.PeriodPay = 0;
            this.ProviderIDCredit = 0;
            this.ReportSinRiesgo = 1;
            OnCreated();
        }

        public int CustomerCreditDocumentID { get; set; }

        public int CompanyID { get; set; }

        public int EntityID { get; set; }

        public int CustomerCreditLineID { get; set; }

        public string DocumentNumber { get; set; }

        public DateTime DateOn { get; set; }

        public decimal Amount { get; set; }

        public decimal Interes { get; set; }

        public int Term { get; set; }

        public decimal Balance { get; set; }

        public decimal BalanceProvicioned { get; set; }

        public decimal ExchangeRate { get; set; }

        public int CurrencyID { get; set; }

        public string? Reference1 { get; set; }

        public string? Reference2 { get; set; }

        public string? Reference3 { get; set; }

        public int StatusID { get; set; }

        public bool IsActive { get; set; }

        public int TypeAmortization { get; set; }

        public int PeriodPay { get; set; }

        public int ProviderIDCredit { get; set; }

        public int ReportSinRiesgo { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
