//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2025-06-24 14:25:27
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace v4posme_library.Models
{
    public partial class TbTransactionMasterDetailReference {

        public TbTransactionMasterDetailReference()
        {
            this.Precio1 = 0.00m;
            this.Precio2 = 0.00m;
            this.Precio3 = 0.00m;
            this.Precio4 = 0.00m;
            this.Precio5 = 0.00m;
            this.Precio6 = 0.00m;
            OnCreated();
        }

        public int TransactionMasterDetailID { get; set; }

        public int TransactionMasterDetailRefereceID { get; set; }

        public int? ComponentID { get; set; }

        public int? ComponentItemID { get; set; }

        public string? Quantity { get; set; }

        public DateTime? CreatedOn { get; set; }

        public string? Reference1 { get; set; }

        public string? Reference2 { get; set; }

        public string? Sales { get; set; }

        public short? IsActive { get; set; }

        public decimal? Precio1 { get; set; }

        public decimal? Precio2 { get; set; }

        public decimal? Precio3 { get; set; }

        public decimal? Precio4 { get; set; }

        public decimal? Precio5 { get; set; }

        public decimal? Precio6 { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
