//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 22/12/2024 9:47:43 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace v4posme_library.Models
{
    public partial class TbAccountingBalance {

        public TbAccountingBalance()
        {
            this.ComponentCycleID = 0;
            this.ComponentPeriodID = 0;
            this.CompanyID = 0;
            this.ComponentID = 0;
            this.AccountID = 0;
            this.BranchID = 0;
            this.Debit = 0.00000000m;
            this.Credit = 0.00000000m;
            this.IsActive = false;
            OnCreated();
        }

        public TbAccountingBalance(int accountBalanceID, decimal? balance, int? classID) : this()        {
            this.AccountBalanceID = accountBalanceID;
            this.Balance = balance;
            this.ClassID = classID;
        }

        [Key]
        [Required()]
        public int AccountBalanceID { get; set; }

        [Required()]
        public int ComponentCycleID { get; set; }

        [Required()]
        public int ComponentPeriodID { get; set; }

        [Required()]
        public int CompanyID { get; set; }

        [Required()]
        public int ComponentID { get; set; }

        [Required()]
        public int AccountID { get; set; }

        [Required()]
        public int BranchID { get; set; }

        public decimal? Balance { get; set; }

        [Required()]
        public decimal Debit { get; set; }

        [Required()]
        public decimal Credit { get; set; }

        public int? ClassID { get; set; }

        [Required()]
        public bool IsActive { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
