//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2025-06-24 14:25:27
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace v4posme_library.Models
{
    public partial class TbAccountTmp {

        public TbAccountTmp()
        {
            OnCreated();
        }

        public int AccountID { get; set; }

        public int? AccountParentID { get; set; }

        public string? N1 { get; set; }

        public string? N2 { get; set; }

        public string? N3 { get; set; }

        public string? N4 { get; set; }

        public string? N5 { get; set; }

        public string? Name { get; set; }

        public int? Nivel { get; set; }

        public bool? Operative { get; set; }

        public decimal? Balance { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
