//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2025-06-24 14:25:27
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace v4posme_library.Models
{
    public partial class TbTransactionMasterDetailTemp {

        public TbTransactionMasterDetailTemp()
        {
            this.CompanyID = 0;
            this.TransactionID = 0;
            this.TransactionMasterID = 0;
            this.ItemFormulatedApplied = false;
            this.TypePriceID = 0;
            this.SkuCatalogItemID = 0;
            this.SkuQuantity = 0.00m;
            this.SkuQuantityBySku = 0.00m;
            OnCreated();
        }

        public int TransactionMasterDetailTemporalID { get; set; }

        public string? Token { get; set; }

        public int CompanyID { get; set; }

        public int TransactionID { get; set; }

        public int TransactionMasterID { get; set; }

        public int TransactionMasterDetailID { get; set; }

        public int ComponentID { get; set; }

        public int? ComponentItemID { get; set; }

        public int? PromotionID { get; set; }

        public decimal? Amount { get; set; }

        public decimal? Cost { get; set; }

        public decimal? Quantity { get; set; }

        public decimal? Discount { get; set; }

        public decimal? UnitaryAmount { get; set; }

        public decimal? Tax1 { get; set; }

        public decimal? Tax2 { get; set; }

        public decimal? Tax3 { get; set; }

        public decimal? Tax4 { get; set; }

        public decimal? UnitaryCost { get; set; }

        public decimal? UnitaryPrice { get; set; }

        public string? Reference1 { get; set; }

        public string? Reference2 { get; set; }

        public string? Reference3 { get; set; }

        public string? Reference4 { get; set; }

        public string? Reference5 { get; set; }

        public string? Reference6 { get; set; }

        public string? Reference7 { get; set; }

        public string? DescriptionReference { get; set; }

        public decimal? ExchangeRateReference { get; set; }

        public int? CatalogStatusID { get; set; }

        public int? InventoryStatusID { get; set; }

        public bool? IsActive { get; set; }

        public decimal? QuantityStock { get; set; }

        public decimal? QuantiryStockInTraffic { get; set; }

        public decimal? QuantityStockUnaswared { get; set; }

        public decimal? RemaingStock { get; set; }

        public DateTime? ExpirationDate { get; set; }

        public int? InventoryWarehouseSourceID { get; set; }

        public int? InventoryWarehouseTargetID { get; set; }

        public bool ItemFormulatedApplied { get; set; }

        public int TypePriceID { get; set; }

        public int SkuCatalogItemID { get; set; }

        public decimal SkuQuantity { get; set; }

        public decimal SkuQuantityBySku { get; set; }

        public string? SkuFormatoDescription { get; set; }

        public string? ItemNameLog { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
