//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2025-06-24 14:25:27
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace v4posme_library.Models
{
    public partial class PrCxcGetReportCustomerListResult {

        public PrCxcGetReportCustomerListResult()
        {
            OnCreated();
        }

        public string CustomerNumber { get; set; }

        public string? CustomerName { get; set; }

        public string Identification { get; set; }

        public string? Phone { get; set; }

        public string? Email { get; set; }

        public string Moneda { get; set; }

        public decimal? BalanceTotal { get; set; }

        public decimal? BalanceTotalCapital { get; set; }

        public decimal? BalanceTotalInteres { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
