//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2025-06-24 14:25:27
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace v4posme_library.Models
{
    /// <summary>
    /// VIEW
    /// </summary>
    public partial class VwContabilidadComprobante {

        public VwContabilidadComprobante()
        {
            OnCreated();
        }

        public string CodigoComprobante { get; set; }

        public DateTime FechaComprobante { get; set; }

        public decimal TipoCambioComprobante { get; set; }

        public string? EstadoComprobante { get; set; }

        public decimal DebitoComprobante { get; set; }

        public decimal CrditoComprobante { get; set; }

        public string? TipoComprobante { get; set; }

        public string MonedaComprobante { get; set; }

        public string? CentroCostoCuenta { get; set; }

        public string CodigoCuenta { get; set; }

        public string NombreCuenta { get; set; }

        public decimal DebitoCuenta { get; set; }

        public decimal CreditoCuenta { get; set; }

        public string TipoCuenta { get; set; }

        public string BeneficiarioComprobante { get; set; }

        public string? NotaComprobante { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
