//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 22/12/2024 9:47:43 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace v4posme_library.Models
{
    public partial class TbItemWarehouseExpired {

        public TbItemWarehouseExpired()
        {
            OnCreated();
        }

        public TbItemWarehouseExpired(int itemWarehouseExpiredID, decimal? quantity, string? lote) : this()        {
            this.ItemWarehouseExpiredID = itemWarehouseExpiredID;
            this.Quantity = quantity;
            this.Lote = lote;
        }

        [Key]
        [Required()]
        public int ItemWarehouseExpiredID { get; set; }

        [Required()]
        public int WarehouseID { get; set; }

        [Required()]
        public int ItemID { get; set; }

        [Required()]
        public int CompanyID { get; set; }

        public decimal? Quantity { get; set; }

        [StringLength(50)]
        public string? Lote { get; set; }

        [Required()]
        public DateTime DateExpired { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
