//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 26/9/2024 4:44:37 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace v4posme_library.Models
{
    public partial class TbTransactionMaster {

        public TbTransactionMaster()
        {
            this.CompanyID = 0;
            this.TransactionNumber = @"0";
            this.TransactionID = 0;
            this.DescriptionReference = @"0";
            this.IsTemplate = 0;
            this.PrinterQuantity = 0;
            OnCreated();
        }

        public TbTransactionMaster(int transactionMasterID, int? branchID, int? transactionCausalID, int? entityID, DateTime? transactionOn, DateTime? transactionOn2, DateTime? statusIDChangeOn, int? componentID, string? note, short? sign, int? currencyID, int? currencyID2, decimal? exchangeRate, string? reference1, string? reference2, string? reference3, string? reference4, int? statusID, decimal? amount, decimal? tax1, decimal? tax2, decimal? tax3, decimal? tax4, decimal? discount, decimal? subAmount, bool? isApplied, int? journalEntryID, int? classID, int? areaID, int? priorityID, int? sourceWarehouseID, int? targetWarehouseID, int? createdBy, int? createdAt, DateTime? createdOn, string? createdIn, bool? isActive, int? periodPay, DateTime? nextVisit, string? numberPhone, int? notificationID, int? entityIDSecondary) : this()        {
            this.TransactionMasterID = transactionMasterID;
            this.BranchID = branchID;
            this.TransactionCausalID = transactionCausalID;
            this.EntityID = entityID;
            this.TransactionOn = transactionOn;
            this.TransactionOn2 = transactionOn2;
            this.StatusIDChangeOn = statusIDChangeOn;
            this.ComponentID = componentID;
            this.Note = note;
            this.Sign = sign;
            this.CurrencyID = currencyID;
            this.CurrencyID2 = currencyID2;
            this.ExchangeRate = exchangeRate;
            this.Reference1 = reference1;
            this.Reference2 = reference2;
            this.Reference3 = reference3;
            this.Reference4 = reference4;
            this.StatusID = statusID;
            this.Amount = amount;
            this.Tax1 = tax1;
            this.Tax2 = tax2;
            this.Tax3 = tax3;
            this.Tax4 = tax4;
            this.Discount = discount;
            this.SubAmount = subAmount;
            this.IsApplied = isApplied;
            this.JournalEntryID = journalEntryID;
            this.ClassID = classID;
            this.AreaID = areaID;
            this.PriorityID = priorityID;
            this.SourceWarehouseID = sourceWarehouseID;
            this.TargetWarehouseID = targetWarehouseID;
            this.CreatedBy = createdBy;
            this.CreatedAt = createdAt;
            this.CreatedOn = createdOn;
            this.CreatedIn = createdIn;
            this.IsActive = isActive;
            this.PeriodPay = periodPay;
            this.NextVisit = nextVisit;
            this.NumberPhone = numberPhone;
            this.NotificationID = notificationID;
            this.EntityIDSecondary = entityIDSecondary;
        }

        [Key]
        [Required()]
        public int TransactionMasterID { get; set; }

        [Required()]
        public int CompanyID { get; set; }

        [StringLength(250)]
        [Required()]
        public string TransactionNumber { get; set; }

        [Required()]
        public int TransactionID { get; set; }

        public int? BranchID { get; set; }

        public int? TransactionCausalID { get; set; }

        public int? EntityID { get; set; }

        public DateTime? TransactionOn { get; set; }

        public DateTime? TransactionOn2 { get; set; }

        public DateTime? StatusIDChangeOn { get; set; }

        public int? ComponentID { get; set; }

        [StringLength(3500)]
        public string? Note { get; set; }

        public short? Sign { get; set; }

        public int? CurrencyID { get; set; }

        public int? CurrencyID2 { get; set; }

        public decimal? ExchangeRate { get; set; }

        [StringLength(250)]
        public string? Reference1 { get; set; }

        [StringLength(250)]
        public string? Reference2 { get; set; }

        [StringLength(250)]
        public string? Reference3 { get; set; }

        [StringLength(250)]
        public string? Reference4 { get; set; }

        [StringLength(4000)]
        [Required()]
        public string DescriptionReference { get; set; }

        public int? StatusID { get; set; }

        public decimal? Amount { get; set; }

        public decimal? Tax1 { get; set; }

        public decimal? Tax2 { get; set; }

        public decimal? Tax3 { get; set; }

        public decimal? Tax4 { get; set; }

        public decimal? Discount { get; set; }

        public decimal? SubAmount { get; set; }

        public bool? IsApplied { get; set; }

        public int? JournalEntryID { get; set; }

        public int? ClassID { get; set; }

        public int? AreaID { get; set; }

        public int? PriorityID { get; set; }

        public int? SourceWarehouseID { get; set; }

        public int? TargetWarehouseID { get; set; }

        public int? CreatedBy { get; set; }

        public int? CreatedAt { get; set; }

        public DateTime? CreatedOn { get; set; }

        [StringLength(250)]
        public string? CreatedIn { get; set; }

        public bool? IsActive { get; set; }

        public int? IsTemplate { get; set; }

        public int? PeriodPay { get; set; }

        public DateTime? NextVisit { get; set; }

        [StringLength(250)]
        public string? NumberPhone { get; set; }

        public int? NotificationID { get; set; }

        public int? PrinterQuantity { get; set; }

        public int? EntityIDSecondary { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
