//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 3/1/2025 3:48:59 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace v4posme_library.Models
{
    public partial class TbProvider {

        public TbProvider()
        {
            this.CompanyID = 0;
            this.BranchID = 0;
            this.EntityID = 0;
            this.ProviderNumber = @"0";
            OnCreated();
        }

        public TbProvider(int providerID, string? numberIdentification, int? identificationTypeID, int? providerType, int? providerCategoryID, int? providerClasificationID, string? reference1, string? reference2, int? payConditionID, bool? isLocal, int? countryID, int? stateID, int? cityID, string? address, int? currencyID, int? statusID, int? deleveryDay, int? deleveryDayReal, decimal? distancia, string? createdIn, int? createdBy, int? createdAt, DateTime? createdOn, bool? isActive) : this()        {
            this.ProviderID = providerID;
            this.NumberIdentification = numberIdentification;
            this.IdentificationTypeID = identificationTypeID;
            this.ProviderType = providerType;
            this.ProviderCategoryID = providerCategoryID;
            this.ProviderClasificationID = providerClasificationID;
            this.Reference1 = reference1;
            this.Reference2 = reference2;
            this.PayConditionID = payConditionID;
            this.IsLocal = isLocal;
            this.CountryID = countryID;
            this.StateID = stateID;
            this.CityID = cityID;
            this.Address = address;
            this.CurrencyID = currencyID;
            this.StatusID = statusID;
            this.DeleveryDay = deleveryDay;
            this.DeleveryDayReal = deleveryDayReal;
            this.Distancia = distancia;
            this.CreatedIn = createdIn;
            this.CreatedBy = createdBy;
            this.CreatedAt = createdAt;
            this.CreatedOn = createdOn;
            this.IsActive = isActive;
        }

        [Key]
        [Required()]
        public int ProviderID { get; set; }

        [Required()]
        public int CompanyID { get; set; }

        [Required()]
        public int BranchID { get; set; }

        [Required()]
        public int EntityID { get; set; }

        [StringLength(250)]
        [Required()]
        public string ProviderNumber { get; set; }

        [StringLength(250)]
        public string? NumberIdentification { get; set; }

        public int? IdentificationTypeID { get; set; }

        public int? ProviderType { get; set; }

        public int? ProviderCategoryID { get; set; }

        public int? ProviderClasificationID { get; set; }

        [StringLength(250)]
        public string? Reference1 { get; set; }

        [StringLength(250)]
        public string? Reference2 { get; set; }

        public int? PayConditionID { get; set; }

        public bool? IsLocal { get; set; }

        public int? CountryID { get; set; }

        public int? StateID { get; set; }

        public int? CityID { get; set; }

        [StringLength(250)]
        public string? Address { get; set; }

        public int? CurrencyID { get; set; }

        public int? StatusID { get; set; }

        public int? DeleveryDay { get; set; }

        public int? DeleveryDayReal { get; set; }

        public decimal? Distancia { get; set; }

        [StringLength(250)]
        public string? CreatedIn { get; set; }

        public int? CreatedBy { get; set; }

        public int? CreatedAt { get; set; }

        public DateTime? CreatedOn { get; set; }

        public bool? IsActive { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
