//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 26/9/2024 4:44:37 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace v4posme_library.Models
{
    public partial class TbJournalEntry {

        public TbJournalEntry()
        {
            this.CompanyID = 0;
            this.JournalNumber = @"0";
            this.TbExchangeRate = 0.00000000m;
            this.IsActive = false;
            this.IsApplied = false;
            this.TitleTemplated = @"N/A";
            this.IsTemplated = false;
            this.StatusID = 0;
            this.Debit = 0.00m;
            this.Credit = 0.00m;
            this.JournalTypeID = 0;
            this.CurrencyID = 0;
            this.AccountingCycleID = 0;
            this.EntryName = @"0";
            this.IsModule = false;
            this.TransactionMasterID = 0;
            this.TransactionID = 0;
            OnCreated();
        }

        public TbJournalEntry(int journalEntryID, DateTime journalDate, DateTime? createdOn, string? createdIn, int? createdAt, int? createdBy, string? note, string? reference1, string? reference2, string? reference3) : this()        {
            this.JournalEntryID = journalEntryID;
            this.JournalDate = journalDate;
            this.CreatedOn = createdOn;
            this.CreatedIn = createdIn;
            this.CreatedAt = createdAt;
            this.CreatedBy = createdBy;
            this.Note = note;
            this.Reference1 = reference1;
            this.Reference2 = reference2;
            this.Reference3 = reference3;
        }

        [Key]
        [Required()]
        public int JournalEntryID { get; set; }

        [Required()]
        public int CompanyID { get; set; }

        [StringLength(250)]
        [Required()]
        public string JournalNumber { get; set; }

        [Required()]
        public DateTime JournalDate { get; set; }

        [Required()]
        public decimal TbExchangeRate { get; set; }

        public DateTime? CreatedOn { get; set; }

        [StringLength(250)]
        public string? CreatedIn { get; set; }

        public int? CreatedAt { get; set; }

        public int? CreatedBy { get; set; }

        [Required()]
        public bool IsActive { get; set; }

        [Required()]
        public bool IsApplied { get; set; }

        [StringLength(250)]
        [Required()]
        public string TitleTemplated { get; set; }

        [Required()]
        public bool IsTemplated { get; set; }

        [Required()]
        public int StatusID { get; set; }

        [StringLength(550)]
        public string? Note { get; set; }

        [StringLength(250)]
        public string? Reference1 { get; set; }

        [StringLength(250)]
        public string? Reference2 { get; set; }

        [StringLength(250)]
        public string? Reference3 { get; set; }

        [Required()]
        public decimal Debit { get; set; }

        [Required()]
        public decimal Credit { get; set; }

        [Required()]
        public int JournalTypeID { get; set; }

        [Required()]
        public int CurrencyID { get; set; }

        [Required()]
        public int AccountingCycleID { get; set; }

        [StringLength(500)]
        [Required()]
        public string EntryName { get; set; }

        [Required()]
        public bool IsModule { get; set; }

        [Required()]
        public int TransactionMasterID { get; set; }

        [Required()]
        public int TransactionID { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
