//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2025-10-19 11:13:49
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace v4posme_library.Models
{
    public partial class TbTransactionCausal {

        public TbTransactionCausal()
        {
            this.CompanyID = 0;
            this.TransactionID = 0;
            this.Name = @"0";
            this.IsDefault = false;
            this.IsActive = false;
            OnCreated();
        }

        public int TransactionCausalID { get; set; }

        public int CompanyID { get; set; }

        public int TransactionID { get; set; }

        public int? BranchID { get; set; }

        public string Name { get; set; }

        public int? WarehouseSourceID { get; set; }

        public int? WarehouseTargetID { get; set; }

        public bool IsDefault { get; set; }

        public bool IsActive { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
