//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2025-06-24 14:25:27
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace v4posme_library.Models
{
    public partial class PrCxcGetReportInteresPeriodoResult {

        public PrCxcGetReportInteresPeriodoResult()
        {
            OnCreated();
        }

        public string CustomerNumber { get; set; }

        public string? LegalName { get; set; }

        public DateTime DocumentFecha { get; set; }

        public string DocumentNumber { get; set; }

        public DateTime? TransactionFecha { get; set; }

        public string TransactionNumber { get; set; }

        public string TransactionName { get; set; }

        public decimal? Balance { get; set; }

        public decimal? Capital { get; set; }

        public decimal? Interest { get; set; }

        public decimal? ExchangeRate { get; set; }

        public decimal? Sale { get; set; }

        public decimal? Purchase { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
