//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 4/10/2024 4:53:03 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace v4posme_library.Models
{
    public partial class TbRoleAutorization {

        public TbRoleAutorization()
        {
            this.CompanyID = 0;
            this.ComponentAutorizationID = 0;
            this.RoleID = 0;
            this.BranchID = 0;
            OnCreated();
        }

        public TbRoleAutorization(int roleAurotizationID) : this()        {
            this.RoleAurotizationID = roleAurotizationID;
        }

        [Key]
        [Required()]
        public int RoleAurotizationID { get; set; }

        [Required()]
        public int CompanyID { get; set; }

        [Required()]
        public int ComponentAutorizationID { get; set; }

        [Required()]
        public int RoleID { get; set; }

        [Required()]
        public int BranchID { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
