//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 8/11/2024 1:24:05 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace v4posme_library.Models
{
    public partial class TbCustomer {

        public TbCustomer()
        {
            this.CompanyID = 0;
            this.BranchID = 0;
            this.EntityID = 0;
            this.CustomerNumber = @"0";
            this.Identification = @"0";
            this.TypeFirm = 0;
            this.Budget = 0.00m;
            this.FormContactID = 0;
            OnCreated();
        }

        public TbCustomer(int customerID, int? identificationType, int? countryID, int? stateID, int? cityID, string? location, string? address, int? currencyID, int? clasificationID, int? categoryID, int? subCategoryID, int? customerTypeID, DateTime? birthDate, int? statusID, int? typePay, int? payConditionID, int? sexoID, string? reference1, string? reference2, string? createdIn, int? createdBy, DateTime? createdOn, int? createdAt, bool? isActive, decimal? balancePoint, byte[]? phoneNumber, DateTime? dateContract, int? entityContactID, string? reference3, string? reference4, string? reference5, string? reference6, DateTime? modifiedOn) : this()        {
            this.CustomerID = customerID;
            this.IdentificationType = identificationType;
            this.CountryID = countryID;
            this.StateID = stateID;
            this.CityID = cityID;
            this.Location = location;
            this.Address = address;
            this.CurrencyID = currencyID;
            this.ClasificationID = clasificationID;
            this.CategoryID = categoryID;
            this.SubCategoryID = subCategoryID;
            this.CustomerTypeID = customerTypeID;
            this.BirthDate = birthDate;
            this.StatusID = statusID;
            this.TypePay = typePay;
            this.PayConditionID = payConditionID;
            this.SexoID = sexoID;
            this.Reference1 = reference1;
            this.Reference2 = reference2;
            this.CreatedIn = createdIn;
            this.CreatedBy = createdBy;
            this.CreatedOn = createdOn;
            this.CreatedAt = createdAt;
            this.IsActive = isActive;
            this.BalancePoint = balancePoint;
            this.PhoneNumber = phoneNumber;
            this.DateContract = dateContract;
            this.EntityContactID = entityContactID;
            this.Reference3 = reference3;
            this.Reference4 = reference4;
            this.Reference5 = reference5;
            this.Reference6 = reference6;
            this.ModifiedOn = modifiedOn;
        }

        [Key]
        [Required()]
        public int CustomerID { get; set; }

        [Required()]
        public int CompanyID { get; set; }

        [Required()]
        public int BranchID { get; set; }

        [Required()]
        public int EntityID { get; set; }

        [StringLength(250)]
        [Required()]
        public string CustomerNumber { get; set; }

        public int? IdentificationType { get; set; }

        [StringLength(250)]
        [Required()]
        public string Identification { get; set; }

        public int? CountryID { get; set; }

        public int? StateID { get; set; }

        public int? CityID { get; set; }

        [StringLength(250)]
        public string? Location { get; set; }

        [StringLength(1500)]
        public string? Address { get; set; }

        public int? CurrencyID { get; set; }

        public int? ClasificationID { get; set; }

        public int? CategoryID { get; set; }

        public int? SubCategoryID { get; set; }

        public int? CustomerTypeID { get; set; }

        public DateTime? BirthDate { get; set; }

        public int? StatusID { get; set; }

        public int? TypePay { get; set; }

        public int? PayConditionID { get; set; }

        public int? SexoID { get; set; }

        /// <summary>
        /// Tipo de Firma
        /// </summary>
        public int? TypeFirm { get; set; }

        [StringLength(250)]
        public string? Reference1 { get; set; }

        [StringLength(250)]
        public string? Reference2 { get; set; }

        [StringLength(250)]
        public string? CreatedIn { get; set; }

        public int? CreatedBy { get; set; }

        public DateTime? CreatedOn { get; set; }

        public int? CreatedAt { get; set; }

        public bool? IsActive { get; set; }

        public decimal? BalancePoint { get; set; }

        public byte[]? PhoneNumber { get; set; }

        public DateTime? DateContract { get; set; }

        /// <summary>
        /// Persona que contacto al cliente
        /// </summary>
        public int? EntityContactID { get; set; }

        [StringLength(255)]
        public string? Reference3 { get; set; }

        [StringLength(255)]
        public string? Reference4 { get; set; }

        [StringLength(255)]
        public string? Reference5 { get; set; }

        [StringLength(255)]
        public string? Reference6 { get; set; }

        public decimal? Budget { get; set; }

        public DateTime? ModifiedOn { get; set; }

        public int? FormContactID { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
