//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2025-06-24 14:25:27
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace v4posme_library.Models
{
    public partial class TbAccountType {

        public TbAccountType()
        {
            this.CompanyID = 0;
            this.Name = @"0";
            this.Naturaleza = @"0";
            this.CreatedBy = 0;
            this.CreatedAt = @"0";
            this.CreatedIn = @"0";
            OnCreated();
        }

        public int CompanyID { get; set; }

        public int AccountTypeID { get; set; }

        public string Name { get; set; }

        public string Naturaleza { get; set; }

        public string? Description { get; set; }

        public int CreatedBy { get; set; }

        public string CreatedAt { get; set; }

        public DateTime CreatedOn { get; set; }

        public string CreatedIn { get; set; }

        public bool? IsActive { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
