//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2025-10-19 11:13:49
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace v4posme_library.Models
{
    public partial class PrCxcGetReportCustomerExpensaResult2 {

        public PrCxcGetReportCustomerExpensaResult2()
        {
            OnCreated();
        }

        public int CustomerCreditDocumentID { get; set; }

        public string TransactionNumber { get; set; }

        public DateTime? CreatedOn { get; set; }

        public decimal? Amount { get; set; }

        public string Simbol { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
