//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2025-06-24 14:25:27
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace v4posme_library.Models
{
    public partial class TbLegal {

        public TbLegal()
        {
            this.CompanyID = 0;
            this.BranchID = 0;
            this.EntityID = 0;
            this.ComercialName = @"N/D";
            this.LegalName = @"N/D";
            this.Address = @"N/D";
            OnCreated();
        }

        public int CompanyID { get; set; }

        public int BranchID { get; set; }

        public int EntityID { get; set; }

        public string? ComercialName { get; set; }

        public string? LegalName { get; set; }

        public string? Address { get; set; }

        public bool? IsActive { get; set; }

        public int LegalID { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
