//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2025-10-19 11:13:49
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace v4posme_library.Models
{
    public partial class PrCxcGetReportInfoProyectResult {

        public PrCxcGetReportInfoProyectResult()
        {
            OnCreated();
        }

        public string CustomerNumber { get; set; }

        public string? LegalName { get; set; }

        public DateTime Fecha { get; set; }

        public string? FechaPeriodo { get; set; }

        public decimal? Capital { get; set; }

        public decimal? Interest { get; set; }

        public decimal? Cuota { get; set; }

        public decimal? Remaining { get; set; }

        public string Moneda { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
