//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 3/1/2025 3:48:59 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace v4posme_library.Models
{
    public partial class TbError {

        public TbError()
        {
            OnCreated();
        }

        public TbError(int errorID, int? tagID, string? notificated, string? message, sbyte? isActive, sbyte? isRead, int? userID, DateTime? createdOn, DateTime? readOn) : this()        {
            this.ErrorID = errorID;
            this.TagID = tagID;
            this.Notificated = notificated;
            this.Message = message;
            this.IsActive = isActive;
            this.IsRead = isRead;
            this.UserID = userID;
            this.CreatedOn = createdOn;
            this.ReadOn = readOn;
        }

        [Key]
        [Required()]
        public int ErrorID { get; set; }

        public int? TagID { get; set; }

        [StringLength(50)]
        public string? Notificated { get; set; }

        [StringLength(500)]
        public string? Message { get; set; }

        public sbyte? IsActive { get; set; }

        public sbyte? IsRead { get; set; }

        public int? UserID { get; set; }

        public DateTime? CreatedOn { get; set; }

        public DateTime? ReadOn { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
