//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 24/10/2024 8:54:25 AM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace v4posme_library.Models
{
    public partial class TbWorkflowStageRelation {

        public TbWorkflowStageRelation()
        {
            this.ComponentID = 0;
            this.WorkflowID = 0;
            this.WorkflowStageID = 0;
            this.WorkflowStageTargetID = 0;
            OnCreated();
        }

        public TbWorkflowStageRelation(int workflowStageRelationID, bool? necesitaAuth, int? authRolID) : this()        {
            this.WorkflowStageRelationID = workflowStageRelationID;
            this.NecesitaAuth = necesitaAuth;
            this.AuthRolID = authRolID;
        }

        [Key]
        [Required()]
        public int WorkflowStageRelationID { get; set; }

        [Required()]
        public int ComponentID { get; set; }

        [Required()]
        public int WorkflowID { get; set; }

        [Required()]
        public int WorkflowStageID { get; set; }

        [Required()]
        public int WorkflowStageTargetID { get; set; }

        public bool? NecesitaAuth { get; set; }

        public int? AuthRolID { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
