//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 4/10/2024 4:53:03 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace v4posme_library.Models
{
    public partial class TbTypeMenuElement {

        public TbTypeMenuElement()
        {
            this.Name = @"0";
            OnCreated();
        }

        public TbTypeMenuElement(int typeMenuElementID) : this()        {
            this.TypeMenuElementID = typeMenuElementID;
        }

        [Key]
        [Required()]
        public int TypeMenuElementID { get; set; }

        [StringLength(250)]
        [Required()]
        public string Name { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
