//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2025-06-24 14:25:27
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace v4posme_library.Models
{
    public partial class PrInventoryGetReportMasterKardexResult {

        public PrInventoryGetReportMasterKardexResult()
        {
            OnCreated();
        }

        public int UserID { get; set; }

        public string? TokenID { get; set; }

        public int CompanyID { get; set; }

        public int ItemID { get; set; }

        public string ItemNumber { get; set; }

        public string ItemName { get; set; }

        public int MinKardexID { get; set; }

        public decimal QuantityInicial { get; set; }

        public decimal CostInicial { get; set; }

        public decimal QuantityInput { get; set; }

        public decimal CostInput { get; set; }

        public decimal QuantityOutput { get; set; }

        public decimal CostOutput { get; set; }

        public int MasterKardexTempID { get; set; }

        public string? ItemCategoryName { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
