//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 22/12/2024 9:47:43 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace v4posme_library.Models
{
    public partial class TbCustomerCreditLine {

        public TbCustomerCreditLine()
        {
            this.CompanyID = 0;
            this.BranchID = 0;
            this.EntityID = 0;
            this.CreditLineID = 0;
            this.AccountNumber = @"0";
            this.CurrencyID = 0;
            this.TypeAmortization = 0;
            this.LimitCredit = 0.000000000m;
            this.Balance = 0.000000000m;
            this.InterestYear = 0.000000000m;
            this.InterestPay = 0.000000000m;
            this.TotalPay = 0.000000000m;
            this.TotalDefeated = 0.000000000m;
            this.PeriodPay = 0;
            this.StatusID = 0;
            this.IsActive = false;
            OnCreated();
        }

        public TbCustomerCreditLine(int customerCreditLineID, DateTime dateOpen, DateTime? dateLastPay, int? term, string? note, int? dayExcluded) : this()        {
            this.CustomerCreditLineID = customerCreditLineID;
            this.DateOpen = dateOpen;
            this.DateLastPay = dateLastPay;
            this.Term = term;
            this.Note = note;
            this.DayExcluded = dayExcluded;
        }

        [Key]
        [Required()]
        public int CustomerCreditLineID { get; set; }

        [Required()]
        public int CompanyID { get; set; }

        [Required()]
        public int BranchID { get; set; }

        [Required()]
        public int EntityID { get; set; }

        [Required()]
        public int CreditLineID { get; set; }

        [StringLength(25)]
        [Required()]
        public string AccountNumber { get; set; }

        [Required()]
        public int CurrencyID { get; set; }

        [Required()]
        public int TypeAmortization { get; set; }

        [Required()]
        public decimal LimitCredit { get; set; }

        [Required()]
        public decimal Balance { get; set; }

        [Required()]
        public decimal InterestYear { get; set; }

        [Required()]
        public decimal InterestPay { get; set; }

        [Required()]
        public decimal TotalPay { get; set; }

        [Required()]
        public decimal TotalDefeated { get; set; }

        [Required()]
        public DateTime DateOpen { get; set; }

        [Required()]
        public int PeriodPay { get; set; }

        public DateTime? DateLastPay { get; set; }

        public int? Term { get; set; }

        [StringLength(550)]
        public string? Note { get; set; }

        [Required()]
        public int StatusID { get; set; }

        [Required()]
        public bool IsActive { get; set; }

        public int? DayExcluded { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
