//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2025-06-24 14:25:27
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace v4posme_library.Models
{
    public partial class PrInventoryGetEportListItemExpiredResult {

        public PrInventoryGetEportListItemExpiredResult()
        {
            OnCreated();
        }

        public string ItemNumber { get; set; }

        public string? ItemName { get; set; }

        public string? UnitMeasure { get; set; }

        public string CategoryName { get; set; }

        public decimal Quantity { get; set; }

        public decimal Cost { get; set; }

        public decimal? PricePublico { get; set; }

        public string WarehouseName { get; set; }

        public DateTime DateExpired { get; set; }

        public decimal? QuantityExpired { get; set; }

        public string? Lote { get; set; }

        public string? ProveedorName { get; set; }

        public int? DateExpiredInDay { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
