//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2025-06-24 14:25:27
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace v4posme_library.Models
{
    public partial class PrSalesGetReportSalesByClientResult {

        public PrSalesGetReportSalesByClientResult()
        {
            OnCreated();
        }

        public string CustomerNumber { get; set; }

        public string? LegalName { get; set; }

        public decimal? Quantity { get; set; }

        public decimal? Cost { get; set; }

        public decimal? Amount { get; set; }

        public decimal? AmountConIva { get; set; }

        public decimal? Utilidad { get; set; }

        public decimal? Iva { get; set; }

        public decimal? IvaTotal { get; set; }

        public int? VarCurrencyReporte { get; set; }

        public int? CurrencyID { get; set; }

        public decimal? AmountCommision { get; set; }

        public decimal? PagoConPuntos { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
