//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 24/10/2024 8:54:25 AM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace v4posme_library.Models
{
    public partial class TbComponentAuditDetail {

        public TbComponentAuditDetail()
        {
            this.CompanyID = 0;
            this.BranchID = 0;
            this.ComponentAuditID = 0;
            OnCreated();
        }

        public TbComponentAuditDetail(int componentAuditDetailID, int? fieldID, string? oldValue, string? newValue, string? note) : this()        {
            this.ComponentAuditDetailID = componentAuditDetailID;
            this.FieldID = fieldID;
            this.OldValue = oldValue;
            this.NewValue = newValue;
            this.Note = note;
        }

        [Key]
        [Required()]
        public int ComponentAuditDetailID { get; set; }

        [Required()]
        public int CompanyID { get; set; }

        [Required()]
        public int BranchID { get; set; }

        [Required()]
        public int ComponentAuditID { get; set; }

        public int? FieldID { get; set; }

        [StringLength(250)]
        public string? OldValue { get; set; }

        [StringLength(250)]
        public string? NewValue { get; set; }

        [StringLength(250)]
        public string? Note { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
