//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 24/10/2024 8:54:25 AM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace v4posme_library.Models
{
    public partial class TbWarehouse {

        public TbWarehouse()
        {
            this.CompanyID = 0;
            this.BranchID = 0;
            this.Number = @"0";
            this.Name = @"0";
            this.StatusID = 0;
            this.IsActive = false;
            this.CreatedBy = 0;
            this.CreatedIn = @"0";
            this.CreatedAt = 0;
            this.TypeWarehouse = 0;
            OnCreated();
        }

        public TbWarehouse(int warehouseID, string? address, DateTime createdOn, string? emailResponsability) : this()        {
            this.WarehouseID = warehouseID;
            this.Address = address;
            this.CreatedOn = createdOn;
            this.EmailResponsability = emailResponsability;
        }

        [Key]
        [Required()]
        public int WarehouseID { get; set; }

        [Required()]
        public int CompanyID { get; set; }

        [Required()]
        public int BranchID { get; set; }

        [StringLength(50)]
        [Required()]
        public string Number { get; set; }

        [StringLength(50)]
        [Required()]
        public string Name { get; set; }

        [StringLength(250)]
        public string? Address { get; set; }

        [Required()]
        public int StatusID { get; set; }

        [Required()]
        public bool IsActive { get; set; }

        [Required()]
        public int CreatedBy { get; set; }

        [Required()]
        public DateTime CreatedOn { get; set; }

        [StringLength(50)]
        [Required()]
        public string CreatedIn { get; set; }

        [Required()]
        public int CreatedAt { get; set; }

        [Required()]
        public int TypeWarehouse { get; set; }

        [StringLength(255)]
        public string? EmailResponsability { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
