//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2025-06-24 14:25:27
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace v4posme_library.Models
{
    public partial class TbCompanyParameter {

        public TbCompanyParameter()
        {
            this.ParameterID = 0;
            this.CompanyID = 0;
            this.Display = @"0";
            this.Description = @"0";
            this.Value = @"0";
            this.CustomValue = @"0";
            OnCreated();
        }

        public int ParameterID { get; set; }

        public int CompanyID { get; set; }

        public string Display { get; set; }

        public string Description { get; set; }

        public string Value { get; set; }

        public string CustomValue { get; set; }

        public int CompanyParameterID { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
