//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 13/6/2025 8:44:46 AM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace v4posme_library.Models
{
    public partial class TbWorkflowStageChangeLog {

        public TbWorkflowStageChangeLog()
        {
            this.ComponentID = 0;
            this.WorkflowID = 0;
            this.WorkflowStageID = 0;
            OnCreated();
        }

        public TbWorkflowStageChangeLog(int workflowStageChangeLogID, int? componentItemID, string? description, DateTime? createdOn, int? createdBy) : this()        {
            this.WorkflowStageChangeLogID = workflowStageChangeLogID;
            this.ComponentItemID = componentItemID;
            this.Description = description;
            this.CreatedOn = createdOn;
            this.CreatedBy = createdBy;
        }

        [Key]
        [Required()]
        public int WorkflowStageChangeLogID { get; set; }

        [Required()]
        public int ComponentID { get; set; }

        [Required()]
        public int WorkflowID { get; set; }

        [Required()]
        public int WorkflowStageID { get; set; }

        public int? ComponentItemID { get; set; }

        [StringLength(250)]
        public string? Description { get; set; }

        public DateTime? CreatedOn { get; set; }

        public int? CreatedBy { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
