//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2025-06-24 14:25:27
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace v4posme_library.Models
{
    public partial class TbCustomerCreditLine {

        public TbCustomerCreditLine()
        {
            this.CompanyID = 0;
            this.BranchID = 0;
            this.EntityID = 0;
            this.CreditLineID = 0;
            this.AccountNumber = @"0";
            this.CurrencyID = 0;
            this.TypeAmortization = 0;
            this.LimitCredit = 0.000000000m;
            this.Balance = 0.000000000m;
            this.InterestYear = 0.000000000m;
            this.InterestPay = 0.000000000m;
            this.TotalPay = 0.000000000m;
            this.TotalDefeated = 0.000000000m;
            this.PeriodPay = 0;
            this.StatusID = 0;
            this.IsActive = false;
            OnCreated();
        }

        public int CustomerCreditLineID { get; set; }

        public int CompanyID { get; set; }

        public int BranchID { get; set; }

        public int EntityID { get; set; }

        public int CreditLineID { get; set; }

        public string AccountNumber { get; set; }

        public int CurrencyID { get; set; }

        public int TypeAmortization { get; set; }

        public decimal LimitCredit { get; set; }

        public decimal Balance { get; set; }

        public decimal InterestYear { get; set; }

        public decimal InterestPay { get; set; }

        public decimal TotalPay { get; set; }

        public decimal TotalDefeated { get; set; }

        public DateTime DateOpen { get; set; }

        public int PeriodPay { get; set; }

        public DateTime? DateLastPay { get; set; }

        public int? Term { get; set; }

        public string? Note { get; set; }

        public int StatusID { get; set; }

        public bool IsActive { get; set; }

        public int? DayExcluded { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
