//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2025-10-19 11:13:49
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace v4posme_library.Models
{
    /// <summary>
    /// VIEW
    /// </summary>
    public partial class VwTransaccionMasterConcept232425 {

        public VwTransaccionMasterConcept232425()
        {
            OnCreated();
        }

        public int TransactionMasterID { get; set; }

        public string Descripcion { get; set; }

        public DateTime? Fecha { get; set; }

        public string Documento { get; set; }

        public string Moneda { get; set; }

        public string? Concepto { get; set; }

        public decimal? Valor { get; set; }

        public string? Componente { get; set; }

        public int? ComponentItemID { get; set; }

        public string? Referencia1 { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
