//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2025-06-24 14:25:27
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace v4posme_library.Models
{
    public partial class TbIndicatorHistory {

        public TbIndicatorHistory()
        {
            this.CompanyID = 0;
            this.IndicatorID = 0;
            this.Value = 0.00m;
            OnCreated();
        }

        public int CompanyID { get; set; }

        public int IndicatorID { get; set; }

        public DateTime DateOn { get; set; }

        public decimal Value { get; set; }

        public int IndicatorHistoryID { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
