//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2025-06-24 14:25:27
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace v4posme_library.Models
{
    public partial class TbCatalogItem {

        public TbCatalogItem()
        {
            this.CatalogID = 0;
            this.Ratio = 1.00000000m;
            OnCreated();
        }

        public int CatalogID { get; set; }

        public int CatalogItemID { get; set; }

        public string? Name { get; set; }

        public string? Display { get; set; }

        public int? FlavorID { get; set; }

        public string? Description { get; set; }

        public int? Sequence { get; set; }

        public int? ParentCatalogID { get; set; }

        public int? ParentCatalogItemID { get; set; }

        public decimal Ratio { get; set; }

        public string? Reference1 { get; set; }

        public string? Reference2 { get; set; }

        public string? Reference3 { get; set; }

        public string? Reference4 { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
