//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 4/10/2024 4:53:03 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace v4posme_library.Models
{
    public partial class TbEntityEmail {

        public TbEntityEmail()
        {
            this.CompanyID = 0;
            this.BranchID = 0;
            this.EntityID = 0;
            OnCreated();
        }

        public TbEntityEmail(long entityEmailID, string? email, sbyte? isPrimary) : this()        {
            this.EntityEmailID = entityEmailID;
            this.Email = email;
            this.IsPrimary = isPrimary;
        }

        [Key]
        [Required()]
        public long EntityEmailID { get; set; }

        [Required()]
        public int CompanyID { get; set; }

        [Required()]
        public int BranchID { get; set; }

        [Required()]
        public int EntityID { get; set; }

        [StringLength(250)]
        public string? Email { get; set; }

        public sbyte? IsPrimary { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
