//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2025-10-19 11:13:49
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace v4posme_library.Models
{
    public partial class TbEmployeeCalendarPayDetail {

        public TbEmployeeCalendarPayDetail()
        {
            this.CalendarID = 0;
            this.EmployeeID = 0;
            this.PlusSalary = 0.00m;
            this.PlusCommission = 0.00m;
            this.MinusAdelantos = 0.00m;
            this.EqualNeto = 0.00m;
            this.IsActive = false;
            OnCreated();
        }

        public int CalendarDetailID { get; set; }

        public int CalendarID { get; set; }

        public int EmployeeID { get; set; }

        public decimal PlusSalary { get; set; }

        public decimal PlusCommission { get; set; }

        public decimal? PlusBonus { get; set; }

        public decimal MinusAdelantos { get; set; }

        public decimal? MinusDeductionForLoans { get; set; }

        public decimal? MinusDeductionForLateArrival { get; set; }

        public decimal? MinusInss { get; set; }

        public decimal? InssPatronal { get; set; }

        public decimal? MinusIr { get; set; }

        public decimal? Saving { get; set; }

        public decimal EqualNeto { get; set; }

        public string? Reference1 { get; set; }

        public string? Reference2 { get; set; }

        public string? Reference3 { get; set; }

        public bool IsActive { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
