//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2025-06-24 14:25:27
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace v4posme_library.Models
{
    public partial class PrPurchaseGetReportPurchaseDetailResult {

        public PrPurchaseGetReportPurchaseDetailResult()
        {
            OnCreated();
        }

        public int UserID { get; set; }

        public string? Nickname { get; set; }

        public string TransactionNumber { get; set; }

        public string Tipo { get; set; }

        public DateTime? TransactionOn { get; set; }

        public DateTime? CreatedOn { get; set; }

        public int? DayOfMonth { get; set; }

        public string ProviderNumber { get; set; }

        public string? LegalName { get; set; }

        public string Zone { get; set; }

        public string ItemNumber { get; set; }

        public string ItemName { get; set; }

        public string NameCategory { get; set; }

        public decimal? Quantity { get; set; }

        public decimal? UnitaryCost { get; set; }

        public decimal? Cost { get; set; }

        public int? VarCurrencyReporte { get; set; }

        public int? CurrencyID { get; set; }

        public decimal? ExchangeRate { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
