//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2025-06-24 14:25:27
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace v4posme_library.Models
{
    public partial class PrCollectionGetReportDocumentsCreditResult {

        public PrCollectionGetReportDocumentsCreditResult()
        {
            OnCreated();
        }

        public string? Orden { get; set; }

        public string? Nickname { get; set; }

        public DateTime? CustomerCreatedOn { get; set; }

        public string CustomerNumber { get; set; }

        public string? CustomerName { get; set; }

        public string DocumentNumber { get; set; }

        public string? ComercialName { get; set; }

        public string Identification { get; set; }

        public string? Sexo { get; set; }

        public string? Location { get; set; }

        public string? PhoneNumber { get; set; }

        public string? StatusCivil { get; set; }

        public int Term { get; set; }

        public decimal Interes { get; set; }

        public decimal AmountDocument { get; set; }

        public DateTime DateDocument { get; set; }

        public DateTime? DateLastShareDocument { get; set; }

        public decimal? DeudaTotal { get; set; }

        public decimal? MontoPagado { get; set; }

        public decimal? Avance { get; set; }

        public decimal Saldo { get; set; }

        public int? Orden1 { get; set; }

        public int CurrencyID { get; set; }

        public string StatusCustomer { get; set; }

        public string? StatusName { get; set; }

        public string? PeriodPay { get; set; }

        public int CustomerCreditDocumentID { get; set; }

        public decimal? _2025_06_24 { get; set; }

        public decimal? _2025_06_23 { get; set; }

        public decimal? _2025_06_22 { get; set; }

        public decimal? _2025_06_21 { get; set; }

        public decimal? _2025_06_20 { get; set; }

        public decimal? _2025_06_19 { get; set; }

        public decimal? _2025_06_18 { get; set; }

        public decimal? _2025_06_17 { get; set; }

        public decimal? _2025_06_16 { get; set; }

        public decimal? _2025_06_15 { get; set; }

        public decimal? _2025_06_14 { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
