//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 22/12/2024 9:47:43 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace v4posme_library.Models
{
    public partial class TbCompanyComponentFlavor {

        public TbCompanyComponentFlavor()
        {
            this.CompanyID = 0;
            this.ComponentID = 0;
            this.ComponentItemID = 0;
            this.FlavorID = @"0";
            OnCreated();
        }

        public TbCompanyComponentFlavor(int companyComponentFlavorID) : this()        {
            this.CompanyComponentFlavorID = companyComponentFlavorID;
        }

        [Key]
        [Required()]
        public int CompanyComponentFlavorID { get; set; }

        [Required()]
        public int CompanyID { get; set; }

        [Required()]
        public int ComponentID { get; set; }

        [Required()]
        public int ComponentItemID { get; set; }

        [StringLength(250)]
        [Required()]
        public string FlavorID { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
