//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2025-10-19 11:13:49
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace v4posme_library.Models
{
    public partial class TbLogMesseger {

        public TbLogMesseger()
        {
            this.IpAddress = @"0";
            OnCreated();
        }

        public int Id { get; set; }

        public int Errno { get; set; }

        public string Errtype { get; set; }

        public string Errstr { get; set; }

        public string Errfile { get; set; }

        public int Errline { get; set; }

        public string UserAgent { get; set; }

        public string IpAddress { get; set; }

        public DateTime Time { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
