//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2025-10-19 11:13:49
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace v4posme_library.Models
{
    public partial class TbComponentAuditDetail {

        public TbComponentAuditDetail()
        {
            this.CompanyID = 0;
            this.BranchID = 0;
            this.ComponentAuditID = 0;
            OnCreated();
        }

        public int ComponentAuditDetailID { get; set; }

        public int CompanyID { get; set; }

        public int BranchID { get; set; }

        public int ComponentAuditID { get; set; }

        public int? FieldID { get; set; }

        public string? OldValue { get; set; }

        public string? NewValue { get; set; }

        public string? Note { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
