//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 22/12/2024 9:47:43 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace v4posme_library.Models
{
    public partial class TbTransactionMasterConcept {

        public TbTransactionMasterConcept()
        {
            this.CompanyID = 0;
            this.TransactionID = 0;
            this.TransactionMasterID = 0;
            this.Value = 0.0000m;
            OnCreated();
        }

        public TbTransactionMasterConcept(int transactionMasterConceptID, int? componentID, int? componentItemID, int? conceptID, int? currencyID, decimal? exchangeRate) : this()        {
            this.TransactionMasterConceptID = transactionMasterConceptID;
            this.ComponentID = componentID;
            this.ComponentItemID = componentItemID;
            this.ConceptID = conceptID;
            this.CurrencyID = currencyID;
            this.ExchangeRate = exchangeRate;
        }

        [Key]
        [Required()]
        public int TransactionMasterConceptID { get; set; }

        [Required()]
        public int CompanyID { get; set; }

        [Required()]
        public int TransactionID { get; set; }

        [Required()]
        public int TransactionMasterID { get; set; }

        public int? ComponentID { get; set; }

        public int? ComponentItemID { get; set; }

        public int? ConceptID { get; set; }

        public decimal? Value { get; set; }

        public int? CurrencyID { get; set; }

        public decimal? ExchangeRate { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
