//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2025-06-24 14:25:27
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace v4posme_library.Models
{
    public partial class TbTransactionMasterPurchase {

        public TbTransactionMasterPurchase()
        {
            this.CompanyID = 0;
            this.TransactionID = 0;
            this.TransactionMasterID = 0;
            this.PurchaseTypeID = 0;
            this.TransportTypeID = 0;
            OnCreated();
        }

        public int CompanyID { get; set; }

        public int TransactionID { get; set; }

        public int TransactionMasterID { get; set; }

        public int PurchaseTypeID { get; set; }

        public int TransportTypeID { get; set; }

        public int TransactionMasterPurchaseID { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
