//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2025-06-24 14:25:27
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace v4posme_library.Models
{
    public partial class TbCustomerCreditClasification {

        public TbCustomerCreditClasification()
        {
            this.EntityID = 0;
            this.NumberShareLate = 0;
            this.AmountCapitalLate = 0.00000000m;
            this.AmountInterestLate = 0.00000000m;
            this.MaxDayMora = 0;
            this.NumberCreditAbiertos = 0;
            this.NumberCreditSaneados = 0;
            this.NumberCreditCancelados = 0;
            this.AmountCapitalAbierto = 0.00000000m;
            this.AmountCapitalSaneado = 0.00000000m;
            this.AmountCapitalCancelado = 0.00000000m;
            this.Summary = 0;
            OnCreated();
        }

        public int ClasificationID { get; set; }

        public int EntityID { get; set; }

        public DateTime DateHistory { get; set; }

        public int NumberShareLate { get; set; }

        public decimal AmountCapitalLate { get; set; }

        public decimal AmountInterestLate { get; set; }

        public int MaxDayMora { get; set; }

        public int NumberCreditAbiertos { get; set; }

        public int NumberCreditSaneados { get; set; }

        public int NumberCreditCancelados { get; set; }

        public decimal AmountCapitalAbierto { get; set; }

        public decimal AmountCapitalSaneado { get; set; }

        public decimal AmountCapitalCancelado { get; set; }

        public int Summary { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
