//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 22/12/2024 9:47:43 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace v4posme_library.Models
{
    public partial class TbWorkflow {

        public TbWorkflow()
        {
            this.ComponentID = 0;
            this.IsActive = false;
            OnCreated();
        }

        public TbWorkflow(int workflowID, string? name, string? description) : this()        {
            this.WorkflowID = workflowID;
            this.Name = name;
            this.Description = description;
        }

        [Key]
        [Required()]
        public int WorkflowID { get; set; }

        [Required()]
        public int ComponentID { get; set; }

        [StringLength(250)]
        public string? Name { get; set; }

        [StringLength(250)]
        public string? Description { get; set; }

        [Required()]
        public bool IsActive { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
