//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2025-10-19 11:13:49
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace v4posme_library.Models
{
    public partial class TbCompanyComponentConcept {

        public TbCompanyComponentConcept()
        {
            this.CompanyID = 0;
            this.ComponentID = 0;
            this.ComponentItemID = 0;
            this.Name = @"0";
            OnCreated();
        }

        public int CompanyComponentConceptID { get; set; }

        public int CompanyID { get; set; }

        public int ComponentID { get; set; }

        public int ComponentItemID { get; set; }

        public string Name { get; set; }

        public decimal? ValueIn { get; set; }

        public decimal? ValueOut { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
