//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 26/9/2024 4:44:37 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace v4posme_library.Models
{
    public partial class TbRemember {

        public TbRemember()
        {
            this.CompanyID = 0;
            this.Title = @"0";
            this.Description = @"0";
            this.Period = 0;
            this.Day = 0;
            this.StatusID = 0;
            this.IsTemporal = false;
            this.CreatedBy = 0;
            this.CreatedIn = @"0";
            this.CreatedAt = 0;
            this.IsActive = false;
            this.TagID = 0;
            this.LeerFile = 0;
            OnCreated();
        }

        public TbRemember(int rememberID, DateTime? lastNotificationOn, DateTime createdOn) : this()        {
            this.RememberID = rememberID;
            this.LastNotificationOn = lastNotificationOn;
            this.CreatedOn = createdOn;
        }

        [Key]
        [Required()]
        public int RememberID { get; set; }

        [Required()]
        public int CompanyID { get; set; }

        [StringLength(250)]
        [Required()]
        public string Title { get; set; }

        [StringLength(500)]
        [Required()]
        public string Description { get; set; }

        [Required()]
        public int Period { get; set; }

        [Required()]
        public int Day { get; set; }

        [Required()]
        public int StatusID { get; set; }

        public DateTime? LastNotificationOn { get; set; }

        [Required()]
        public bool IsTemporal { get; set; }

        [Required()]
        public int CreatedBy { get; set; }

        [Required()]
        public DateTime CreatedOn { get; set; }

        [StringLength(50)]
        [Required()]
        public string CreatedIn { get; set; }

        [Required()]
        public int CreatedAt { get; set; }

        [Required()]
        public bool IsActive { get; set; }

        public int? TagID { get; set; }

        public int? LeerFile { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
