//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 3/1/2025 3:48:59 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace v4posme_library.Models
{
    public partial class TbBiblia {

        public TbBiblia()
        {
            this.Orden = 0;
            this.Dia = 0;
            this.Capitulo = 0;
            this.Libro = @"N";
            OnCreated();
        }

        public TbBiblia(int versiculoID, string? versiculo) : this()        {
            this.VersiculoID = versiculoID;
            this.Versiculo = versiculo;
        }

        [Key]
        [Required()]
        public int VersiculoID { get; set; }

        [Required()]
        public int Orden { get; set; }

        [Required()]
        public int Dia { get; set; }

        [Required()]
        public int Capitulo { get; set; }

        [StringLength(255)]
        [Required()]
        public string Libro { get; set; }

        [StringLength(1500)]
        public string? Versiculo { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
