//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2025-10-19 11:13:49
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace v4posme_library.Models
{
    public partial class TbAccountingBalance {

        public TbAccountingBalance()
        {
            this.ComponentCycleID = 0;
            this.ComponentPeriodID = 0;
            this.CompanyID = 0;
            this.ComponentID = 0;
            this.AccountID = 0;
            this.BranchID = 0;
            this.Debit = 0.00000000m;
            this.Credit = 0.00000000m;
            this.IsActive = false;
            OnCreated();
        }

        public int AccountBalanceID { get; set; }

        public int ComponentCycleID { get; set; }

        public int ComponentPeriodID { get; set; }

        public int CompanyID { get; set; }

        public int ComponentID { get; set; }

        public int AccountID { get; set; }

        public int BranchID { get; set; }

        public decimal? Balance { get; set; }

        public decimal Debit { get; set; }

        public decimal Credit { get; set; }

        public int? ClassID { get; set; }

        public bool IsActive { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
