//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2025-10-19 11:13:49
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace v4posme_library.Models
{
    public partial class TbWorkflowStage {

        public TbWorkflowStage()
        {
            this.ComponentID = 0;
            this.WorkflowID = 0;
            this.IsActive = false;
            this.IsInit = false;
            OnCreated();
        }

        public int WorkflowStageID { get; set; }

        public int ComponentID { get; set; }

        public int WorkflowID { get; set; }

        public string? Name { get; set; }

        public string? Description { get; set; }

        public string? Display { get; set; }

        public int? FlavorID { get; set; }

        public bool? EditableParcial { get; set; }

        public bool? EditableTotal { get; set; }

        public bool? Eliminable { get; set; }

        /// <summary>
        /// Este campo es util para saber si el documento debe de aumentar o disminuir inventario o para saver si el documento debe de ser contabilizado
        /// </summary>
        public bool? Aplicable { get; set; }

        public bool? Vinculable { get; set; }

        public bool IsActive { get; set; }

        public bool IsInit { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
