//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 4/10/2024 4:53:03 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace v4posme_library.Models
{
    /// <summary>
    /// VIEW
    /// </summary>
    public partial class VwGerenciaBalance {

        public VwGerenciaBalance()
        {
            OnCreated();
        }

        [StringLength(250)]
        public string? CentroCosto { get; set; }

        [StringLength(503)]
        [Required()]
        public string Cuenta { get; set; }

        [StringLength(4)]
        public string? Ano { get; set; }

        [StringLength(7)]
        public string? Mes { get; set; }

        [StringLength(2)]
        public string? MesOnly { get; set; }

        public decimal? CsaldoInicial { get; set; }

        public decimal? CsaldoFinal { get; set; }

        [Required()]
        public decimal CsaldoMensual { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
