//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 26/9/2024 4:44:37 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace v4posme_library.Models
{
    public partial class TbCenterCost {

        public TbCenterCost()
        {
            this.CompanyID = 0;
            this.AccountLevelID = 0;
            this.Number = @"0";
            OnCreated();
        }

        public TbCenterCost(int classID, int? parentAccountID, int? parentClassID, string? description, bool? isActive, int? createdBy, DateTime? createdOn, int? createdAt, string? createdIn) : this()        {
            this.ClassID = classID;
            this.ParentAccountID = parentAccountID;
            this.ParentClassID = parentClassID;
            this.Description = description;
            this.IsActive = isActive;
            this.CreatedBy = createdBy;
            this.CreatedOn = createdOn;
            this.CreatedAt = createdAt;
            this.CreatedIn = createdIn;
        }

        [Key]
        [Required()]
        public int ClassID { get; set; }

        [Required()]
        public int CompanyID { get; set; }

        [Required()]
        public int AccountLevelID { get; set; }

        public int? ParentAccountID { get; set; }

        public int? ParentClassID { get; set; }

        [StringLength(250)]
        [Required()]
        public string Number { get; set; }

        [StringLength(250)]
        public string? Description { get; set; }

        public bool? IsActive { get; set; }

        public int? CreatedBy { get; set; }

        public DateTime? CreatedOn { get; set; }

        public int? CreatedAt { get; set; }

        [StringLength(250)]
        public string? CreatedIn { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
