//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2025-06-24 14:25:27
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace v4posme_library.Models
{
    public partial class TbExchangeRate {

        public TbExchangeRate()
        {
            this.CurrencyID = 0;
            this.CompanyID = 0;
            this.TargetCurrencyID = 0;
            this.Value = 0.0000m;
            OnCreated();
        }

        public int CurrencyID { get; set; }

        public int CompanyID { get; set; }

        public DateTime Date { get; set; }

        public int TargetCurrencyID { get; set; }

        public double? Ratio { get; set; }

        public decimal Value { get; set; }

        public int ExchangeRateID { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
