//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 26/9/2024 4:44:37 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace v4posme_library.Models
{
    public partial class TbTransactionMasterInfo {

        public TbTransactionMasterInfo()
        {
            this.CompanyID = 0;
            this.TransactionID = 0;
            this.TransactionMasterID = 0;
            this.MesaID = 0;
            this.ChangeAmount = 0.000000000m;
            this.ReceiptAmountDol = 0.00000m;
            this.ReceiptAmountBank = 0.00m;
            this.ReceiptAmountBankID = 0;
            this.ReceiptAmountBankDol = 0m;
            this.ReceiptAmountBankDolID = 0;
            this.ReceiptAmountCard = 0m;
            this.ReceiptAmountCardBankID = 0;
            this.ReceiptAmountCardDol = 0m;
            this.ReceiptAmountCardBankDolID = 0;
            OnCreated();
        }

        public TbTransactionMasterInfo(int transactionMasterInfoID, int? zoneID, int? routeID, string? referenceClientName, string? referenceClientIdentifier, decimal? receiptAmountPoint, decimal? receiptAmount, string? reference1, string? reference2, string? receiptAmountBankReference, string? receiptAmountBankDolReference, string? receiptAmountCardBankReference, string? receiptAmountCardBankDolReference) : this()        {
            this.TransactionMasterInfoID = transactionMasterInfoID;
            this.ZoneID = zoneID;
            this.RouteID = routeID;
            this.ReferenceClientName = referenceClientName;
            this.ReferenceClientIdentifier = referenceClientIdentifier;
            this.ReceiptAmountPoint = receiptAmountPoint;
            this.ReceiptAmount = receiptAmount;
            this.Reference1 = reference1;
            this.Reference2 = reference2;
            this.ReceiptAmountBankReference = receiptAmountBankReference;
            this.ReceiptAmountBankDolReference = receiptAmountBankDolReference;
            this.ReceiptAmountCardBankReference = receiptAmountCardBankReference;
            this.ReceiptAmountCardBankDolReference = receiptAmountCardBankDolReference;
        }

        [Key]
        [Required()]
        public int TransactionMasterInfoID { get; set; }

        [Required()]
        public int CompanyID { get; set; }

        [Required()]
        public int TransactionID { get; set; }

        [Required()]
        public int TransactionMasterID { get; set; }

        public int? ZoneID { get; set; }

        public int? RouteID { get; set; }

        [Required()]
        public int MesaID { get; set; }

        [StringLength(250)]
        public string? ReferenceClientName { get; set; }

        [StringLength(50)]
        public string? ReferenceClientIdentifier { get; set; }

        [Required()]
        public decimal ChangeAmount { get; set; }

        public decimal? ReceiptAmountPoint { get; set; }

        public decimal? ReceiptAmount { get; set; }

        [Required()]
        public decimal ReceiptAmountDol { get; set; }

        [StringLength(150)]
        public string? Reference1 { get; set; }

        [StringLength(150)]
        public string? Reference2 { get; set; }

        [Required()]
        public decimal ReceiptAmountBank { get; set; }

        public int? ReceiptAmountBankID { get; set; }

        [StringLength(255)]
        public string? ReceiptAmountBankReference { get; set; }

        [Required()]
        public decimal ReceiptAmountBankDol { get; set; }

        public int? ReceiptAmountBankDolID { get; set; }

        [StringLength(255)]
        public string? ReceiptAmountBankDolReference { get; set; }

        [Required()]
        public decimal ReceiptAmountCard { get; set; }

        public int? ReceiptAmountCardBankID { get; set; }

        [StringLength(255)]
        public string? ReceiptAmountCardBankReference { get; set; }

        [Required()]
        public decimal ReceiptAmountCardDol { get; set; }

        public int? ReceiptAmountCardBankDolID { get; set; }

        [StringLength(255)]
        public string? ReceiptAmountCardBankDolReference { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
