//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2025-06-24 14:25:27
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace v4posme_library.Models
{
    public partial class TbTransactionProfileDetail {

        public TbTransactionProfileDetail()
        {
            this.CompanyID = 0;
            this.TransactionID = 0;
            this.TransactionCausalID = 0;
            this.ConceptID = 0;
            this.AccountID = @"0";
            this.Sign = @"0";
            OnCreated();
        }

        public int CompanyID { get; set; }

        public int TransactionID { get; set; }

        public int TransactionCausalID { get; set; }

        public int ProfileDetailID { get; set; }

        public int ConceptID { get; set; }

        public string AccountID { get; set; }

        public string? ClassID { get; set; }

        public string Sign { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
