//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2025-06-24 14:25:27
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace v4posme_library.Models
{
    /// <summary>
    /// Tabla de Notificaciones
    /// </summary>
    public partial class TbNotification {

        public TbNotification()
        {
            this.QuantityOcupation = 0;
            this.QuantityDisponible = 0;
            OnCreated();
        }

        public int NotificationID { get; set; }

        public int? ErrorID { get; set; }

        public string? From { get; set; }

        public string? To { get; set; }

        public string? Subject { get; set; }

        public string? Message { get; set; }

        public string? Summary { get; set; }

        public string? Title { get; set; }

        public int? TagID { get; set; }

        public DateTime? CreatedOn { get; set; }

        public bool? IsActive { get; set; }

        public string? PhoneFrom { get; set; }

        public string? PhoneTo { get; set; }

        public string? ProgramDate { get; set; }

        public string? ProgramHour { get; set; }

        public DateTime? SendOn { get; set; }

        public DateTime? SendEmailOn { get; set; }

        public DateTime? SendWhatsappOn { get; set; }

        public bool? AddedCalendarGoogle { get; set; }

        public int? QuantityOcupation { get; set; }

        public int? QuantityDisponible { get; set; }

        public string? GoogleCalendarEventID { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
