//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2025-06-24 14:25:27
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace v4posme_library.Models
{
    public partial class PrCxcGetReportCustomerPayByInvoiceResult {

        public PrCxcGetReportCustomerPayByInvoiceResult()
        {
            OnCreated();
        }

        public string CustomerNumber { get; set; }

        public string? CustomerName { get; set; }

        public string? PhoneNumber { get; set; }

        public string? Location { get; set; }

        public string Identification { get; set; }

        public DateTime FechaDesembolso { get; set; }

        public decimal MontoDesembolso { get; set; }

        public decimal InteresDesembolso { get; set; }

        public int Plazo { get; set; }

        public string? StatusDesembolso { get; set; }

        public string? FrecuenciaDesembolso { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
