//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2025-10-19 11:13:49
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace v4posme_library.Models
{
    public partial class TbItem {

        public TbItem()
        {
            this.CompanyID = 0;
            this.BranchID = 0;
            this.InventoryCategoryID = 0;
            this.ItemNumber = @"0";
            this.Name = @"0";
            this.Quantity = 0.0000m;
            this.QuantityMax = 0.0000m;
            this.QuantityMin = 0.0000m;
            this.Cost = 0.0000m;
            this.IsInvoiceQuantityZero = 0;
            this.IsServices = 0;
            this.CurrencyID = 1;
            this.IsInvoice = 1;
            this.RealStateWallInCloset = 0;
            this.RealStatePiscinaPrivate = 0;
            this.RealStateClubPiscina = 0;
            this.RealStateAceptanMascota = 0;
            this.RealStateContractCorrentaje = 0;
            this.RealStatePlanReference = 0;
            this.RealStateRoomServices = 0;
            this.RealStateRoomBatchServices = 0;
            this.RealStateRooBatchVisit = 0;
            this.RealStateGerenciaExclusive = 0;
            OnCreated();
        }

        public int ItemID { get; set; }

        public int CompanyID { get; set; }

        public int BranchID { get; set; }

        public int InventoryCategoryID { get; set; }

        public int? FamilyID { get; set; }

        public string ItemNumber { get; set; }

        public string? BarCode { get; set; }

        public string Name { get; set; }

        public string? Description { get; set; }

        public string? UnitMeasureID { get; set; }

        public int? DisplayID { get; set; }

        public int? Capacity { get; set; }

        public int? DisplayUnitMeasureID { get; set; }

        public int? DefaultWarehouseID { get; set; }

        public decimal Quantity { get; set; }

        public decimal QuantityMax { get; set; }

        public decimal QuantityMin { get; set; }

        public decimal Cost { get; set; }

        public string? Reference1 { get; set; }

        public string? Reference2 { get; set; }

        public string? Reference3 { get; set; }

        public int? StatusID { get; set; }

        public bool? IsPerishable { get; set; }

        public decimal? FactorBox { get; set; }

        public decimal? FactorProgram { get; set; }

        public string? CreatedIn { get; set; }

        public int? CreatedAt { get; set; }

        public int? CreatedBy { get; set; }

        public DateTime? CreatedOn { get; set; }

        public bool? IsActive { get; set; }

        public sbyte? IsInvoiceQuantityZero { get; set; }

        public sbyte? IsServices { get; set; }

        public int CurrencyID { get; set; }

        public int IsInvoice { get; set; }

        public sbyte? RealStateWallInCloset { get; set; }

        public sbyte? RealStatePiscinaPrivate { get; set; }

        public sbyte? RealStateClubPiscina { get; set; }

        public sbyte? RealStateAceptanMascota { get; set; }

        public sbyte? RealStateContractCorrentaje { get; set; }

        public sbyte? RealStatePlanReference { get; set; }

        public string? RealStateLinkYoutube { get; set; }

        public string? RealStateLinkPaginaWeb { get; set; }

        public string? RealStateLinkPhontos { get; set; }

        public string? RealStateLinkGoogleMaps { get; set; }

        public string? RealStateLinkOther { get; set; }

        public string? RealStateStyleKitchen { get; set; }

        public sbyte? RealStateRoomServices { get; set; }

        public sbyte? RealStateRoomBatchServices { get; set; }

        public string? RealStateReferenceUbicacion { get; set; }

        public string? RealStateReferenceZone { get; set; }

        public string? RealStateReferenceCondominio { get; set; }

        public int? RealStateEmployerAgentID { get; set; }

        public int? RealStateCountryID { get; set; }

        public int? RealStateStateID { get; set; }

        public int? RealStateCityID { get; set; }

        public DateTime? ModifiedOn { get; set; }

        public sbyte? RealStateRooBatchVisit { get; set; }

        public int? RealStateGerenciaExclusive { get; set; }

        public string? RealStatePhone { get; set; }

        public string? RealStateEmail { get; set; }

        public DateTime? DateLastUse { get; set; }

        public decimal? QuantityInvoice { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
