//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 24/10/2024 8:54:25 AM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace v4posme_library.Models
{
    public partial class TbLog {

        public TbLog()
        {
            this.CompanyID = 0;
            this.BranchID = 0;
            this.LoginID = 0;
            this.Token = @"0";
            this.ProcedureName = @"0";
            this.Code = 0;
            this.Description = @"0";
            OnCreated();
        }

        public TbLog(int logID, DateTime createdOn) : this()        {
            this.LogID = logID;
            this.CreatedOn = createdOn;
        }

        [Key]
        [Required()]
        public int LogID { get; set; }

        [Required()]
        public int CompanyID { get; set; }

        [Required()]
        public int BranchID { get; set; }

        [Required()]
        public int LoginID { get; set; }

        [StringLength(255)]
        [Required()]
        public string Token { get; set; }

        [StringLength(150)]
        [Required()]
        public string ProcedureName { get; set; }

        [Required()]
        public int Code { get; set; }

        [StringLength(350)]
        [Required()]
        public string Description { get; set; }

        [Required()]
        public DateTime CreatedOn { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
