//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2025-10-19 11:13:49
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace v4posme_library.Models
{
    public partial class TbReporting {

        public TbReporting()
        {
            this.FlavorID = 0;
            OnCreated();
        }

        public int ReportID { get; set; }

        public string? Keyi { get; set; }

        public string? Namei { get; set; }

        public string? Display { get; set; }

        public string? UrlReport { get; set; }

        public string? UrlReportProcess { get; set; }

        public int? Ranking { get; set; }

        public int? IsMobile { get; set; }

        public string? Queryi { get; set; }

        public int? NeedAutenticated { get; set; }

        public int? IsActive { get; set; }

        public int? FlavorID { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
