//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 22/12/2024 9:47:43 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace v4posme_library.Models
{
    public partial class TbTransactionProfileDetail {

        public TbTransactionProfileDetail()
        {
            this.CompanyID = 0;
            this.TransactionID = 0;
            this.TransactionCausalID = 0;
            this.ConceptID = 0;
            this.AccountID = @"0";
            this.Sign = @"0";
            OnCreated();
        }

        public TbTransactionProfileDetail(int profileDetailID, string? classID) : this()        {
            this.ProfileDetailID = profileDetailID;
            this.ClassID = classID;
        }

        [Key]
        [Required()]
        public int ProfileDetailID { get; set; }

        [Required()]
        public int CompanyID { get; set; }

        [Required()]
        public int TransactionID { get; set; }

        [Required()]
        public int TransactionCausalID { get; set; }

        [Required()]
        public int ConceptID { get; set; }

        [StringLength(50)]
        [Required()]
        public string AccountID { get; set; }

        [StringLength(50)]
        public string? ClassID { get; set; }

        [StringLength(1)]
        [Required()]
        public string Sign { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
