//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 13/6/2025 8:44:45 AM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace v4posme_library.Models
{
    public partial class TbCompanyDefaultDataview {

        public TbCompanyDefaultDataview()
        {
            this.CompanyID = 0;
            this.ComponentID = 0;
            this.DataViewID = 0;
            this.CallerID = 0;
            OnCreated();
        }

        public TbCompanyDefaultDataview(int companyDefaultDataviewID, int? targetComponentID) : this()        {
            this.CompanyDefaultDataviewID = companyDefaultDataviewID;
            this.TargetComponentID = targetComponentID;
        }

        [Key]
        [Required()]
        public int CompanyDefaultDataviewID { get; set; }

        [Required()]
        public int CompanyID { get; set; }

        [Required()]
        public int ComponentID { get; set; }

        [Required()]
        public int DataViewID { get; set; }

        [Required()]
        public int CallerID { get; set; }

        public int? TargetComponentID { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
