//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 3/1/2025 3:48:59 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace v4posme_library.Models
{
    public partial class TbCompanyCurrency {

        public TbCompanyCurrency()
        {
            this.CurrencyID = 0;
            this.CompanyID = 0;
            OnCreated();
        }

        public TbCompanyCurrency(int companyCurrencyID, string? simb) : this()        {
            this.CompanyCurrencyID = companyCurrencyID;
            this.Simb = simb;
        }

        [Key]
        [Required()]
        public int CompanyCurrencyID { get; set; }

        [Required()]
        public int CurrencyID { get; set; }

        [Required()]
        public int CompanyID { get; set; }

        [StringLength(5)]
        public string? Simb { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
