//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 26/9/2024 4:44:37 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace v4posme_library.Models
{
    public partial class TbIndicatorHistory {

        public TbIndicatorHistory()
        {
            this.CompanyID = 0;
            this.IndicatorID = 0;
            this.Value = 0.00m;
            OnCreated();
        }

        public TbIndicatorHistory(int indicatorHistoryID, DateTime dateOn) : this()        {
            this.IndicatorHistoryID = indicatorHistoryID;
            this.DateOn = dateOn;
        }

        [Key]
        [Required()]
        public int IndicatorHistoryID { get; set; }

        [Required()]
        public int CompanyID { get; set; }

        [Required()]
        public int IndicatorID { get; set; }

        [Required()]
        public DateTime DateOn { get; set; }

        [Required()]
        public decimal Value { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
