//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2025-10-19 11:13:49
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace v4posme_library.Models
{
    public partial class TbCompanyComponentItemDataview {

        public TbCompanyComponentItemDataview()
        {
            this.CompanyID = 0;
            this.ComponentID = 0;
            this.DataViewID = 0;
            this.CallerID = 0;
            this.FlavorID = 0;
            OnCreated();
        }

        public int CompanyComponentItemDataviewID { get; set; }

        public int CompanyID { get; set; }

        public int ComponentID { get; set; }

        public int DataViewID { get; set; }

        public int CallerID { get; set; }

        public int FlavorID { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
