//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 24/10/2024 8:54:25 AM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace v4posme_library.Models
{
    public partial class TbTransactionMasterReference {

        public TbTransactionMasterReference()
        {
            OnCreated();
        }

        public TbTransactionMasterReference(int transactionMasterReferenceID, int? transactionMasterID, string? transactionReferenceNumber, DateTime? createdOn, bool? isActive, string? reference1, string? reference2, string? reference3, string? refernece4, string? refernece5, string? reference6, string? reference7, string? reference8, string? referecne9, string? reference10, string? reference11, string? reference12, string? reference13, string? reference14, string? reference15, string? reference16, string? reference17, string? reference18, string? reference19, string? reference20, string? reference21, string? reference22) : this()        {
            this.TransactionMasterReferenceID = transactionMasterReferenceID;
            this.TransactionMasterID = transactionMasterID;
            this.TransactionReferenceNumber = transactionReferenceNumber;
            this.CreatedOn = createdOn;
            this.IsActive = isActive;
            this.Reference1 = reference1;
            this.Reference2 = reference2;
            this.Reference3 = reference3;
            this.Refernece4 = refernece4;
            this.Refernece5 = refernece5;
            this.Reference6 = reference6;
            this.Reference7 = reference7;
            this.Reference8 = reference8;
            this.Referecne9 = referecne9;
            this.Reference10 = reference10;
            this.Reference11 = reference11;
            this.Reference12 = reference12;
            this.Reference13 = reference13;
            this.Reference14 = reference14;
            this.Reference15 = reference15;
            this.Reference16 = reference16;
            this.Reference17 = reference17;
            this.Reference18 = reference18;
            this.Reference19 = reference19;
            this.Reference20 = reference20;
            this.Reference21 = reference21;
            this.Reference22 = reference22;
        }

        [Key]
        [Required()]
        public int TransactionMasterReferenceID { get; set; }

        public int? TransactionMasterID { get; set; }

        [StringLength(255)]
        public string? TransactionReferenceNumber { get; set; }

        public DateTime? CreatedOn { get; set; }

        public bool? IsActive { get; set; }

        [StringLength(255)]
        public string? Reference1 { get; set; }

        [StringLength(255)]
        public string? Reference2 { get; set; }

        [StringLength(255)]
        public string? Reference3 { get; set; }

        [StringLength(255)]
        public string? Refernece4 { get; set; }

        [StringLength(255)]
        public string? Refernece5 { get; set; }

        [StringLength(255)]
        public string? Reference6 { get; set; }

        [StringLength(255)]
        public string? Reference7 { get; set; }

        [StringLength(255)]
        public string? Reference8 { get; set; }

        [StringLength(255)]
        public string? Referecne9 { get; set; }

        [StringLength(255)]
        public string? Reference10 { get; set; }

        [StringLength(255)]
        public string? Reference11 { get; set; }

        [StringLength(255)]
        public string? Reference12 { get; set; }

        [StringLength(255)]
        public string? Reference13 { get; set; }

        [StringLength(255)]
        public string? Reference14 { get; set; }

        [StringLength(255)]
        public string? Reference15 { get; set; }

        [StringLength(255)]
        public string? Reference16 { get; set; }

        [StringLength(255)]
        public string? Reference17 { get; set; }

        [StringLength(255)]
        public string? Reference18 { get; set; }

        [StringLength(255)]
        public string? Reference19 { get; set; }

        [StringLength(255)]
        public string? Reference20 { get; set; }

        [StringLength(255)]
        public string? Reference21 { get; set; }

        [StringLength(255)]
        public string? Reference22 { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
