//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2025-10-19 11:13:49
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace v4posme_library.Models
{
    public partial class PrCxcGetReportDocumentContractResult {

        public PrCxcGetReportDocumentContractResult()
        {
            OnCreated();
        }

        public string? LegalName { get; set; }

        public string Identification { get; set; }

        public string? Address { get; set; }

        public DateTime? FechInicial { get; set; }

        public DateTime FechActual { get; set; }

        public string CurrencyName { get; set; }

        public string? Sexo { get; set; }

        public int Term { get; set; }

        public string? Period { get; set; }

        public DateTime? CreatedOn { get; set; }

        public string? NombreProveedor { get; set; }

        public string? CedulaProveedor { get; set; }

        public string? DireccionProveedor { get; set; }

        public string? EstadoCivil { get; set; }

        public string? Profesion { get; set; }

        public string? Domicilio { get; set; }

        public string? TypeFirmaCustomer { get; set; }

        public string TypeFirmaProvider { get; set; }

        public decimal? TipoCambio { get; set; }

        public decimal? Cuota { get; set; }

        public decimal? CuotaDolares { get; set; }

        public decimal? MontoCuota { get; set; }

        public decimal? AmountTotal { get; set; }

        public decimal? ReceiptAmount { get; set; }

        public DateTime? FechFinal { get; set; }

        public int? DuracionDelCredito { get; set; }

        public string? NameLayEmployee { get; set; }

        public string? NameLayEmployeeEstadoCivil { get; set; }

        public string? NameLayEmployeeQuinquenio { get; set; }

        public string DocumentNumber { get; set; }

        public string? Concepto { get; set; }

        public string? PhoneNumber { get; set; }

        public string? LugarTrabajo { get; set; }

        public DateTime? BirthDate { get; set; }

        public decimal? CantidadProductos { get; set; }

        public string? PhoneNumberTransactionMaster { get; set; }

        public string? ReferenceClientIdentifier { get; set; }

        public string? ReferenceClientName { get; set; }

        public string? Zona { get; set; }

        public string LayWritePublicNumber { get; set; }

        public string LayPasoAnteMi { get; set; }

        public string LayPrimerLineaProtocolo { get; set; }

        public string ProductNameLog { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
