//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2025-10-19 11:13:49
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace v4posme_library.Models
{
    /// <summary>
    /// tabla para almacenar los tag de notificaciones
    /// </summary>
    public partial class TbTag {

        public TbTag()
        {
            OnCreated();
        }

        public int TagID { get; set; }

        public string? Name { get; set; }

        public string? Description { get; set; }

        public bool? SendEmail { get; set; }

        public bool? SendNotificationApp { get; set; }

        public bool? SendSMS { get; set; }

        public bool? IsActive { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
