//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace v4posme_window_form.Models.Tablas
{

    [Persistent(@"tb_caller")]
    public partial class Caller : XPLiteObject
    {
        int fCallerID;
        [Key(true)]
        [Persistent(@"callerID")]
        public int CallerID
        {
            get { return fCallerID; }
            set { SetPropertyValue<int>(nameof(CallerID), ref fCallerID, value); }
        }
        bool fIsActive;
        [Persistent(@"isActive")]
        public bool IsActive
        {
            get { return fIsActive; }
            set { SetPropertyValue<bool>(nameof(IsActive), ref fIsActive, value); }
        }
        string fName;
        [Size(250)]
        [Persistent(@"name")]
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        string fDescription;
        [Size(250)]
        [Persistent(@"description")]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>(nameof(Description), ref fDescription, value); }
        }
    }

}
