//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace v4posme_window_form.Models.Tablas
{

    [Persistent(@"tb_component_autorization_detail")]
    public partial class ComponentAutorizationDetail : XPLiteObject
    {
        int fCompanyID;
        [Indexed(Name = @"IDX_COMPONENT_AUTORIZATSION_DETAIL_001")]
        [Persistent(@"companyID")]
        [ColumnDefaultValue(0)]
        public int CompanyID
        {
            get { return fCompanyID; }
            set { SetPropertyValue<int>(nameof(CompanyID), ref fCompanyID, value); }
        }
        int fComponentAutorizationID;
        [Indexed(Name = @"IDX_COMPONENT_AUTORIZATSION_DETAIL_002")]
        [Persistent(@"componentAutorizationID")]
        [ColumnDefaultValue(0)]
        public int ComponentAutorizationID
        {
            get { return fComponentAutorizationID; }
            set { SetPropertyValue<int>(nameof(ComponentAutorizationID), ref fComponentAutorizationID, value); }
        }
        int fComponentID;
        [Indexed(Name = @"IDX_COMPONENT_AUTORIZATSION_DETAIL_003")]
        [Persistent(@"componentID")]
        [ColumnDefaultValue(0)]
        public int ComponentID
        {
            get { return fComponentID; }
            set { SetPropertyValue<int>(nameof(ComponentID), ref fComponentID, value); }
        }
        int fWorkflowID;
        [Indexed(Name = @"IDX_COMPONENT_AUTORIZATSION_DETAIL_004")]
        [Persistent(@"workflowID")]
        [ColumnDefaultValue(0)]
        public int WorkflowID
        {
            get { return fWorkflowID; }
            set { SetPropertyValue<int>(nameof(WorkflowID), ref fWorkflowID, value); }
        }
        int fWorkflowStageID;
        [Indexed(Name = @"IDX_COMPONENT_AUTORIZATSION_DETAIL_005")]
        [Persistent(@"workflowStageID")]
        [ColumnDefaultValue(0)]
        public int WorkflowStageID
        {
            get { return fWorkflowStageID; }
            set { SetPropertyValue<int>(nameof(WorkflowStageID), ref fWorkflowStageID, value); }
        }
        int fComponentAurotizationDetailID;
        [Key(true)]
        [Persistent(@"componentAurotizationDetailID")]
        public int ComponentAurotizationDetailID
        {
            get { return fComponentAurotizationDetailID; }
            set { SetPropertyValue<int>(nameof(ComponentAurotizationDetailID), ref fComponentAurotizationDetailID, value); }
        }
    }

}
