//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace v4posme_window_form.Models.Tablas
{

    [Persistent(@"tb_customer_credit_document_entity_related")]
    public partial class CustomerCreditDocumentEntityRelated : XPLiteObject
    {
        int fCcEntityRelatedID;
        [Key(true)]
        [Persistent(@"ccEntityRelatedID")]
        public int CcEntityRelatedID
        {
            get { return fCcEntityRelatedID; }
            set { SetPropertyValue<int>(nameof(CcEntityRelatedID), ref fCcEntityRelatedID, value); }
        }
        int fCustomerCreditDocumentID;
        [Indexed(Name = @"IDX_CUSTOMER_CREDIT_DOCUMENT_ENTITY_RELATED_001")]
        [Persistent(@"customerCreditDocumentID")]
        [ColumnDefaultValue(0)]
        public int CustomerCreditDocumentID
        {
            get { return fCustomerCreditDocumentID; }
            set { SetPropertyValue<int>(nameof(CustomerCreditDocumentID), ref fCustomerCreditDocumentID, value); }
        }
        int fEntityID;
        [Indexed(Name = @"IDX_CUSTOMER_CREDIT_DOCUMENT_ENTITY_RELATED_002")]
        [Persistent(@"entityID")]
        [ColumnDefaultValue(0)]
        public int EntityID
        {
            get { return fEntityID; }
            set { SetPropertyValue<int>(nameof(EntityID), ref fEntityID, value); }
        }
        int fType;
        [Persistent(@"type")]
        [ColumnDefaultValue(0)]
        public int Type
        {
            get { return fType; }
            set { SetPropertyValue<int>(nameof(Type), ref fType, value); }
        }
        int fTypeCredit;
        [Persistent(@"typeCredit")]
        [ColumnDefaultValue(4)]
        public int TypeCredit
        {
            get { return fTypeCredit; }
            set { SetPropertyValue<int>(nameof(TypeCredit), ref fTypeCredit, value); }
        }
        int fStatusCredit;
        [Persistent(@"statusCredit")]
        [ColumnDefaultValue(1)]
        public int StatusCredit
        {
            get { return fStatusCredit; }
            set { SetPropertyValue<int>(nameof(StatusCredit), ref fStatusCredit, value); }
        }
        int fTypeGarantia;
        [Persistent(@"typeGarantia")]
        [ColumnDefaultValue(4)]
        public int TypeGarantia
        {
            get { return fTypeGarantia; }
            set { SetPropertyValue<int>(nameof(TypeGarantia), ref fTypeGarantia, value); }
        }
        int fTypeRecuperation;
        [Persistent(@"typeRecuperation")]
        [ColumnDefaultValue(1)]
        public int TypeRecuperation
        {
            get { return fTypeRecuperation; }
            set { SetPropertyValue<int>(nameof(TypeRecuperation), ref fTypeRecuperation, value); }
        }
        decimal fRatioDesembolso;
        [Persistent(@"ratioDesembolso")]
        [ColumnDefaultValue(0.00000000)]
        public decimal RatioDesembolso
        {
            get { return fRatioDesembolso; }
            set { SetPropertyValue<decimal>(nameof(RatioDesembolso), ref fRatioDesembolso, value); }
        }
        decimal fRatioBalance;
        [Persistent(@"ratioBalance")]
        [ColumnDefaultValue(0.00000000)]
        public decimal RatioBalance
        {
            get { return fRatioBalance; }
            set { SetPropertyValue<decimal>(nameof(RatioBalance), ref fRatioBalance, value); }
        }
        decimal fRatioBalanceExpired;
        [Persistent(@"ratioBalanceExpired")]
        [ColumnDefaultValue(0.00000000)]
        public decimal RatioBalanceExpired
        {
            get { return fRatioBalanceExpired; }
            set { SetPropertyValue<decimal>(nameof(RatioBalanceExpired), ref fRatioBalanceExpired, value); }
        }
        decimal fRatioShare;
        [Persistent(@"ratioShare")]
        [ColumnDefaultValue(0.00000000)]
        public decimal RatioShare
        {
            get { return fRatioShare; }
            set { SetPropertyValue<decimal>(nameof(RatioShare), ref fRatioShare, value); }
        }
        DateTime fCreatedOn;
        [Persistent(@"createdOn")]
        public DateTime CreatedOn
        {
            get { return fCreatedOn; }
            set { SetPropertyValue<DateTime>(nameof(CreatedOn), ref fCreatedOn, value); }
        }
        int fCreatedBy;
        [Persistent(@"createdBy")]
        [ColumnDefaultValue(0)]
        public int CreatedBy
        {
            get { return fCreatedBy; }
            set { SetPropertyValue<int>(nameof(CreatedBy), ref fCreatedBy, value); }
        }
        string fCreatedIn;
        [Size(120)]
        [Persistent(@"createdIn")]
        [ColumnDefaultValue("0")]
        public string CreatedIn
        {
            get { return fCreatedIn; }
            set { SetPropertyValue<string>(nameof(CreatedIn), ref fCreatedIn, value); }
        }
        int fCreatedAt;
        [Persistent(@"createdAt")]
        [ColumnDefaultValue(0)]
        public int CreatedAt
        {
            get { return fCreatedAt; }
            set { SetPropertyValue<int>(nameof(CreatedAt), ref fCreatedAt, value); }
        }
        bool fIsActive;
        [Persistent(@"isActive")]
        [ColumnDefaultValue(false)]
        public bool IsActive
        {
            get { return fIsActive; }
            set { SetPropertyValue<bool>(nameof(IsActive), ref fIsActive, value); }
        }
    }

}
