//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace v4posme_window_form.Models.Tablas
{

    [Persistent(@"tb_journal_entry_detail")]
    public partial class JournalEntryDetail : XPLiteObject
    {
        int fJournalEntryDetailID;
        [Key(true)]
        [Persistent(@"journalEntryDetailID")]
        public int JournalEntryDetailID
        {
            get { return fJournalEntryDetailID; }
            set { SetPropertyValue<int>(nameof(JournalEntryDetailID), ref fJournalEntryDetailID, value); }
        }
        int fJournalEntryID;
        [Indexed(Name = @"IDX_JOURNAL_ENTRY_DETAIL_001")]
        [Persistent(@"journalEntryID")]
        [ColumnDefaultValue(0)]
        public int JournalEntryID
        {
            get { return fJournalEntryID; }
            set { SetPropertyValue<int>(nameof(JournalEntryID), ref fJournalEntryID, value); }
        }
        int fCompanyID;
        [Indexed(Name = @"IDX_JOURNAL_ENTRY_DETAIL_002")]
        [Persistent(@"companyID")]
        [ColumnDefaultValue(0)]
        public int CompanyID
        {
            get { return fCompanyID; }
            set { SetPropertyValue<int>(nameof(CompanyID), ref fCompanyID, value); }
        }
        int fAccountID;
        [Indexed(Name = @"IDX_JOURNAL_ENTRY_DETAIL_003")]
        [Persistent(@"accountID")]
        [ColumnDefaultValue(0)]
        public int AccountID
        {
            get { return fAccountID; }
            set { SetPropertyValue<int>(nameof(AccountID), ref fAccountID, value); }
        }
        bool fIsActive;
        [Persistent(@"isActive")]
        [ColumnDefaultValue(false)]
        public bool IsActive
        {
            get { return fIsActive; }
            set { SetPropertyValue<bool>(nameof(IsActive), ref fIsActive, value); }
        }
        int fClassID;
        [Indexed(Name = @"IDX_JOURNAL_ENTRY_DETAIL_004")]
        [Persistent(@"classID")]
        public int ClassID
        {
            get { return fClassID; }
            set { SetPropertyValue<int>(nameof(ClassID), ref fClassID, value); }
        }
        decimal fDebit;
        [Persistent(@"debit")]
        [ColumnDefaultValue(0.00000000)]
        public decimal Debit
        {
            get { return fDebit; }
            set { SetPropertyValue<decimal>(nameof(Debit), ref fDebit, value); }
        }
        decimal fCredit;
        [Persistent(@"credit")]
        [ColumnDefaultValue(0.00000000)]
        public decimal Credit
        {
            get { return fCredit; }
            set { SetPropertyValue<decimal>(nameof(Credit), ref fCredit, value); }
        }
        string fNote;
        [Size(250)]
        [Persistent(@"note")]
        public string Note
        {
            get { return fNote; }
            set { SetPropertyValue<string>(nameof(Note), ref fNote, value); }
        }
        bool fIsApplied;
        [Persistent(@"isApplied")]
        public bool IsApplied
        {
            get { return fIsApplied; }
            set { SetPropertyValue<bool>(nameof(IsApplied), ref fIsApplied, value); }
        }
        int fBranchID;
        [Indexed(Name = @"IDX_JOURNAL_ENTRY_DETAIL_005")]
        [Persistent(@"branchID")]
        public int BranchID
        {
            get { return fBranchID; }
            set { SetPropertyValue<int>(nameof(BranchID), ref fBranchID, value); }
        }
        decimal fTb_exchange_rate;
        [Persistent(@"tb_exchange_rate")]
        [ColumnDefaultValue(0.00000000)]
        public decimal Tb_exchange_rate
        {
            get { return fTb_exchange_rate; }
            set { SetPropertyValue<decimal>(nameof(Tb_exchange_rate), ref fTb_exchange_rate, value); }
        }
    }

}
