//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace v4posme_window_form.Models.Tablas
{

    [Persistent(@"tb_price")]
    public partial class Price : XPLiteObject
    {
        int fCompanyID;
        [Indexed(Name = @"IDX_PRICE_001")]
        [Persistent(@"companyID")]
        [ColumnDefaultValue(0)]
        public int CompanyID
        {
            get { return fCompanyID; }
            set { SetPropertyValue<int>(nameof(CompanyID), ref fCompanyID, value); }
        }
        int fListPriceID;
        [Indexed(Name = @"IDX_PRICE_002")]
        [Persistent(@"listPriceID")]
        [ColumnDefaultValue(0)]
        public int ListPriceID
        {
            get { return fListPriceID; }
            set { SetPropertyValue<int>(nameof(ListPriceID), ref fListPriceID, value); }
        }
        int fItemID;
        [Indexed(Name = @"IDX_PRICE_003")]
        [Persistent(@"itemID")]
        [ColumnDefaultValue(0)]
        public int ItemID
        {
            get { return fItemID; }
            set { SetPropertyValue<int>(nameof(ItemID), ref fItemID, value); }
        }
        int fPriceID;
        [Key(true)]
        [Persistent(@"priceID")]
        public int PriceID
        {
            get { return fPriceID; }
            set { SetPropertyValue<int>(nameof(PriceID), ref fPriceID, value); }
        }
        int fTypePriceID;
        [Indexed(Name = @"IDX_PRICE_004")]
        [Persistent(@"typePriceID")]
        [ColumnDefaultValue(0)]
        public int TypePriceID
        {
            get { return fTypePriceID; }
            set { SetPropertyValue<int>(nameof(TypePriceID), ref fTypePriceID, value); }
        }
        decimal fPercentage;
        [Persistent(@"percentage")]
        [ColumnDefaultValue(0.00000000)]
        public decimal Percentage
        {
            get { return fPercentage; }
            set { SetPropertyValue<decimal>(nameof(Percentage), ref fPercentage, value); }
        }
        decimal fPrice1;
        [Persistent(@"price")]
        [ColumnDefaultValue(0.00000000)]
        public decimal Price1
        {
            get { return fPrice1; }
            set { SetPropertyValue<decimal>(nameof(Price1), ref fPrice1, value); }
        }
        decimal fPercentageCommision;
        [Persistent(@"percentageCommision")]
        [ColumnDefaultValue(0.00000000)]
        public decimal PercentageCommision
        {
            get { return fPercentageCommision; }
            set { SetPropertyValue<decimal>(nameof(PercentageCommision), ref fPercentageCommision, value); }
        }
    }

}
