//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace v4posme_window_form.Models.Tablas
{

    [Persistent(@"tb_user")]
    public partial class User : XPLiteObject
    {
        int fCompanyID;
        [Indexed(Name = @"IDX_USER_001")]
        [Persistent(@"companyID")]
        [ColumnDefaultValue(0)]
        public int CompanyID
        {
            get { return fCompanyID; }
            set { SetPropertyValue<int>(nameof(CompanyID), ref fCompanyID, value); }
        }
        int fBranchID;
        [Indexed(Name = @"IDX_USER_002")]
        [Persistent(@"branchID")]
        [ColumnDefaultValue(0)]
        public int BranchID
        {
            get { return fBranchID; }
            set { SetPropertyValue<int>(nameof(BranchID), ref fBranchID, value); }
        }
        int fUserID;
        [Key(true)]
        [Persistent(@"userID")]
        public int UserID
        {
            get { return fUserID; }
            set { SetPropertyValue<int>(nameof(UserID), ref fUserID, value); }
        }
        string fNickname;
        [Indexed(@"Password;IsActive", Name = @"IDX_USER_005")]
        [Size(250)]
        [Persistent(@"nickname")]
        public string Nickname
        {
            get { return fNickname; }
            set { SetPropertyValue<string>(nameof(Nickname), ref fNickname, value); }
        }
        string fPassword;
        [Size(250)]
        [Persistent(@"password")]
        public string Password
        {
            get { return fPassword; }
            set { SetPropertyValue<string>(nameof(Password), ref fPassword, value); }
        }
        string fCreatedOn;
        [Size(250)]
        [Persistent(@"createdOn")]
        public string CreatedOn
        {
            get { return fCreatedOn; }
            set { SetPropertyValue<string>(nameof(CreatedOn), ref fCreatedOn, value); }
        }
        bool fIsActive;
        [Persistent(@"isActive")]
        public bool IsActive
        {
            get { return fIsActive; }
            set { SetPropertyValue<bool>(nameof(IsActive), ref fIsActive, value); }
        }
        string fEmail;
        [Size(250)]
        [Persistent(@"email")]
        [ColumnDefaultValue("0")]
        public string Email
        {
            get { return fEmail; }
            set { SetPropertyValue<string>(nameof(Email), ref fEmail, value); }
        }
        int fCreatedBy;
        [Persistent(@"createdBy")]
        [ColumnDefaultValue(0)]
        public int CreatedBy
        {
            get { return fCreatedBy; }
            set { SetPropertyValue<int>(nameof(CreatedBy), ref fCreatedBy, value); }
        }
        int fEmployeeID;
        [Indexed(Name = @"IDX_USER_004")]
        [Persistent(@"employeeID")]
        [ColumnDefaultValue(0)]
        public int EmployeeID
        {
            get { return fEmployeeID; }
            set { SetPropertyValue<int>(nameof(EmployeeID), ref fEmployeeID, value); }
        }
        int fUseMobile;
        [Persistent(@"useMobile")]
        [ColumnDefaultValue(0)]
        public int UseMobile
        {
            get { return fUseMobile; }
            set { SetPropertyValue<int>(nameof(UseMobile), ref fUseMobile, value); }
        }
        string fPhone;
        [Size(255)]
        [Persistent(@"phone")]
        public string Phone
        {
            get { return fPhone; }
            set { SetPropertyValue<string>(nameof(Phone), ref fPhone, value); }
        }
        DateTime fLastPayment;
        [Persistent(@"lastPayment")]
        public DateTime LastPayment
        {
            get { return fLastPayment; }
            set { SetPropertyValue<DateTime>(nameof(LastPayment), ref fLastPayment, value); }
        }
        string fComercio;
        [Size(255)]
        [Persistent(@"comercio")]
        public string Comercio
        {
            get { return fComercio; }
            set { SetPropertyValue<string>(nameof(Comercio), ref fComercio, value); }
        }
        string fFoto;
        [Size(255)]
        [Persistent(@"foto")]
        public string Foto
        {
            get { return fFoto; }
            set { SetPropertyValue<string>(nameof(Foto), ref fFoto, value); }
        }
        string fToken_google_calendar;
        [Size(1200)]
        [Persistent(@"token_google_calendar")]
        public string Token_google_calendar
        {
            get { return fToken_google_calendar; }
            set { SetPropertyValue<string>(nameof(Token_google_calendar), ref fToken_google_calendar, value); }
        }
    }

}
