//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace v4posme_window_form.Models.dbkroqnguhldo1
{

    [Persistent(@"tb_account_tmp")]
    public partial class AccountTmp : XPLiteObject
    {
        int fAccountID;
        [Key(true)]
        [Persistent(@"accountID")]
        public int AccountID
        {
            get { return fAccountID; }
            set { SetPropertyValue<int>(nameof(AccountID), ref fAccountID, value); }
        }
        int fAccountParentID;
        [Persistent(@"accountParentID")]
        public int AccountParentID
        {
            get { return fAccountParentID; }
            set { SetPropertyValue<int>(nameof(AccountParentID), ref fAccountParentID, value); }
        }
        string fN1;
        [Size(10)]
        [Persistent(@"n1")]
        public string N1
        {
            get { return fN1; }
            set { SetPropertyValue<string>(nameof(N1), ref fN1, value); }
        }
        string fN2;
        [Size(10)]
        [Persistent(@"n2")]
        public string N2
        {
            get { return fN2; }
            set { SetPropertyValue<string>(nameof(N2), ref fN2, value); }
        }
        string fN3;
        [Size(10)]
        [Persistent(@"n3")]
        public string N3
        {
            get { return fN3; }
            set { SetPropertyValue<string>(nameof(N3), ref fN3, value); }
        }
        string fN4;
        [Size(10)]
        [Persistent(@"n4")]
        public string N4
        {
            get { return fN4; }
            set { SetPropertyValue<string>(nameof(N4), ref fN4, value); }
        }
        string fN5;
        [Size(10)]
        [Persistent(@"n5")]
        public string N5
        {
            get { return fN5; }
            set { SetPropertyValue<string>(nameof(N5), ref fN5, value); }
        }
        string fName;
        [Size(250)]
        [Persistent(@"name")]
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        int fNivel;
        [Persistent(@"nivel")]
        public int Nivel
        {
            get { return fNivel; }
            set { SetPropertyValue<int>(nameof(Nivel), ref fNivel, value); }
        }
        bool fOperative;
        [Persistent(@"operative")]
        public bool Operative
        {
            get { return fOperative; }
            set { SetPropertyValue<bool>(nameof(Operative), ref fOperative, value); }
        }
        decimal fBalance;
        [Persistent(@"balance")]
        public decimal Balance
        {
            get { return fBalance; }
            set { SetPropertyValue<decimal>(nameof(Balance), ref fBalance, value); }
        }
    }

}
