//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace v4posme_window_form.Models.dbkroqnguhldo1
{

    [Persistent(@"tb_bank")]
    public partial class Bank : XPLiteObject
    {
        int fBankID;
        [Key(true)]
        [Persistent(@"bankID")]
        public int BankID
        {
            get { return fBankID; }
            set { SetPropertyValue<int>(nameof(BankID), ref fBankID, value); }
        }
        int fCompanyID;
        [Indexed(Name = @"IDX_BANK_003")]
        [Persistent(@"companyID")]
        [ColumnDefaultValue(0)]
        public int CompanyID
        {
            get { return fCompanyID; }
            set { SetPropertyValue<int>(nameof(CompanyID), ref fCompanyID, value); }
        }
        string fName;
        [Size(255)]
        [Persistent(@"name")]
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        int fAccountID;
        [Indexed(Name = @"IDX_BANK_001")]
        [Persistent(@"accountID")]
        [ColumnDefaultValue(0)]
        public int AccountID
        {
            get { return fAccountID; }
            set { SetPropertyValue<int>(nameof(AccountID), ref fAccountID, value); }
        }
        int fCurrencyID;
        [Indexed(Name = @"IDX_BANK_002")]
        [Persistent(@"currencyID")]
        [ColumnDefaultValue(0)]
        public int CurrencyID
        {
            get { return fCurrencyID; }
            set { SetPropertyValue<int>(nameof(CurrencyID), ref fCurrencyID, value); }
        }
        decimal fBalance;
        [Persistent(@"balance")]
        [ColumnDefaultValue(0.00000000)]
        public decimal Balance
        {
            get { return fBalance; }
            set { SetPropertyValue<decimal>(nameof(Balance), ref fBalance, value); }
        }
        int fIsActive;
        [Persistent(@"isActive")]
        [ColumnDefaultValue(1)]
        public int IsActive
        {
            get { return fIsActive; }
            set { SetPropertyValue<int>(nameof(IsActive), ref fIsActive, value); }
        }
    }

}
