//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace v4posme_window_form.Models.dbkroqnguhldo1
{

    [Persistent(@"tb_cash_box_session")]
    public partial class CashBoxSession : XPLiteObject
    {
        int fCompanyID;
        [Indexed(Name = @"IDX_CASH_BOX_SESSION_001")]
        [Persistent(@"companyID")]
        [ColumnDefaultValue(0)]
        public int CompanyID
        {
            get { return fCompanyID; }
            set { SetPropertyValue<int>(nameof(CompanyID), ref fCompanyID, value); }
        }
        int fBranchID;
        [Indexed(Name = @"IDX_CASH_BOX_SESSION_002")]
        [Persistent(@"branchID")]
        [ColumnDefaultValue(0)]
        public int BranchID
        {
            get { return fBranchID; }
            set { SetPropertyValue<int>(nameof(BranchID), ref fBranchID, value); }
        }
        int fCashBoxID;
        [Indexed(Name = @"IDX_CASH_BOX_SESSION_003")]
        [Persistent(@"cashBoxID")]
        [ColumnDefaultValue(0)]
        public int CashBoxID
        {
            get { return fCashBoxID; }
            set { SetPropertyValue<int>(nameof(CashBoxID), ref fCashBoxID, value); }
        }
        int fCashBoxSessionID;
        [Key(true)]
        [Persistent(@"cashBoxSessionID")]
        public int CashBoxSessionID
        {
            get { return fCashBoxSessionID; }
            set { SetPropertyValue<int>(nameof(CashBoxSessionID), ref fCashBoxSessionID, value); }
        }
        DateTime fStartOn;
        [Persistent(@"startOn")]
        public DateTime StartOn
        {
            get { return fStartOn; }
            set { SetPropertyValue<DateTime>(nameof(StartOn), ref fStartOn, value); }
        }
        DateTime fEndOn;
        [Persistent(@"endOn")]
        public DateTime EndOn
        {
            get { return fEndOn; }
            set { SetPropertyValue<DateTime>(nameof(EndOn), ref fEndOn, value); }
        }
        int fStatusID;
        [Indexed(Name = @"IDX_CASH_BOX_SESSION_005")]
        [Persistent(@"statusID")]
        [ColumnDefaultValue(0)]
        public int StatusID
        {
            get { return fStatusID; }
            set { SetPropertyValue<int>(nameof(StatusID), ref fStatusID, value); }
        }
        bool fIsActive;
        [Persistent(@"isActive")]
        [ColumnDefaultValue(false)]
        public bool IsActive
        {
            get { return fIsActive; }
            set { SetPropertyValue<bool>(nameof(IsActive), ref fIsActive, value); }
        }
        int fUserID;
        [Indexed(Name = @"IDX_CASH_BOX_SESSION_006")]
        [Persistent(@"userID")]
        public int UserID
        {
            get { return fUserID; }
            set { SetPropertyValue<int>(nameof(UserID), ref fUserID, value); }
        }
    }

}
