//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace v4posme_window_form.Models.dbkroqnguhldo1
{

    [Persistent(@"tb_company_component_flavor")]
    public partial class CompanyComponentFlavor : XPLiteObject
    {
        int fCompanyID;
        [Indexed(Name = @"IDX_COMPANY_COMPONENT_FLAVOR_001")]
        [Persistent(@"companyID")]
        [ColumnDefaultValue(0)]
        public int CompanyID
        {
            get { return fCompanyID; }
            set { SetPropertyValue<int>(nameof(CompanyID), ref fCompanyID, value); }
        }
        int fComponentID;
        [Indexed(Name = @"IDX_COMPANY_COMPONENT_FLAVOR_002")]
        [Persistent(@"componentID")]
        [ColumnDefaultValue(0)]
        public int ComponentID
        {
            get { return fComponentID; }
            set { SetPropertyValue<int>(nameof(ComponentID), ref fComponentID, value); }
        }
        int fComponentItemID;
        [Indexed(Name = @"IDX_COMPANY_COMPONENT_FLAVOR_003")]
        [Persistent(@"componentItemID")]
        [ColumnDefaultValue(0)]
        public int ComponentItemID
        {
            get { return fComponentItemID; }
            set { SetPropertyValue<int>(nameof(ComponentItemID), ref fComponentItemID, value); }
        }
        string fFlavorID;
        [Indexed(Name = @"IDX_COMPANY_COMPONENT_FLAVOR_004")]
        [Size(250)]
        [Persistent(@"flavorID")]
        [ColumnDefaultValue("0")]
        public string FlavorID
        {
            get { return fFlavorID; }
            set { SetPropertyValue<string>(nameof(FlavorID), ref fFlavorID, value); }
        }
        int fCompanyComponentFlavorID;
        [Key(true)]
        [Persistent(@"companyComponentFlavorID")]
        public int CompanyComponentFlavorID
        {
            get { return fCompanyComponentFlavorID; }
            set { SetPropertyValue<int>(nameof(CompanyComponentFlavorID), ref fCompanyComponentFlavorID, value); }
        }
    }

}
