//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace v4posme_window_form.Models.Tablas
{

    [Indices(@"ParameterID;CompanyID")]
    [Persistent(@"tb_company_parameter")]
    public partial class CompanyParameter : XPLiteObject
    {
        int fParameterID;
        [Indexed(Name = @"IDX_COMPANY_PARAMETER_001")]
        [Persistent(@"parameterID")]
        [ColumnDefaultValue(0)]
        public int ParameterID
        {
            get { return fParameterID; }
            set { SetPropertyValue<int>(nameof(ParameterID), ref fParameterID, value); }
        }
        int fCompanyID;
        [Indexed(Name = @"IDX_COMPANY_PARAMETER_002")]
        [Persistent(@"companyID")]
        [ColumnDefaultValue(0)]
        public int CompanyID
        {
            get { return fCompanyID; }
            set { SetPropertyValue<int>(nameof(CompanyID), ref fCompanyID, value); }
        }
        string fDisplay;
        [Size(250)]
        [Persistent(@"display")]
        [ColumnDefaultValue("0")]
        public string Display
        {
            get { return fDisplay; }
            set { SetPropertyValue<string>(nameof(Display), ref fDisplay, value); }
        }
        string fDescription;
        [Size(250)]
        [Persistent(@"description")]
        [ColumnDefaultValue("0")]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>(nameof(Description), ref fDescription, value); }
        }
        string fValue;
        [Size(300)]
        [Persistent(@"value")]
        [ColumnDefaultValue("0")]
        public string Value
        {
            get { return fValue; }
            set { SetPropertyValue<string>(nameof(Value), ref fValue, value); }
        }
        string fCustomValue;
        [Size(300)]
        [Persistent(@"customValue")]
        [ColumnDefaultValue("0")]
        public string CustomValue
        {
            get { return fCustomValue; }
            set { SetPropertyValue<string>(nameof(CustomValue), ref fCustomValue, value); }
        }
        int fCompanyParameterID;
        [Key(true)]
        [Persistent(@"companyParameterID")]
        public int CompanyParameterID
        {
            get { return fCompanyParameterID; }
            set { SetPropertyValue<int>(nameof(CompanyParameterID), ref fCompanyParameterID, value); }
        }
    }

}
