//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace v4posme_window_form.Models.dbkroqnguhldo1
{

    [Persistent(@"tb_company_subelement_audit")]
    public partial class CompanySubelementAudit : XPLiteObject
    {
        int fElementID;
        [Indexed(Name = @"IDX_COMPANY_SUBELEMENT_AUDIT_001")]
        [Persistent(@"elementID")]
        [ColumnDefaultValue(0)]
        public int ElementID
        {
            get { return fElementID; }
            set { SetPropertyValue<int>(nameof(ElementID), ref fElementID, value); }
        }
        int fSubElementID;
        [Indexed(Name = @"IDX_COMPANY_SUBELEMENT_AUDIT_002")]
        [Persistent(@"subElementID")]
        [ColumnDefaultValue(0)]
        public int SubElementID
        {
            get { return fSubElementID; }
            set { SetPropertyValue<int>(nameof(SubElementID), ref fSubElementID, value); }
        }
        int fCompanyID;
        [Indexed(Name = @"IDX_COMPANY_SUBELEMENT_AUDIT_003")]
        [Persistent(@"companyID")]
        [ColumnDefaultValue(0)]
        public int CompanyID
        {
            get { return fCompanyID; }
            set { SetPropertyValue<int>(nameof(CompanyID), ref fCompanyID, value); }
        }
        int fCompanySubelementAudiID;
        [Key(true)]
        [Persistent(@"companySubelementAudiID")]
        public int CompanySubelementAudiID
        {
            get { return fCompanySubelementAudiID; }
            set { SetPropertyValue<int>(nameof(CompanySubelementAudiID), ref fCompanySubelementAudiID, value); }
        }
    }

}
