//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace v4posme_window_form.Models.dbkroqnguhldo1
{

    [Persistent(@"tb_component_element")]
    public partial class ComponentElement : XPLiteObject
    {
        int fElementID;
        [Indexed(Name = @"IDX_COMPONENT_ELEMENT_001")]
        [Persistent(@"elementID")]
        [ColumnDefaultValue(0)]
        public int ElementID
        {
            get { return fElementID; }
            set { SetPropertyValue<int>(nameof(ElementID), ref fElementID, value); }
        }
        int fComponentID;
        [Indexed(Name = @"IDX_COMPONENT_ELEMENT_002")]
        [Persistent(@"componentID")]
        [ColumnDefaultValue(0)]
        public int ComponentID
        {
            get { return fComponentID; }
            set { SetPropertyValue<int>(nameof(ComponentID), ref fComponentID, value); }
        }
        int fComponentElementID;
        [Key(true)]
        [Persistent(@"componentElementID")]
        public int ComponentElementID
        {
            get { return fComponentElementID; }
            set { SetPropertyValue<int>(nameof(ComponentElementID), ref fComponentElementID, value); }
        }
    }

}
