//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace v4posme_window_form.Models.Tablas
{

    [Indices(@"CompanyID;ComponentID;CallerID;TargetComponentID")]
    [Persistent(@"tb_company_default_dataview")]
    public partial class CompanyDefaultDataview : XPLiteObject
    {
        int fCompanyID;
        [Indexed(Name = @"IDX_COMPANY_DEFAULT_DATAVIEW_001")]
        [Persistent(@"companyID")]
        [ColumnDefaultValue(0)]
        public int CompanyID
        {
            get { return fCompanyID; }
            set { SetPropertyValue<int>(nameof(CompanyID), ref fCompanyID, value); }
        }
        int fComponentID;
        [Indexed(Name = @"IDX_COMPANY_DEFAULT_DATAVIEW_002")]
        [Persistent(@"componentID")]
        [ColumnDefaultValue(0)]
        public int ComponentID
        {
            get { return fComponentID; }
            set { SetPropertyValue<int>(nameof(ComponentID), ref fComponentID, value); }
        }
        int fDataViewID;
        [Indexed(Name = @"IDX_COMPANY_DEFAULT_DATAVIEW_003")]
        [Persistent(@"dataViewID")]
        [ColumnDefaultValue(0)]
        public int DataViewID
        {
            get { return fDataViewID; }
            set { SetPropertyValue<int>(nameof(DataViewID), ref fDataViewID, value); }
        }
        int fCallerID;
        [Indexed(Name = @"IDX_COMPANY_DEFAULT_DATAVIEW_004")]
        [Persistent(@"callerID")]
        [ColumnDefaultValue(0)]
        public int CallerID
        {
            get { return fCallerID; }
            set { SetPropertyValue<int>(nameof(CallerID), ref fCallerID, value); }
        }
        int fTargetComponentID;
        [Indexed(Name = @"IDX_COMPANY_DEFAULT_DATAVIEW_005")]
        [Persistent(@"targetComponentID")]
        public int TargetComponentID
        {
            get { return fTargetComponentID; }
            set { SetPropertyValue<int>(nameof(TargetComponentID), ref fTargetComponentID, value); }
        }
        int fCompanyDefaultDataviewID;
        [Key(true)]
        [Persistent(@"companyDefaultDataviewID")]
        public int CompanyDefaultDataviewID
        {
            get { return fCompanyDefaultDataviewID; }
            set { SetPropertyValue<int>(nameof(CompanyDefaultDataviewID), ref fCompanyDefaultDataviewID, value); }
        }
    }

}
