//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace v4posme_window_form.Models.Tablas
{

    [Persistent(@"tb_counter")]
    public partial class Counter : XPLiteObject
    {
        int fCounterID;
        [Key(true)]
        [Persistent(@"counterID")]
        public int CounterID
        {
            get { return fCounterID; }
            set { SetPropertyValue<int>(nameof(CounterID), ref fCounterID, value); }
        }
        int fComponentID;
        [Indexed(Name = @"IDX_COUNTER_001")]
        [Persistent(@"componentID")]
        [ColumnDefaultValue(0)]
        public int ComponentID
        {
            get { return fComponentID; }
            set { SetPropertyValue<int>(nameof(ComponentID), ref fComponentID, value); }
        }
        int fCompanyID;
        [Indexed(Name = @"IDX_COUNTER_002")]
        [Persistent(@"companyID")]
        [ColumnDefaultValue(0)]
        public int CompanyID
        {
            get { return fCompanyID; }
            set { SetPropertyValue<int>(nameof(CompanyID), ref fCompanyID, value); }
        }
        int fBranchID;
        [Indexed(Name = @"IDX_COUNTER_003")]
        [Persistent(@"branchID")]
        [ColumnDefaultValue(0)]
        public int BranchID
        {
            get { return fBranchID; }
            set { SetPropertyValue<int>(nameof(BranchID), ref fBranchID, value); }
        }
        int fComponentItemID;
        [Indexed(Name = @"IDX_COUNTER_004")]
        [Persistent(@"componentItemID")]
        public int ComponentItemID
        {
            get { return fComponentItemID; }
            set { SetPropertyValue<int>(nameof(ComponentItemID), ref fComponentItemID, value); }
        }
        int fInitialValue;
        [Persistent(@"initialValue")]
        public int InitialValue
        {
            get { return fInitialValue; }
            set { SetPropertyValue<int>(nameof(InitialValue), ref fInitialValue, value); }
        }
        int fCurrentValue;
        [Persistent(@"currentValue")]
        public int CurrentValue
        {
            get { return fCurrentValue; }
            set { SetPropertyValue<int>(nameof(CurrentValue), ref fCurrentValue, value); }
        }
        int fSeed;
        [Persistent(@"seed")]
        public int Seed
        {
            get { return fSeed; }
            set { SetPropertyValue<int>(nameof(Seed), ref fSeed, value); }
        }
        string fSerie;
        [Size(10)]
        [Persistent(@"serie")]
        public string Serie
        {
            get { return fSerie; }
            set { SetPropertyValue<string>(nameof(Serie), ref fSerie, value); }
        }
        int fLength;
        [Persistent(@"length")]
        public int Length
        {
            get { return fLength; }
            set { SetPropertyValue<int>(nameof(Length), ref fLength, value); }
        }
    }

}
