//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace v4posme_window_form.Models.Tablas
{

    [Persistent(@"tb_credit_line")]
    public partial class CreditLine : XPLiteObject
    {
        int fCreditLineID;
        [Key(true)]
        [Persistent(@"creditLineID")]
        public int CreditLineID
        {
            get { return fCreditLineID; }
            set { SetPropertyValue<int>(nameof(CreditLineID), ref fCreditLineID, value); }
        }
        int fCompanyID;
        [Indexed(Name = @"IDX_CREDIT_LINE_001")]
        [Persistent(@"companyID")]
        [ColumnDefaultValue(0)]
        public int CompanyID
        {
            get { return fCompanyID; }
            set { SetPropertyValue<int>(nameof(CompanyID), ref fCompanyID, value); }
        }
        string fName;
        [Size(150)]
        [Persistent(@"name")]
        [ColumnDefaultValue("0")]
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        string fDescription;
        [Size(400)]
        [Persistent(@"description")]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>(nameof(Description), ref fDescription, value); }
        }
        bool fIsActive;
        [Persistent(@"isActive")]
        [ColumnDefaultValue(false)]
        public bool IsActive
        {
            get { return fIsActive; }
            set { SetPropertyValue<bool>(nameof(IsActive), ref fIsActive, value); }
        }
    }

}
