//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace v4posme_window_form.Models.dbkroqnguhldo1
{

    [Persistent(@"tb_customer_consultas_sin_riesgo")]
    public partial class CustomerConsultasSinRiesgo : XPLiteObject
    {
        int fRequestID;
        [Key(true)]
        [Persistent(@"requestID")]
        public int RequestID
        {
            get { return fRequestID; }
            set { SetPropertyValue<int>(nameof(RequestID), ref fRequestID, value); }
        }
        int fCompanyID;
        [Indexed(Name = @"IDX_CUSTOMER_CONSULTA_SIN_RIESGO_001")]
        [Persistent(@"companyID")]
        [ColumnDefaultValue(0)]
        public int CompanyID
        {
            get { return fCompanyID; }
            set { SetPropertyValue<int>(nameof(CompanyID), ref fCompanyID, value); }
        }
        string fName;
        [Size(150)]
        [Persistent(@"name")]
        [ColumnDefaultValue("0")]
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        string fId;
        [Indexed(Name = @"IDX_CUSTOMER_CONSULTA_SIN_RIESGO_003")]
        [Size(50)]
        [Persistent(@"id")]
        [ColumnDefaultValue("0")]
        public string Id
        {
            get { return fId; }
            set { SetPropertyValue<string>(nameof(Id), ref fId, value); }
        }
        string fFile;
        [Size(150)]
        [Persistent(@"file")]
        [ColumnDefaultValue("0")]
        public string File
        {
            get { return fFile; }
            set { SetPropertyValue<string>(nameof(File), ref fFile, value); }
        }
        int fUserID;
        [Indexed(Name = @"IDX_CUSTOMER_CONSULTA_SIN_RIESGO_004")]
        [Persistent(@"userID")]
        [ColumnDefaultValue(0)]
        public int UserID
        {
            get { return fUserID; }
            set { SetPropertyValue<int>(nameof(UserID), ref fUserID, value); }
        }
        DateTime fCreatedOn;
        [Persistent(@"createdOn")]
        [ColumnDefaultValue(1980, 1, 1, 0, 0, 0, 0)]
        public DateTime CreatedOn
        {
            get { return fCreatedOn; }
            set { SetPropertyValue<DateTime>(nameof(CreatedOn), ref fCreatedOn, value); }
        }
        int fCreatedBy;
        [Persistent(@"createdBy")]
        [ColumnDefaultValue(0)]
        public int CreatedBy
        {
            get { return fCreatedBy; }
            set { SetPropertyValue<int>(nameof(CreatedBy), ref fCreatedBy, value); }
        }
        string fCreatedIn;
        [Size(50)]
        [Persistent(@"createdIn")]
        [ColumnDefaultValue("0")]
        public string CreatedIn
        {
            get { return fCreatedIn; }
            set { SetPropertyValue<string>(nameof(CreatedIn), ref fCreatedIn, value); }
        }
        int fCreatedAt;
        [Persistent(@"createdAt")]
        [ColumnDefaultValue(0)]
        public int CreatedAt
        {
            get { return fCreatedAt; }
            set { SetPropertyValue<int>(nameof(CreatedAt), ref fCreatedAt, value); }
        }
        DateTime fModifiedOn;
        [Persistent(@"modifiedOn")]
        [ColumnDefaultValue(1980, 1, 1, 0, 0, 0, 0)]
        public DateTime ModifiedOn
        {
            get { return fModifiedOn; }
            set { SetPropertyValue<DateTime>(nameof(ModifiedOn), ref fModifiedOn, value); }
        }
        bool fIsPay;
        [Persistent(@"isPay")]
        [ColumnDefaultValue(false)]
        public bool IsPay
        {
            get { return fIsPay; }
            set { SetPropertyValue<bool>(nameof(IsPay), ref fIsPay, value); }
        }
    }

}
