//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace v4posme_window_form.Models.Tablas
{

    [Persistent(@"tb_employee_calendar_pay")]
    public partial class EmployeeCalendarPay : XPLiteObject
    {
        int fCalendarID;
        [Key(true)]
        [Persistent(@"calendarID")]
        public int CalendarID
        {
            get { return fCalendarID; }
            set { SetPropertyValue<int>(nameof(CalendarID), ref fCalendarID, value); }
        }
        int fCompanyID;
        [Indexed(Name = @"IDX_EMPLOYEE_CALENDAR_PAY_001")]
        [Persistent(@"companyID")]
        [ColumnDefaultValue(0)]
        public int CompanyID
        {
            get { return fCompanyID; }
            set { SetPropertyValue<int>(nameof(CompanyID), ref fCompanyID, value); }
        }
        int fAccountingCycleID;
        [Indexed(Name = @"IDX_EMPLOYEE_CALENDAR_PAY_002")]
        [Persistent(@"accountingCycleID")]
        [ColumnDefaultValue(0)]
        public int AccountingCycleID
        {
            get { return fAccountingCycleID; }
            set { SetPropertyValue<int>(nameof(AccountingCycleID), ref fAccountingCycleID, value); }
        }
        string fName;
        [Size(300)]
        [Persistent(@"name")]
        [ColumnDefaultValue("0")]
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        string fNumber;
        [Size(15)]
        [Persistent(@"number")]
        [ColumnDefaultValue("0")]
        public string Number
        {
            get { return fNumber; }
            set { SetPropertyValue<string>(nameof(Number), ref fNumber, value); }
        }
        int fTypeID;
        [Indexed(Name = @"IDX_EMPLOYEE_CALENDAR_PAY_003")]
        [Persistent(@"typeID")]
        [ColumnDefaultValue(0)]
        public int TypeID
        {
            get { return fTypeID; }
            set { SetPropertyValue<int>(nameof(TypeID), ref fTypeID, value); }
        }
        int fCurrencyID;
        [Indexed(Name = @"IDX_EMPLOYEE_CALENDAR_PAY_004")]
        [Persistent(@"currencyID")]
        [ColumnDefaultValue(0)]
        public int CurrencyID
        {
            get { return fCurrencyID; }
            set { SetPropertyValue<int>(nameof(CurrencyID), ref fCurrencyID, value); }
        }
        int fStatusID;
        [Indexed(Name = @"IDX_EMPLOYEE_CALENDAR_PAY_005")]
        [Persistent(@"statusID")]
        [ColumnDefaultValue(0)]
        public int StatusID
        {
            get { return fStatusID; }
            set { SetPropertyValue<int>(nameof(StatusID), ref fStatusID, value); }
        }
        string fDescription;
        [Size(1500)]
        [Persistent(@"description")]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>(nameof(Description), ref fDescription, value); }
        }
        int fCreatedBy;
        [Persistent(@"createdBy")]
        [ColumnDefaultValue(0)]
        public int CreatedBy
        {
            get { return fCreatedBy; }
            set { SetPropertyValue<int>(nameof(CreatedBy), ref fCreatedBy, value); }
        }
        int fCreatedAt;
        [Persistent(@"createdAt")]
        [ColumnDefaultValue(0)]
        public int CreatedAt
        {
            get { return fCreatedAt; }
            set { SetPropertyValue<int>(nameof(CreatedAt), ref fCreatedAt, value); }
        }
        DateTime fCreatedOn;
        [Persistent(@"createdOn")]
        [ColumnDefaultValue(1980, 1, 1, 0, 0, 0, 0)]
        public DateTime CreatedOn
        {
            get { return fCreatedOn; }
            set { SetPropertyValue<DateTime>(nameof(CreatedOn), ref fCreatedOn, value); }
        }
        string fCreatedIn;
        [Size(50)]
        [Persistent(@"createdIn")]
        [ColumnDefaultValue("0")]
        public string CreatedIn
        {
            get { return fCreatedIn; }
            set { SetPropertyValue<string>(nameof(CreatedIn), ref fCreatedIn, value); }
        }
        bool fIsActive;
        [Persistent(@"isActive")]
        [ColumnDefaultValue(false)]
        public bool IsActive
        {
            get { return fIsActive; }
            set { SetPropertyValue<bool>(nameof(IsActive), ref fIsActive, value); }
        }
    }

}
