//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace v4posme_window_form.Models.Tablas
{

    [Persistent(@"tb_item_category")]
    public partial class ItemCategory : XPLiteObject
    {
        int fCompanyID;
        [Indexed(Name = @"IDX_ITEM_CATEGORY_001")]
        [Persistent(@"companyID")]
        [ColumnDefaultValue(0)]
        public int CompanyID
        {
            get { return fCompanyID; }
            set { SetPropertyValue<int>(nameof(CompanyID), ref fCompanyID, value); }
        }
        int fBranchID;
        [Indexed(Name = @"IDX_ITEM_CATEGORY_002")]
        [Persistent(@"branchID")]
        [ColumnDefaultValue(0)]
        public int BranchID
        {
            get { return fBranchID; }
            set { SetPropertyValue<int>(nameof(BranchID), ref fBranchID, value); }
        }
        int fInventoryCategoryID;
        [Key(true)]
        [Persistent(@"inventoryCategoryID")]
        public int InventoryCategoryID
        {
            get { return fInventoryCategoryID; }
            set { SetPropertyValue<int>(nameof(InventoryCategoryID), ref fInventoryCategoryID, value); }
        }
        string fName;
        [Size(250)]
        [Persistent(@"name")]
        [ColumnDefaultValue("0")]
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        string fDescription;
        [Size(250)]
        [Persistent(@"description")]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>(nameof(Description), ref fDescription, value); }
        }
        bool fIsActive;
        [Persistent(@"isActive")]
        public bool IsActive
        {
            get { return fIsActive; }
            set { SetPropertyValue<bool>(nameof(IsActive), ref fIsActive, value); }
        }
        string fCreatedIn;
        [Size(250)]
        [Persistent(@"createdIn")]
        public string CreatedIn
        {
            get { return fCreatedIn; }
            set { SetPropertyValue<string>(nameof(CreatedIn), ref fCreatedIn, value); }
        }
        int fCreatedBy;
        [Persistent(@"createdBy")]
        public int CreatedBy
        {
            get { return fCreatedBy; }
            set { SetPropertyValue<int>(nameof(CreatedBy), ref fCreatedBy, value); }
        }
        DateTime fCreatedOn;
        [Persistent(@"createdOn")]
        public DateTime CreatedOn
        {
            get { return fCreatedOn; }
            set { SetPropertyValue<DateTime>(nameof(CreatedOn), ref fCreatedOn, value); }
        }
        int fCreatedAt;
        [Persistent(@"createdAt")]
        public int CreatedAt
        {
            get { return fCreatedAt; }
            set { SetPropertyValue<int>(nameof(CreatedAt), ref fCreatedAt, value); }
        }
    }

}
