//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace v4posme_window_form.Models.dbkroqnguhldo1
{

    [Persistent(@"tb_provider")]
    public partial class Provider : XPLiteObject
    {
        int fProviderID;
        [Key(true)]
        [Persistent(@"providerID")]
        public int ProviderID
        {
            get { return fProviderID; }
            set { SetPropertyValue<int>(nameof(ProviderID), ref fProviderID, value); }
        }
        int fCompanyID;
        [Indexed(Name = @"IDX_PROVIDER_001")]
        [Persistent(@"companyID")]
        [ColumnDefaultValue(0)]
        public int CompanyID
        {
            get { return fCompanyID; }
            set { SetPropertyValue<int>(nameof(CompanyID), ref fCompanyID, value); }
        }
        int fBranchID;
        [Indexed(Name = @"IDX_PROVIDER_002")]
        [Persistent(@"branchID")]
        [ColumnDefaultValue(0)]
        public int BranchID
        {
            get { return fBranchID; }
            set { SetPropertyValue<int>(nameof(BranchID), ref fBranchID, value); }
        }
        int fEntityID;
        [Indexed(Name = @"IDX_PROVIDER_003")]
        [Persistent(@"entityID")]
        [ColumnDefaultValue(0)]
        public int EntityID
        {
            get { return fEntityID; }
            set { SetPropertyValue<int>(nameof(EntityID), ref fEntityID, value); }
        }
        string fProviderNumber;
        [Indexed(Name = @"IDX_PROVIDER_004")]
        [Size(250)]
        [Persistent(@"providerNumber")]
        [ColumnDefaultValue("0")]
        public string ProviderNumber
        {
            get { return fProviderNumber; }
            set { SetPropertyValue<string>(nameof(ProviderNumber), ref fProviderNumber, value); }
        }
        string fNumberIdentification;
        [Size(250)]
        [Persistent(@"numberIdentification")]
        public string NumberIdentification
        {
            get { return fNumberIdentification; }
            set { SetPropertyValue<string>(nameof(NumberIdentification), ref fNumberIdentification, value); }
        }
        int fIdentificationTypeID;
        [Indexed(Name = @"IDX_PROVIDER_005")]
        [Persistent(@"identificationTypeID")]
        public int IdentificationTypeID
        {
            get { return fIdentificationTypeID; }
            set { SetPropertyValue<int>(nameof(IdentificationTypeID), ref fIdentificationTypeID, value); }
        }
        int fProviderType;
        [Indexed(Name = @"IDX_PROVIDER_006")]
        [Persistent(@"providerType")]
        public int ProviderType
        {
            get { return fProviderType; }
            set { SetPropertyValue<int>(nameof(ProviderType), ref fProviderType, value); }
        }
        int fProviderCategoryID;
        [Indexed(Name = @"IDX_PROVIDER_007")]
        [Persistent(@"providerCategoryID")]
        public int ProviderCategoryID
        {
            get { return fProviderCategoryID; }
            set { SetPropertyValue<int>(nameof(ProviderCategoryID), ref fProviderCategoryID, value); }
        }
        int fProviderClasificationID;
        [Indexed(Name = @"IDX_PROVIDER_008")]
        [Persistent(@"providerClasificationID")]
        public int ProviderClasificationID
        {
            get { return fProviderClasificationID; }
            set { SetPropertyValue<int>(nameof(ProviderClasificationID), ref fProviderClasificationID, value); }
        }
        string fReference1;
        [Size(250)]
        [Persistent(@"reference1")]
        public string Reference1
        {
            get { return fReference1; }
            set { SetPropertyValue<string>(nameof(Reference1), ref fReference1, value); }
        }
        string fReference2;
        [Size(250)]
        [Persistent(@"reference2")]
        public string Reference2
        {
            get { return fReference2; }
            set { SetPropertyValue<string>(nameof(Reference2), ref fReference2, value); }
        }
        int fPayConditionID;
        [Indexed(Name = @"IDX_PROVIDER_009")]
        [Persistent(@"payConditionID")]
        public int PayConditionID
        {
            get { return fPayConditionID; }
            set { SetPropertyValue<int>(nameof(PayConditionID), ref fPayConditionID, value); }
        }
        bool fIsLocal;
        [Persistent(@"isLocal")]
        public bool IsLocal
        {
            get { return fIsLocal; }
            set { SetPropertyValue<bool>(nameof(IsLocal), ref fIsLocal, value); }
        }
        int fCountryID;
        [Indexed(Name = @"IDX_PROVIDER_010")]
        [Persistent(@"countryID")]
        public int CountryID
        {
            get { return fCountryID; }
            set { SetPropertyValue<int>(nameof(CountryID), ref fCountryID, value); }
        }
        int fStateID;
        [Indexed(Name = @"IDX_PROVIDER_011")]
        [Persistent(@"stateID")]
        public int StateID
        {
            get { return fStateID; }
            set { SetPropertyValue<int>(nameof(StateID), ref fStateID, value); }
        }
        int fCityID;
        [Indexed(Name = @"IDX_PROVIDER_012")]
        [Persistent(@"cityID")]
        public int CityID
        {
            get { return fCityID; }
            set { SetPropertyValue<int>(nameof(CityID), ref fCityID, value); }
        }
        string fAddress;
        [Size(250)]
        [Persistent(@"address")]
        public string Address
        {
            get { return fAddress; }
            set { SetPropertyValue<string>(nameof(Address), ref fAddress, value); }
        }
        int fCurrencyID;
        [Indexed(Name = @"IDX_PROVIDER_013")]
        [Persistent(@"currencyID")]
        public int CurrencyID
        {
            get { return fCurrencyID; }
            set { SetPropertyValue<int>(nameof(CurrencyID), ref fCurrencyID, value); }
        }
        int fStatusID;
        [Indexed(Name = @"IDX_PROVIDER_014")]
        [Persistent(@"statusID")]
        public int StatusID
        {
            get { return fStatusID; }
            set { SetPropertyValue<int>(nameof(StatusID), ref fStatusID, value); }
        }
        int fDeleveryDay;
        [Persistent(@"deleveryDay")]
        public int DeleveryDay
        {
            get { return fDeleveryDay; }
            set { SetPropertyValue<int>(nameof(DeleveryDay), ref fDeleveryDay, value); }
        }
        int fDeleveryDayReal;
        [Persistent(@"deleveryDayReal")]
        public int DeleveryDayReal
        {
            get { return fDeleveryDayReal; }
            set { SetPropertyValue<int>(nameof(DeleveryDayReal), ref fDeleveryDayReal, value); }
        }
        decimal fDistancia;
        [Persistent(@"distancia")]
        public decimal Distancia
        {
            get { return fDistancia; }
            set { SetPropertyValue<decimal>(nameof(Distancia), ref fDistancia, value); }
        }
        string fCreatedIn;
        [Size(250)]
        [Persistent(@"createdIn")]
        public string CreatedIn
        {
            get { return fCreatedIn; }
            set { SetPropertyValue<string>(nameof(CreatedIn), ref fCreatedIn, value); }
        }
        int fCreatedBy;
        [Persistent(@"createdBy")]
        public int CreatedBy
        {
            get { return fCreatedBy; }
            set { SetPropertyValue<int>(nameof(CreatedBy), ref fCreatedBy, value); }
        }
        int fCreatedAt;
        [Persistent(@"createdAt")]
        public int CreatedAt
        {
            get { return fCreatedAt; }
            set { SetPropertyValue<int>(nameof(CreatedAt), ref fCreatedAt, value); }
        }
        DateTime fCreatedOn;
        [Persistent(@"createdOn")]
        public DateTime CreatedOn
        {
            get { return fCreatedOn; }
            set { SetPropertyValue<DateTime>(nameof(CreatedOn), ref fCreatedOn, value); }
        }
        bool fIsActive;
        [Persistent(@"isActive")]
        public bool IsActive
        {
            get { return fIsActive; }
            set { SetPropertyValue<bool>(nameof(IsActive), ref fIsActive, value); }
        }
    }

}
