//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace v4posme_window_form.Models.dbkroqnguhldo1
{

    [Persistent(@"tb_public_catalog_detail")]
    public partial class PublicCatalogDetail : XPLiteObject
    {
        int fPublicCatalogDetailID;
        [Key(true)]
        [Persistent(@"publicCatalogDetailID")]
        public int PublicCatalogDetailID
        {
            get { return fPublicCatalogDetailID; }
            set { SetPropertyValue<int>(nameof(PublicCatalogDetailID), ref fPublicCatalogDetailID, value); }
        }
        int fPublicCatalogID;
        [Indexed(Name = @"IDX_PUBLIC_CATALOG_DETAIL_001")]
        [Persistent(@"publicCatalogID")]
        public int PublicCatalogID
        {
            get { return fPublicCatalogID; }
            set { SetPropertyValue<int>(nameof(PublicCatalogID), ref fPublicCatalogID, value); }
        }
        string fName;
        [Size(255)]
        [Persistent(@"name")]
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        string fDisplay;
        [Size(255)]
        [Persistent(@"display")]
        public string Display
        {
            get { return fDisplay; }
            set { SetPropertyValue<string>(nameof(Display), ref fDisplay, value); }
        }
        int fFlavorID;
        [Indexed(Name = @"IDX_PUBLIC_CATALOG_DETAIL_002")]
        [Persistent(@"flavorID")]
        public int FlavorID
        {
            get { return fFlavorID; }
            set { SetPropertyValue<int>(nameof(FlavorID), ref fFlavorID, value); }
        }
        string fDescription;
        [Size(255)]
        [Persistent(@"description")]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>(nameof(Description), ref fDescription, value); }
        }
        string fSequence;
        [Size(255)]
        [Persistent(@"sequence")]
        public string Sequence
        {
            get { return fSequence; }
            set { SetPropertyValue<string>(nameof(Sequence), ref fSequence, value); }
        }
        int fParentCatalogDetailID;
        [Indexed(Name = @"IDX_PUBLIC_CATALOG_DETAIL_003")]
        [Persistent(@"parentCatalogDetailID")]
        public int ParentCatalogDetailID
        {
            get { return fParentCatalogDetailID; }
            set { SetPropertyValue<int>(nameof(ParentCatalogDetailID), ref fParentCatalogDetailID, value); }
        }
        string fRatio;
        [Size(255)]
        [Persistent(@"ratio")]
        public string Ratio
        {
            get { return fRatio; }
            set { SetPropertyValue<string>(nameof(Ratio), ref fRatio, value); }
        }
        string fReference1;
        [Size(255)]
        [Persistent(@"reference1")]
        public string Reference1
        {
            get { return fReference1; }
            set { SetPropertyValue<string>(nameof(Reference1), ref fReference1, value); }
        }
        string fReference2;
        [Size(255)]
        [Persistent(@"reference2")]
        public string Reference2
        {
            get { return fReference2; }
            set { SetPropertyValue<string>(nameof(Reference2), ref fReference2, value); }
        }
        string fReference3;
        [Size(255)]
        [Persistent(@"reference3")]
        public string Reference3
        {
            get { return fReference3; }
            set { SetPropertyValue<string>(nameof(Reference3), ref fReference3, value); }
        }
        string fReference4;
        [Size(255)]
        [Persistent(@"reference4")]
        public string Reference4
        {
            get { return fReference4; }
            set { SetPropertyValue<string>(nameof(Reference4), ref fReference4, value); }
        }
        string fParentName;
        [Size(255)]
        [Persistent(@"parentName")]
        public string ParentName
        {
            get { return fParentName; }
            set { SetPropertyValue<string>(nameof(ParentName), ref fParentName, value); }
        }
        string fIsActive;
        [Indexed(Name = @"IDX_PUBLIC_CATALOG_DETAIL_004")]
        [Size(255)]
        [Persistent(@"isActive")]
        public string IsActive
        {
            get { return fIsActive; }
            set { SetPropertyValue<string>(nameof(IsActive), ref fIsActive, value); }
        }
    }

}
