//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace v4posme_window_form.Models.Tablas
{

    [Persistent(@"tb_role")]
    public partial class Role : XPLiteObject
    {
        int fRoleID;
        [Indexed(@"CompanyID;BranchID;IsActive", Name = @"IDX_ROLE_003")]
        [Key(true)]
        [Persistent(@"roleID")]
        public int RoleID
        {
            get { return fRoleID; }
            set { SetPropertyValue<int>(nameof(RoleID), ref fRoleID, value); }
        }
        int fCompanyID;
        [Indexed(Name = @"IDX_ROLE_001")]
        [Persistent(@"companyID")]
        [ColumnDefaultValue(0)]
        public int CompanyID
        {
            get { return fCompanyID; }
            set { SetPropertyValue<int>(nameof(CompanyID), ref fCompanyID, value); }
        }
        int fBranchID;
        [Indexed(Name = @"IDX_ROLE_002")]
        [Persistent(@"branchID")]
        [ColumnDefaultValue(0)]
        public int BranchID
        {
            get { return fBranchID; }
            set { SetPropertyValue<int>(nameof(BranchID), ref fBranchID, value); }
        }
        string fName;
        [Size(250)]
        [Persistent(@"name")]
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        string fDescription;
        [Size(250)]
        [Persistent(@"description")]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>(nameof(Description), ref fDescription, value); }
        }
        bool fIsAdmin;
        [Persistent(@"isAdmin")]
        public bool IsAdmin
        {
            get { return fIsAdmin; }
            set { SetPropertyValue<bool>(nameof(IsAdmin), ref fIsAdmin, value); }
        }
        DateTime fCreatedOn;
        [Persistent(@"createdOn")]
        public DateTime CreatedOn
        {
            get { return fCreatedOn; }
            set { SetPropertyValue<DateTime>(nameof(CreatedOn), ref fCreatedOn, value); }
        }
        string fUrlDefault;
        [Size(250)]
        [Persistent(@"urlDefault")]
        [ColumnDefaultValue("0")]
        public string UrlDefault
        {
            get { return fUrlDefault; }
            set { SetPropertyValue<string>(nameof(UrlDefault), ref fUrlDefault, value); }
        }
        bool fIsActive;
        [Persistent(@"isActive")]
        public bool IsActive
        {
            get { return fIsActive; }
            set { SetPropertyValue<bool>(nameof(IsActive), ref fIsActive, value); }
        }
        int fCreatedBy;
        [Persistent(@"createdBy")]
        [ColumnDefaultValue(0)]
        public int CreatedBy
        {
            get { return fCreatedBy; }
            set { SetPropertyValue<int>(nameof(CreatedBy), ref fCreatedBy, value); }
        }
    }

}
