//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace v4posme_window_form.Models.Tablas
{

    [Persistent(@"tb_transaction_master_detail_credit")]
    public partial class TransactionMasterDetailCredit : XPLiteObject
    {
        int fTransactionMasterDetailCreditID;
        [Key(true)]
        [Persistent(@"transactionMasterDetailCreditID")]
        public int TransactionMasterDetailCreditID
        {
            get { return fTransactionMasterDetailCreditID; }
            set { SetPropertyValue<int>(nameof(TransactionMasterDetailCreditID), ref fTransactionMasterDetailCreditID, value); }
        }
        int fTransactionMasterID;
        [Indexed(Name = @"IDX_TRANSACTION_MASTER_DETAIL_CREDIT_001")]
        [Persistent(@"transactionMasterID")]
        [ColumnDefaultValue(0)]
        public int TransactionMasterID
        {
            get { return fTransactionMasterID; }
            set { SetPropertyValue<int>(nameof(TransactionMasterID), ref fTransactionMasterID, value); }
        }
        int fTransactionMasterDetailID;
        [Indexed(Name = @"IDX_TRANSACTION_MASTER_DETAIL_CREDIT_002")]
        [Persistent(@"transactionMasterDetailID")]
        [ColumnDefaultValue(0)]
        public int TransactionMasterDetailID
        {
            get { return fTransactionMasterDetailID; }
            set { SetPropertyValue<int>(nameof(TransactionMasterDetailID), ref fTransactionMasterDetailID, value); }
        }
        decimal fCapital;
        [Persistent(@"capital")]
        [ColumnDefaultValue(0.00000000)]
        public decimal Capital
        {
            get { return fCapital; }
            set { SetPropertyValue<decimal>(nameof(Capital), ref fCapital, value); }
        }
        decimal fInterest;
        [Persistent(@"interest")]
        [ColumnDefaultValue(0.00000000)]
        public decimal Interest
        {
            get { return fInterest; }
            set { SetPropertyValue<decimal>(nameof(Interest), ref fInterest, value); }
        }
        int fDayDalay;
        [Persistent(@"dayDalay")]
        [ColumnDefaultValue(0)]
        public int DayDalay
        {
            get { return fDayDalay; }
            set { SetPropertyValue<int>(nameof(DayDalay), ref fDayDalay, value); }
        }
        decimal fInterestMora;
        [Persistent(@"interestMora")]
        [ColumnDefaultValue(0.00000000)]
        public decimal InterestMora
        {
            get { return fInterestMora; }
            set { SetPropertyValue<decimal>(nameof(InterestMora), ref fInterestMora, value); }
        }
        int fCurrencyID;
        [Indexed(Name = @"IDX_TRANSACTION_MASTER_DETAIL_CREDIT_003")]
        [Persistent(@"currencyID")]
        [ColumnDefaultValue(0)]
        public int CurrencyID
        {
            get { return fCurrencyID; }
            set { SetPropertyValue<int>(nameof(CurrencyID), ref fCurrencyID, value); }
        }
        decimal fExchangeRate;
        [Persistent(@"exchangeRate")]
        [ColumnDefaultValue(0.00000000)]
        public decimal ExchangeRate
        {
            get { return fExchangeRate; }
            set { SetPropertyValue<decimal>(nameof(ExchangeRate), ref fExchangeRate, value); }
        }
        string fReference1;
        [Size(1500)]
        [Persistent(@"reference1")]
        public string Reference1
        {
            get { return fReference1; }
            set { SetPropertyValue<string>(nameof(Reference1), ref fReference1, value); }
        }
        string fReference2;
        [Persistent(@"reference2")]
        public string Reference2
        {
            get { return fReference2; }
            set { SetPropertyValue<string>(nameof(Reference2), ref fReference2, value); }
        }
        string fReference3;
        [Persistent(@"reference3")]
        public string Reference3
        {
            get { return fReference3; }
            set { SetPropertyValue<string>(nameof(Reference3), ref fReference3, value); }
        }
        string fReference4;
        [Persistent(@"reference4")]
        public string Reference4
        {
            get { return fReference4; }
            set { SetPropertyValue<string>(nameof(Reference4), ref fReference4, value); }
        }
        string fReference5;
        [Persistent(@"reference5")]
        public string Reference5
        {
            get { return fReference5; }
            set { SetPropertyValue<string>(nameof(Reference5), ref fReference5, value); }
        }
        string fReference6;
        [Persistent(@"reference6")]
        public string Reference6
        {
            get { return fReference6; }
            set { SetPropertyValue<string>(nameof(Reference6), ref fReference6, value); }
        }
        string fReference7;
        [Persistent(@"reference7")]
        public string Reference7
        {
            get { return fReference7; }
            set { SetPropertyValue<string>(nameof(Reference7), ref fReference7, value); }
        }
        string fReference8;
        [Persistent(@"reference8")]
        public string Reference8
        {
            get { return fReference8; }
            set { SetPropertyValue<string>(nameof(Reference8), ref fReference8, value); }
        }
        string fReference9;
        [Persistent(@"reference9")]
        public string Reference9
        {
            get { return fReference9; }
            set { SetPropertyValue<string>(nameof(Reference9), ref fReference9, value); }
        }
    }

}
