//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace v4posme_window_form.Models.dbkroqnguhldo1
{

    [NonPersistent]
    public partial class VwSalesInventory : XPLiteObject
    {
        DateTime fCreatedOn;
        [Persistent(@"createdOn")]
        public DateTime CreatedOn
        {
            get { return fCreatedOn; }
            set { SetPropertyValue<DateTime>(nameof(CreatedOn), ref fCreatedOn, value); }
        }
        int fCreatedOnDay;
        [Persistent(@"createdOnDay")]
        public int CreatedOnDay
        {
            get { return fCreatedOnDay; }
            set { SetPropertyValue<int>(nameof(CreatedOnDay), ref fCreatedOnDay, value); }
        }
        string fCurrency;
        [Size(250)]
        [Persistent(@"currency")]
        [ColumnDefaultValue("0")]
        public string Currency
        {
            get { return fCurrency; }
            set { SetPropertyValue<string>(nameof(Currency), ref fCurrency, value); }
        }
        string fTipo;
        [Size(250)]
        [Persistent(@"tipo")]
        [ColumnDefaultValue("0")]
        public string Tipo
        {
            get { return fTipo; }
            set { SetPropertyValue<string>(nameof(Tipo), ref fTipo, value); }
        }
        string fCausal;
        [Size(50)]
        [Persistent(@"causal")]
        [ColumnDefaultValue("0")]
        public string Causal
        {
            get { return fCausal; }
            set { SetPropertyValue<string>(nameof(Causal), ref fCausal, value); }
        }
        string fTransactionNumber;
        [Size(250)]
        [Persistent(@"transactionNumber")]
        [ColumnDefaultValue("0")]
        public string TransactionNumber
        {
            get { return fTransactionNumber; }
            set { SetPropertyValue<string>(nameof(TransactionNumber), ref fTransactionNumber, value); }
        }
        string fStatusName;
        [Size(250)]
        [Persistent(@"statusName")]
        public string StatusName
        {
            get { return fStatusName; }
            set { SetPropertyValue<string>(nameof(StatusName), ref fStatusName, value); }
        }
        string fCompaniaName;
        [Size(250)]
        [Persistent(@"companiaName")]
        [ColumnDefaultValue("N/D")]
        public string CompaniaName
        {
            get { return fCompaniaName; }
            set { SetPropertyValue<string>(nameof(CompaniaName), ref fCompaniaName, value); }
        }
        string fWarehouseName;
        [Size(50)]
        [Persistent(@"warehouseName")]
        [ColumnDefaultValue("0")]
        public string WarehouseName
        {
            get { return fWarehouseName; }
            set { SetPropertyValue<string>(nameof(WarehouseName), ref fWarehouseName, value); }
        }
        string fCustomerNumber;
        [Size(250)]
        [Persistent(@"customerNumber")]
        [ColumnDefaultValue("0")]
        public string CustomerNumber
        {
            get { return fCustomerNumber; }
            set { SetPropertyValue<string>(nameof(CustomerNumber), ref fCustomerNumber, value); }
        }
        string fFirstName;
        [Size(250)]
        [Persistent(@"firstName")]
        public string FirstName
        {
            get { return fFirstName; }
            set { SetPropertyValue<string>(nameof(FirstName), ref fFirstName, value); }
        }
        string fItemNumber;
        [Size(250)]
        [Persistent(@"itemNumber")]
        [ColumnDefaultValue("0")]
        public string ItemNumber
        {
            get { return fItemNumber; }
            set { SetPropertyValue<string>(nameof(ItemNumber), ref fItemNumber, value); }
        }
        string fName;
        [Size(250)]
        [Persistent(@"name")]
        [ColumnDefaultValue("0")]
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        string fCategoryName;
        [Size(250)]
        [Persistent(@"categoryName")]
        [ColumnDefaultValue("0")]
        public string CategoryName
        {
            get { return fCategoryName; }
            set { SetPropertyValue<string>(nameof(CategoryName), ref fCategoryName, value); }
        }
        decimal fTipoCambio;
        [Persistent(@"tipoCambio")]
        public decimal TipoCambio
        {
            get { return fTipoCambio; }
            set { SetPropertyValue<decimal>(nameof(TipoCambio), ref fTipoCambio, value); }
        }
        decimal fQuantity;
        [Persistent(@"quantity")]
        public decimal Quantity
        {
            get { return fQuantity; }
            set { SetPropertyValue<decimal>(nameof(Quantity), ref fQuantity, value); }
        }
        decimal fUnitaryCost;
        [Persistent(@"unitaryCost")]
        public decimal UnitaryCost
        {
            get { return fUnitaryCost; }
            set { SetPropertyValue<decimal>(nameof(UnitaryCost), ref fUnitaryCost, value); }
        }
        decimal fCost;
        [Persistent(@"cost")]
        public decimal Cost
        {
            get { return fCost; }
            set { SetPropertyValue<decimal>(nameof(Cost), ref fCost, value); }
        }
        decimal fUnitaryAmount;
        [Persistent(@"unitaryAmount")]
        public decimal UnitaryAmount
        {
            get { return fUnitaryAmount; }
            set { SetPropertyValue<decimal>(nameof(UnitaryAmount), ref fUnitaryAmount, value); }
        }
        decimal fAmount;
        [Persistent(@"amount")]
        public decimal Amount
        {
            get { return fAmount; }
            set { SetPropertyValue<decimal>(nameof(Amount), ref fAmount, value); }
        }
        decimal fUtility;
        [Persistent(@"utility")]
        public decimal Utility
        {
            get { return fUtility; }
            set { SetPropertyValue<decimal>(nameof(Utility), ref fUtility, value); }
        }
    }

}
