//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace v4posme_window_form.Models.Tablas
{

    [Persistent(@"tb_workflow_stage")]
    public partial class WorkflowStage : XPLiteObject
    {
        int fComponentID;
        [Indexed(Name = @"IDX_WORKFLOW_STAGE_001")]
        [Persistent(@"componentID")]
        [ColumnDefaultValue(0)]
        public int ComponentID
        {
            get { return fComponentID; }
            set { SetPropertyValue<int>(nameof(ComponentID), ref fComponentID, value); }
        }
        int fWorkflowID;
        [Indexed(Name = @"IDX_WORKFLOW_STAGE_002")]
        [Persistent(@"workflowID")]
        [ColumnDefaultValue(0)]
        public int WorkflowID
        {
            get { return fWorkflowID; }
            set { SetPropertyValue<int>(nameof(WorkflowID), ref fWorkflowID, value); }
        }
        int fWorkflowStageID;
        [Key(true)]
        [Persistent(@"workflowStageID")]
        public int WorkflowStageID
        {
            get { return fWorkflowStageID; }
            set { SetPropertyValue<int>(nameof(WorkflowStageID), ref fWorkflowStageID, value); }
        }
        string fName;
        [Size(250)]
        [Persistent(@"name")]
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        string fDescription;
        [Size(250)]
        [Persistent(@"description")]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>(nameof(Description), ref fDescription, value); }
        }
        string fDisplay;
        [Size(250)]
        [Persistent(@"display")]
        public string Display
        {
            get { return fDisplay; }
            set { SetPropertyValue<string>(nameof(Display), ref fDisplay, value); }
        }
        int fFlavorID;
        [Persistent(@"flavorID")]
        public int FlavorID
        {
            get { return fFlavorID; }
            set { SetPropertyValue<int>(nameof(FlavorID), ref fFlavorID, value); }
        }
        bool fEditableParcial;
        [Persistent(@"editableParcial")]
        public bool EditableParcial
        {
            get { return fEditableParcial; }
            set { SetPropertyValue<bool>(nameof(EditableParcial), ref fEditableParcial, value); }
        }
        bool fEditableTotal;
        [Persistent(@"editableTotal")]
        public bool EditableTotal
        {
            get { return fEditableTotal; }
            set { SetPropertyValue<bool>(nameof(EditableTotal), ref fEditableTotal, value); }
        }
        bool fEliminable;
        [Persistent(@"eliminable")]
        public bool Eliminable
        {
            get { return fEliminable; }
            set { SetPropertyValue<bool>(nameof(Eliminable), ref fEliminable, value); }
        }
        bool fAplicable;
        [Persistent(@"aplicable")]
        public bool Aplicable
        {
            get { return fAplicable; }
            set { SetPropertyValue<bool>(nameof(Aplicable), ref fAplicable, value); }
        }
        bool fVinculable;
        [Persistent(@"vinculable")]
        public bool Vinculable
        {
            get { return fVinculable; }
            set { SetPropertyValue<bool>(nameof(Vinculable), ref fVinculable, value); }
        }
        bool fIsActive;
        [Persistent(@"isActive")]
        [ColumnDefaultValue(false)]
        public bool IsActive
        {
            get { return fIsActive; }
            set { SetPropertyValue<bool>(nameof(IsActive), ref fIsActive, value); }
        }
        bool fIsInit;
        [Persistent(@"isInit")]
        [ColumnDefaultValue(false)]
        public bool IsInit
        {
            get { return fIsInit; }
            set { SetPropertyValue<bool>(nameof(IsInit), ref fIsInit, value); }
        }
    }

}
