//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace v4posme_window_form.Models.dbkroqnguhldo1
{

    [Persistent(@"tb_workflow_stage_relation")]
    public partial class WorkflowStageRelation : XPLiteObject
    {
        int fComponentID;
        [Indexed(Name = @"IDX_WOFKFLOW_STAGE_RELATION_001")]
        [Persistent(@"componentID")]
        [ColumnDefaultValue(0)]
        public int ComponentID
        {
            get { return fComponentID; }
            set { SetPropertyValue<int>(nameof(ComponentID), ref fComponentID, value); }
        }
        int fWorkflowID;
        [Indexed(Name = @"IDX_WOFKFLOW_STAGE_RELATION_002")]
        [Persistent(@"workflowID")]
        [ColumnDefaultValue(0)]
        public int WorkflowID
        {
            get { return fWorkflowID; }
            set { SetPropertyValue<int>(nameof(WorkflowID), ref fWorkflowID, value); }
        }
        int fWorkflowStageID;
        [Indexed(Name = @"IDX_WOFKFLOW_STAGE_RELATION_003")]
        [Persistent(@"workflowStageID")]
        [ColumnDefaultValue(0)]
        public int WorkflowStageID
        {
            get { return fWorkflowStageID; }
            set { SetPropertyValue<int>(nameof(WorkflowStageID), ref fWorkflowStageID, value); }
        }
        int fWorkflowStageTargetID;
        [Indexed(Name = @"IDX_WOFKFLOW_STAGE_RELATION_004")]
        [Persistent(@"workflowStageTargetID")]
        [ColumnDefaultValue(0)]
        public int WorkflowStageTargetID
        {
            get { return fWorkflowStageTargetID; }
            set { SetPropertyValue<int>(nameof(WorkflowStageTargetID), ref fWorkflowStageTargetID, value); }
        }
        int fWorkflowStageRelationID;
        [Key(true)]
        [Persistent(@"workflowStageRelationID")]
        public int WorkflowStageRelationID
        {
            get { return fWorkflowStageRelationID; }
            set { SetPropertyValue<int>(nameof(WorkflowStageRelationID), ref fWorkflowStageRelationID, value); }
        }
        bool fNecesitaAuth;
        [Persistent(@"necesitaAuth")]
        public bool NecesitaAuth
        {
            get { return fNecesitaAuth; }
            set { SetPropertyValue<bool>(nameof(NecesitaAuth), ref fNecesitaAuth, value); }
        }
        int fAuthRolID;
        public int AuthRolID
        {
            get { return fAuthRolID; }
            set { SetPropertyValue<int>(nameof(AuthRolID), ref fAuthRolID, value); }
        }
    }

}
