//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace v4posme_library.ModelsCode
{

    [Indices(@"CatalogID;CatalogItemID")]
    [Persistent(@"tb_catalog_item")]
    public partial class CatalogItem : XPLiteObject
    {
        int fCatalogID;
        [Indexed(Name = @"IDX_CATALOG_ITEM_001")]
        [Persistent(@"catalogID")]
        [ColumnDefaultValue(0)]
        public int CatalogID
        {
            get { return fCatalogID; }
            set { SetPropertyValue<int>(nameof(CatalogID), ref fCatalogID, value); }
        }
        int fCatalogItemID;
        [Key(true)]
        [Persistent(@"catalogItemID")]
        public int CatalogItemID
        {
            get { return fCatalogItemID; }
            set { SetPropertyValue<int>(nameof(CatalogItemID), ref fCatalogItemID, value); }
        }
        string fName;
        [Size(250)]
        [Persistent(@"name")]
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        string fDisplay;
        [Size(250)]
        [Persistent(@"display")]
        public string Display
        {
            get { return fDisplay; }
            set { SetPropertyValue<string>(nameof(Display), ref fDisplay, value); }
        }
        int fFlavorID;
        [Indexed(Name = @"IDX_CATALOG_ITEM_002")]
        [Persistent(@"flavorID")]
        public int FlavorID
        {
            get { return fFlavorID; }
            set { SetPropertyValue<int>(nameof(FlavorID), ref fFlavorID, value); }
        }
        string fDescription;
        [Size(250)]
        [Persistent(@"description")]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>(nameof(Description), ref fDescription, value); }
        }
        int fSequence;
        [Persistent(@"sequence")]
        public int Sequence
        {
            get { return fSequence; }
            set { SetPropertyValue<int>(nameof(Sequence), ref fSequence, value); }
        }
        int fParentCatalogID;
        [Indexed(Name = @"IDX_CATALOG_ITEM_003")]
        [Persistent(@"parentCatalogID")]
        public int ParentCatalogID
        {
            get { return fParentCatalogID; }
            set { SetPropertyValue<int>(nameof(ParentCatalogID), ref fParentCatalogID, value); }
        }
        int fParentCatalogItemID;
        [Indexed(Name = @"IDX_CATALOG_ITEM_004")]
        [Persistent(@"parentCatalogItemID")]
        public int ParentCatalogItemID
        {
            get { return fParentCatalogItemID; }
            set { SetPropertyValue<int>(nameof(ParentCatalogItemID), ref fParentCatalogItemID, value); }
        }
        decimal fRatio;
        [Persistent(@"ratio")]
        [ColumnDefaultValue(1.00000000)]
        public decimal Ratio
        {
            get { return fRatio; }
            set { SetPropertyValue<decimal>(nameof(Ratio), ref fRatio, value); }
        }
        string fReference1;
        [Size(150)]
        [Persistent(@"reference1")]
        public string Reference1
        {
            get { return fReference1; }
            set { SetPropertyValue<string>(nameof(Reference1), ref fReference1, value); }
        }
        string fReference2;
        [Size(255)]
        [Persistent(@"reference2")]
        public string Reference2
        {
            get { return fReference2; }
            set { SetPropertyValue<string>(nameof(Reference2), ref fReference2, value); }
        }
        string fReference3;
        [Size(255)]
        [Persistent(@"reference3")]
        public string Reference3
        {
            get { return fReference3; }
            set { SetPropertyValue<string>(nameof(Reference3), ref fReference3, value); }
        }
        string fReference4;
        [Size(255)]
        [Persistent(@"reference4")]
        public string Reference4
        {
            get { return fReference4; }
            set { SetPropertyValue<string>(nameof(Reference4), ref fReference4, value); }
        }
    }

}
