//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace v4posme_library.ModelsCode
{

    [Persistent(@"tb_item_warehouse")]
    public partial class ItemWarehouse : XPLiteObject
    {
        int fItemWarehouseId;
        [Key(true)]
        [Persistent(@"itemWarehouseId")]
        public int ItemWarehouseId
        {
            get { return fItemWarehouseId; }
            set { SetPropertyValue<int>(nameof(ItemWarehouseId), ref fItemWarehouseId, value); }
        }
        int fCompanyID;
        [Indexed(Name = @"IDX_ITEM_WAREHOUSE_001")]
        [Persistent(@"companyID")]
        [ColumnDefaultValue(0)]
        public int CompanyID
        {
            get { return fCompanyID; }
            set { SetPropertyValue<int>(nameof(CompanyID), ref fCompanyID, value); }
        }
        int fBranchID;
        [Indexed(Name = @"IDX_ITEM_WAREHOUSE_002")]
        [Persistent(@"branchID")]
        [ColumnDefaultValue(0)]
        public int BranchID
        {
            get { return fBranchID; }
            set { SetPropertyValue<int>(nameof(BranchID), ref fBranchID, value); }
        }
        int fWarehouseID;
        [Indexed(Name = @"IDX_ITEM_WAREHOUSE_003")]
        [Persistent(@"warehouseID")]
        [ColumnDefaultValue(0)]
        public int WarehouseID
        {
            get { return fWarehouseID; }
            set { SetPropertyValue<int>(nameof(WarehouseID), ref fWarehouseID, value); }
        }
        int fItemID;
        [Indexed(Name = @"IDX_ITEM_WAREHOUSE_004")]
        [Persistent(@"itemID")]
        [ColumnDefaultValue(0)]
        public int ItemID
        {
            get { return fItemID; }
            set { SetPropertyValue<int>(nameof(ItemID), ref fItemID, value); }
        }
        decimal fQuantity;
        [Persistent(@"quantity")]
        [ColumnDefaultValue(0.0000)]
        public decimal Quantity
        {
            get { return fQuantity; }
            set { SetPropertyValue<decimal>(nameof(Quantity), ref fQuantity, value); }
        }
        decimal fCost;
        [Persistent(@"cost")]
        [ColumnDefaultValue(0.0000)]
        public decimal Cost
        {
            get { return fCost; }
            set { SetPropertyValue<decimal>(nameof(Cost), ref fCost, value); }
        }
        decimal fQuantityMax;
        [Persistent(@"quantityMax")]
        [ColumnDefaultValue(0.0000)]
        public decimal QuantityMax
        {
            get { return fQuantityMax; }
            set { SetPropertyValue<decimal>(nameof(QuantityMax), ref fQuantityMax, value); }
        }
        decimal fQuantityMin;
        [Persistent(@"quantityMin")]
        [ColumnDefaultValue(0.0000)]
        public decimal QuantityMin
        {
            get { return fQuantityMin; }
            set { SetPropertyValue<decimal>(nameof(QuantityMin), ref fQuantityMin, value); }
        }
    }

}
