//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace v4posme_library.ModelsCode
{

    [Persistent(@"tb_item_warehouse_expired")]
    public partial class ItemWarehouseExpired : XPLiteObject
    {
        int fItemWarehouseExpiredID;
        [Key(true)]
        [Persistent(@"itemWarehouseExpiredID")]
        public int ItemWarehouseExpiredID
        {
            get { return fItemWarehouseExpiredID; }
            set { SetPropertyValue<int>(nameof(ItemWarehouseExpiredID), ref fItemWarehouseExpiredID, value); }
        }
        int fWarehouseID;
        [Indexed(Name = @"IDX_ITEM_WAREHOUSE_EXPIRED_001")]
        [Persistent(@"warehouseID")]
        public int WarehouseID
        {
            get { return fWarehouseID; }
            set { SetPropertyValue<int>(nameof(WarehouseID), ref fWarehouseID, value); }
        }
        int fItemID;
        [Indexed(Name = @"IDX_ITEM_WAREHOUSE_EXPIRED_002")]
        [Persistent(@"itemID")]
        public int ItemID
        {
            get { return fItemID; }
            set { SetPropertyValue<int>(nameof(ItemID), ref fItemID, value); }
        }
        int fCompanyID;
        [Indexed(Name = @"IDX_ITEM_WAREHOUSE_EXPIRED_003")]
        [Persistent(@"companyID")]
        public int CompanyID
        {
            get { return fCompanyID; }
            set { SetPropertyValue<int>(nameof(CompanyID), ref fCompanyID, value); }
        }
        decimal fQuantity;
        [Persistent(@"quantity")]
        public decimal Quantity
        {
            get { return fQuantity; }
            set { SetPropertyValue<decimal>(nameof(Quantity), ref fQuantity, value); }
        }
        string fLote;
        [Size(50)]
        [Persistent(@"lote")]
        public string Lote
        {
            get { return fLote; }
            set { SetPropertyValue<string>(nameof(Lote), ref fLote, value); }
        }
        DateTime fDateExpired;
        [Persistent(@"dateExpired")]
        public DateTime DateExpired
        {
            get { return fDateExpired; }
            set { SetPropertyValue<DateTime>(nameof(DateExpired), ref fDateExpired, value); }
        }
    }

}
