//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace v4posme_library.ModelsCode
{

    [Persistent(@"tb_item")]
    public partial class Item : XPLiteObject
    {
        int fCompanyID;
        [Indexed(Name = @"IDX_ITEM_001")]
        [Persistent(@"companyID")]
        [ColumnDefaultValue(0)]
        public int CompanyID
        {
            get { return fCompanyID; }
            set { SetPropertyValue<int>(nameof(CompanyID), ref fCompanyID, value); }
        }
        int fBranchID;
        [Indexed(Name = @"IDX_ITEM_002")]
        [Persistent(@"branchID")]
        [ColumnDefaultValue(0)]
        public int BranchID
        {
            get { return fBranchID; }
            set { SetPropertyValue<int>(nameof(BranchID), ref fBranchID, value); }
        }
        int fInventoryCategoryID;
        [Indexed(Name = @"IDX_ITEM_003")]
        [Persistent(@"inventoryCategoryID")]
        [ColumnDefaultValue(0)]
        public int InventoryCategoryID
        {
            get { return fInventoryCategoryID; }
            set { SetPropertyValue<int>(nameof(InventoryCategoryID), ref fInventoryCategoryID, value); }
        }
        int fItemID;
        [Key(true)]
        [Persistent(@"itemID")]
        public int ItemID
        {
            get { return fItemID; }
            set { SetPropertyValue<int>(nameof(ItemID), ref fItemID, value); }
        }
        int fFamilyID;
        [Indexed(Name = @"IDX_ITEM_004")]
        [Persistent(@"familyID")]
        public int FamilyID
        {
            get { return fFamilyID; }
            set { SetPropertyValue<int>(nameof(FamilyID), ref fFamilyID, value); }
        }
        string fItemNumber;
        [Indexed(Name = @"IDX_ITEM_005")]
        [Size(250)]
        [Persistent(@"itemNumber")]
        [ColumnDefaultValue("0")]
        public string ItemNumber
        {
            get { return fItemNumber; }
            set { SetPropertyValue<string>(nameof(ItemNumber), ref fItemNumber, value); }
        }
        string fBarCode;
        [Indexed(Name = @"IDX_ITEM_006")]
        [Size(1200)]
        [Persistent(@"barCode")]
        public string BarCode
        {
            get { return fBarCode; }
            set { SetPropertyValue<string>(nameof(BarCode), ref fBarCode, value); }
        }
        string fName;
        [Size(250)]
        [Persistent(@"name")]
        [ColumnDefaultValue("0")]
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        string fDescription;
        [Size(1000)]
        [Persistent(@"description")]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>(nameof(Description), ref fDescription, value); }
        }
        string fUnitMeasureID;
        [Indexed(Name = @"IDX_ITEM_007")]
        [Size(250)]
        [Persistent(@"unitMeasureID")]
        public string UnitMeasureID
        {
            get { return fUnitMeasureID; }
            set { SetPropertyValue<string>(nameof(UnitMeasureID), ref fUnitMeasureID, value); }
        }
        int fDisplayID;
        [Indexed(Name = @"IDX_ITEM_008")]
        [Persistent(@"displayID")]
        public int DisplayID
        {
            get { return fDisplayID; }
            set { SetPropertyValue<int>(nameof(DisplayID), ref fDisplayID, value); }
        }
        int fCapacity;
        [Persistent(@"capacity")]
        public int Capacity
        {
            get { return fCapacity; }
            set { SetPropertyValue<int>(nameof(Capacity), ref fCapacity, value); }
        }
        int fDisplayUnitMeasureID;
        [Indexed(Name = @"IDX_ITEM_009")]
        [Persistent(@"displayUnitMeasureID")]
        public int DisplayUnitMeasureID
        {
            get { return fDisplayUnitMeasureID; }
            set { SetPropertyValue<int>(nameof(DisplayUnitMeasureID), ref fDisplayUnitMeasureID, value); }
        }
        int fDefaultWarehouseID;
        [Indexed(Name = @"IDX_ITEM_010")]
        [Persistent(@"defaultWarehouseID")]
        public int DefaultWarehouseID
        {
            get { return fDefaultWarehouseID; }
            set { SetPropertyValue<int>(nameof(DefaultWarehouseID), ref fDefaultWarehouseID, value); }
        }
        decimal fQuantity;
        [Persistent(@"quantity")]
        [ColumnDefaultValue(0.0000)]
        public decimal Quantity
        {
            get { return fQuantity; }
            set { SetPropertyValue<decimal>(nameof(Quantity), ref fQuantity, value); }
        }
        decimal fQuantityMax;
        [Persistent(@"quantityMax")]
        [ColumnDefaultValue(0.0000)]
        public decimal QuantityMax
        {
            get { return fQuantityMax; }
            set { SetPropertyValue<decimal>(nameof(QuantityMax), ref fQuantityMax, value); }
        }
        decimal fQuantityMin;
        [Persistent(@"quantityMin")]
        [ColumnDefaultValue(0.0000)]
        public decimal QuantityMin
        {
            get { return fQuantityMin; }
            set { SetPropertyValue<decimal>(nameof(QuantityMin), ref fQuantityMin, value); }
        }
        decimal fCost;
        [Persistent(@"cost")]
        [ColumnDefaultValue(0.0000)]
        public decimal Cost
        {
            get { return fCost; }
            set { SetPropertyValue<decimal>(nameof(Cost), ref fCost, value); }
        }
        string fReference1;
        [Size(250)]
        [Persistent(@"reference1")]
        public string Reference1
        {
            get { return fReference1; }
            set { SetPropertyValue<string>(nameof(Reference1), ref fReference1, value); }
        }
        string fReference2;
        [Size(250)]
        [Persistent(@"reference2")]
        public string Reference2
        {
            get { return fReference2; }
            set { SetPropertyValue<string>(nameof(Reference2), ref fReference2, value); }
        }
        string fReference3;
        [Size(255)]
        [Persistent(@"reference3")]
        public string Reference3
        {
            get { return fReference3; }
            set { SetPropertyValue<string>(nameof(Reference3), ref fReference3, value); }
        }
        int fStatusID;
        [Indexed(Name = @"IDX_ITEM_011")]
        [Persistent(@"statusID")]
        public int StatusID
        {
            get { return fStatusID; }
            set { SetPropertyValue<int>(nameof(StatusID), ref fStatusID, value); }
        }
        bool fIsPerishable;
        [Persistent(@"isPerishable")]
        public bool IsPerishable
        {
            get { return fIsPerishable; }
            set { SetPropertyValue<bool>(nameof(IsPerishable), ref fIsPerishable, value); }
        }
        decimal fFactorBox;
        [Persistent(@"factorBox")]
        public decimal FactorBox
        {
            get { return fFactorBox; }
            set { SetPropertyValue<decimal>(nameof(FactorBox), ref fFactorBox, value); }
        }
        decimal fFactorProgram;
        [Persistent(@"factorProgram")]
        public decimal FactorProgram
        {
            get { return fFactorProgram; }
            set { SetPropertyValue<decimal>(nameof(FactorProgram), ref fFactorProgram, value); }
        }
        string fCreatedIn;
        [Size(250)]
        [Persistent(@"createdIn")]
        public string CreatedIn
        {
            get { return fCreatedIn; }
            set { SetPropertyValue<string>(nameof(CreatedIn), ref fCreatedIn, value); }
        }
        int fCreatedAt;
        [Persistent(@"createdAt")]
        public int CreatedAt
        {
            get { return fCreatedAt; }
            set { SetPropertyValue<int>(nameof(CreatedAt), ref fCreatedAt, value); }
        }
        int fCreatedBy;
        [Persistent(@"createdBy")]
        public int CreatedBy
        {
            get { return fCreatedBy; }
            set { SetPropertyValue<int>(nameof(CreatedBy), ref fCreatedBy, value); }
        }
        DateTime fCreatedOn;
        [Persistent(@"createdOn")]
        public DateTime CreatedOn
        {
            get { return fCreatedOn; }
            set { SetPropertyValue<DateTime>(nameof(CreatedOn), ref fCreatedOn, value); }
        }
        bool fIsActive;
        [Persistent(@"isActive")]
        public bool IsActive
        {
            get { return fIsActive; }
            set { SetPropertyValue<bool>(nameof(IsActive), ref fIsActive, value); }
        }
        sbyte fIsInvoiceQuantityZero;
        [Persistent(@"isInvoiceQuantityZero")]
        [ColumnDefaultValue(0)]
        public sbyte IsInvoiceQuantityZero
        {
            get { return fIsInvoiceQuantityZero; }
            set { SetPropertyValue<sbyte>(nameof(IsInvoiceQuantityZero), ref fIsInvoiceQuantityZero, value); }
        }
        sbyte fIsServices;
        [Persistent(@"isServices")]
        [ColumnDefaultValue(0)]
        public sbyte IsServices
        {
            get { return fIsServices; }
            set { SetPropertyValue<sbyte>(nameof(IsServices), ref fIsServices, value); }
        }
        int fCurrencyID;
        [Indexed(Name = @"IDX_ITEM_012")]
        [Persistent(@"currencyID")]
        [ColumnDefaultValue(1)]
        public int CurrencyID
        {
            get { return fCurrencyID; }
            set { SetPropertyValue<int>(nameof(CurrencyID), ref fCurrencyID, value); }
        }
        int fIsInvoice;
        [Persistent(@"isInvoice")]
        [ColumnDefaultValue(1)]
        public int IsInvoice
        {
            get { return fIsInvoice; }
            set { SetPropertyValue<int>(nameof(IsInvoice), ref fIsInvoice, value); }
        }
    }

}
