//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace v4posme_library.ModelsCode
{

    [Persistent(@"tb_item_config_loto")]
    public partial class ItemConfigLoto : XPLiteObject
    {
        int fItemConfigLotoID;
        [Key(true)]
        [Persistent(@"itemConfigLotoID")]
        public int ItemConfigLotoID
        {
            get { return fItemConfigLotoID; }
            set { SetPropertyValue<int>(nameof(ItemConfigLotoID), ref fItemConfigLotoID, value); }
        }
        int fIsActive;
        [Persistent(@"isActive")]
        [ColumnDefaultValue(1)]
        public int IsActive
        {
            get { return fIsActive; }
            set { SetPropertyValue<int>(nameof(IsActive), ref fIsActive, value); }
        }
        decimal fMaxSale;
        [Persistent(@"maxSale")]
        [ColumnDefaultValue(1.00)]
        public decimal MaxSale
        {
            get { return fMaxSale; }
            set { SetPropertyValue<decimal>(nameof(MaxSale), ref fMaxSale, value); }
        }
        int fTurno1Inicio;
        [Persistent(@"turno1Inicio")]
        [ColumnDefaultValue(0)]
        public int Turno1Inicio
        {
            get { return fTurno1Inicio; }
            set { SetPropertyValue<int>(nameof(Turno1Inicio), ref fTurno1Inicio, value); }
        }
        int fTurno1Fin;
        [Persistent(@"turno1Fin")]
        [ColumnDefaultValue(9)]
        public int Turno1Fin
        {
            get { return fTurno1Fin; }
            set { SetPropertyValue<int>(nameof(Turno1Fin), ref fTurno1Fin, value); }
        }
        int fTurno2Inicio;
        [Persistent(@"turno2Inicio")]
        [ColumnDefaultValue(9)]
        public int Turno2Inicio
        {
            get { return fTurno2Inicio; }
            set { SetPropertyValue<int>(nameof(Turno2Inicio), ref fTurno2Inicio, value); }
        }
        int fTurno2Fin;
        [Persistent(@"turno2Fin")]
        [ColumnDefaultValue(14)]
        public int Turno2Fin
        {
            get { return fTurno2Fin; }
            set { SetPropertyValue<int>(nameof(Turno2Fin), ref fTurno2Fin, value); }
        }
        int fTurno3Inicio;
        [Persistent(@"turno3Inicio")]
        [ColumnDefaultValue(14)]
        public int Turno3Inicio
        {
            get { return fTurno3Inicio; }
            set { SetPropertyValue<int>(nameof(Turno3Inicio), ref fTurno3Inicio, value); }
        }
        int fTurno3Fin;
        [Persistent(@"turno3Fin")]
        [ColumnDefaultValue(22)]
        public int Turno3Fin
        {
            get { return fTurno3Fin; }
            set { SetPropertyValue<int>(nameof(Turno3Fin), ref fTurno3Fin, value); }
        }
        int fItemID;
        [Indexed(Name = @"IDX_ITEM_CONFIG_LOTO_001")]
        [Persistent(@"itemID")]
        [ColumnDefaultValue(1)]
        public int ItemID
        {
            get { return fItemID; }
            set { SetPropertyValue<int>(nameof(ItemID), ref fItemID, value); }
        }
    }

}
