//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace v4posme_library.ModelsCode
{

    [Persistent(@"tb_item_sku")]
    public partial class ItemSku : XPLiteObject
    {
        int fSkuID;
        [Key(true)]
        [Persistent(@"skuID")]
        public int SkuID
        {
            get { return fSkuID; }
            set { SetPropertyValue<int>(nameof(SkuID), ref fSkuID, value); }
        }
        int fItemID;
        [Indexed(Name = @"IDX_WAREHOUSE_SKU_001")]
        [Persistent(@"itemID")]
        public int ItemID
        {
            get { return fItemID; }
            set { SetPropertyValue<int>(nameof(ItemID), ref fItemID, value); }
        }
        int fCatalogItemID;
        [Indexed(Name = @"IDX_WAREHOUSE_SKU_002")]
        [Persistent(@"catalogItemID")]
        public int CatalogItemID
        {
            get { return fCatalogItemID; }
            set { SetPropertyValue<int>(nameof(CatalogItemID), ref fCatalogItemID, value); }
        }
        decimal fValue;
        [Persistent(@"value")]
        public decimal Value
        {
            get { return fValue; }
            set { SetPropertyValue<decimal>(nameof(Value), ref fValue, value); }
        }
    }

}
