//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace v4posme_library.ModelsCode
{

    [Persistent(@"tb_naturales")]
    public partial class Naturales : XPLiteObject
    {
        int fCompanyID;
        [Indexed(Name = @"IDX_NATURALES_001")]
        [Persistent(@"companyID")]
        [ColumnDefaultValue(0)]
        public int CompanyID
        {
            get { return fCompanyID; }
            set { SetPropertyValue<int>(nameof(CompanyID), ref fCompanyID, value); }
        }
        int fBranchID;
        [Indexed(Name = @"IDX_NATURALES_002")]
        [Persistent(@"branchID")]
        [ColumnDefaultValue(0)]
        public int BranchID
        {
            get { return fBranchID; }
            set { SetPropertyValue<int>(nameof(BranchID), ref fBranchID, value); }
        }
        int fEntityID;
        [Indexed(Name = @"IDX_NATURALES_003")]
        [Persistent(@"entityID")]
        [ColumnDefaultValue(0)]
        public int EntityID
        {
            get { return fEntityID; }
            set { SetPropertyValue<int>(nameof(EntityID), ref fEntityID, value); }
        }
        string fFirstName;
        [Size(250)]
        [Persistent(@"firstName")]
        public string FirstName
        {
            get { return fFirstName; }
            set { SetPropertyValue<string>(nameof(FirstName), ref fFirstName, value); }
        }
        string fLastName;
        [Size(250)]
        [Persistent(@"lastName")]
        public string LastName
        {
            get { return fLastName; }
            set { SetPropertyValue<string>(nameof(LastName), ref fLastName, value); }
        }
        string fAddress;
        [Size(250)]
        [Persistent(@"address")]
        public string Address
        {
            get { return fAddress; }
            set { SetPropertyValue<string>(nameof(Address), ref fAddress, value); }
        }
        int fStatusID;
        [Indexed(Name = @"IDX_NATURALES_004")]
        [Persistent(@"statusID")]
        [ColumnDefaultValue(0)]
        public int StatusID
        {
            get { return fStatusID; }
            set { SetPropertyValue<int>(nameof(StatusID), ref fStatusID, value); }
        }
        int fProfesionID;
        [Indexed(Name = @"IDX_NATURALES_005")]
        [Persistent(@"profesionID")]
        [ColumnDefaultValue(0)]
        public int ProfesionID
        {
            get { return fProfesionID; }
            set { SetPropertyValue<int>(nameof(ProfesionID), ref fProfesionID, value); }
        }
        bool fIsActive;
        [Persistent(@"isActive")]
        public bool IsActive
        {
            get { return fIsActive; }
            set { SetPropertyValue<bool>(nameof(IsActive), ref fIsActive, value); }
        }
        int fNaturalesID;
        [Key(true)]
        [Persistent(@"naturalesID")]
        public int NaturalesID
        {
            get { return fNaturalesID; }
            set { SetPropertyValue<int>(nameof(NaturalesID), ref fNaturalesID, value); }
        }
    }

}
