//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace v4posme_library.ModelsCode
{

    [Persistent(@"tb_razones_financieras_tmp")]
    public partial class RazonesFinancierasTmp : XPLiteObject
    {
        int fRzID;
        [Key(true)]
        [Persistent(@"rzID")]
        public int RzID
        {
            get { return fRzID; }
            set { SetPropertyValue<int>(nameof(RzID), ref fRzID, value); }
        }
        int fCompanyID;
        [Persistent(@"companyID")]
        [ColumnDefaultValue(0)]
        public int CompanyID
        {
            get { return fCompanyID; }
            set { SetPropertyValue<int>(nameof(CompanyID), ref fCompanyID, value); }
        }
        int fBranchID;
        [Persistent(@"branchID")]
        [ColumnDefaultValue(0)]
        public int BranchID
        {
            get { return fBranchID; }
            set { SetPropertyValue<int>(nameof(BranchID), ref fBranchID, value); }
        }
        int fLoginID;
        [Persistent(@"loginID")]
        [ColumnDefaultValue(0)]
        public int LoginID
        {
            get { return fLoginID; }
            set { SetPropertyValue<int>(nameof(LoginID), ref fLoginID, value); }
        }
        string fToken;
        [Size(150)]
        [Persistent(@"token")]
        [ColumnDefaultValue("0")]
        public string Token
        {
            get { return fToken; }
            set { SetPropertyValue<string>(nameof(Token), ref fToken, value); }
        }
        string fName;
        [Size(150)]
        [Persistent(@"name")]
        [ColumnDefaultValue("0")]
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        string fSequence;
        [Size(5)]
        [Persistent(@"sequence")]
        [ColumnDefaultValue("0")]
        public string Sequence
        {
            get { return fSequence; }
            set { SetPropertyValue<string>(nameof(Sequence), ref fSequence, value); }
        }
        decimal fValue;
        [Persistent(@"value")]
        [ColumnDefaultValue(0.00)]
        public decimal Value
        {
            get { return fValue; }
            set { SetPropertyValue<decimal>(nameof(Value), ref fValue, value); }
        }
        string fSimbol;
        [Size(5)]
        [Persistent(@"simbol")]
        [ColumnDefaultValue("0")]
        public string Simbol
        {
            get { return fSimbol; }
            set { SetPropertyValue<string>(nameof(Simbol), ref fSimbol, value); }
        }
        string fDescription;
        [Size(500)]
        [Persistent(@"description")]
        [ColumnDefaultValue("0")]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>(nameof(Description), ref fDescription, value); }
        }
    }

}
