//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace v4posme_library.ModelsCode
{

    [Persistent(@"tb_tag")]
    public partial class Tag : XPLiteObject
    {
        int fTagID;
        [Key(true)]
        [Persistent(@"tagID")]
        public int TagID
        {
            get { return fTagID; }
            set { SetPropertyValue<int>(nameof(TagID), ref fTagID, value); }
        }
        string fName;
        [Indexed(Name = @"IDX_TAG_001")]
        [Size(150)]
        [Persistent(@"name")]
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        string fDescription;
        [Size(500)]
        [Persistent(@"description")]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>(nameof(Description), ref fDescription, value); }
        }
        bool fSendEmail;
        [Persistent(@"sendEmail")]
        public bool SendEmail
        {
            get { return fSendEmail; }
            set { SetPropertyValue<bool>(nameof(SendEmail), ref fSendEmail, value); }
        }
        bool fSendNotificationApp;
        [Persistent(@"sendNotificationApp")]
        public bool SendNotificationApp
        {
            get { return fSendNotificationApp; }
            set { SetPropertyValue<bool>(nameof(SendNotificationApp), ref fSendNotificationApp, value); }
        }
        bool fSendSMS;
        [Persistent(@"sendSMS")]
        public bool SendSMS
        {
            get { return fSendSMS; }
            set { SetPropertyValue<bool>(nameof(SendSMS), ref fSendSMS, value); }
        }
        bool fIsActive;
        [Persistent(@"isActive")]
        public bool IsActive
        {
            get { return fIsActive; }
            set { SetPropertyValue<bool>(nameof(IsActive), ref fIsActive, value); }
        }
    }

}
