//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace v4posme_library.ModelsCode
{

    [Persistent(@"tb_transaction_causal")]
    public partial class TransactionCausal : XPLiteObject
    {
        int fCompanyID;
        [Indexed(Name = @"IDX_TRANSACTION_CAUSAL_001")]
        [Persistent(@"companyID")]
        [ColumnDefaultValue(0)]
        public int CompanyID
        {
            get { return fCompanyID; }
            set { SetPropertyValue<int>(nameof(CompanyID), ref fCompanyID, value); }
        }
        int fTransactionID;
        [Indexed(Name = @"IDX_TRANSACTION_CAUSAL_002")]
        [Persistent(@"transactionID")]
        [ColumnDefaultValue(0)]
        public int TransactionID
        {
            get { return fTransactionID; }
            set { SetPropertyValue<int>(nameof(TransactionID), ref fTransactionID, value); }
        }
        int fTransactionCausalID;
        [Key(true)]
        [Persistent(@"transactionCausalID")]
        public int TransactionCausalID
        {
            get { return fTransactionCausalID; }
            set { SetPropertyValue<int>(nameof(TransactionCausalID), ref fTransactionCausalID, value); }
        }
        int fBranchID;
        [Indexed(Name = @"IDX_TRANSACTION_CAUSAL_003")]
        [Persistent(@"branchID")]
        public int BranchID
        {
            get { return fBranchID; }
            set { SetPropertyValue<int>(nameof(BranchID), ref fBranchID, value); }
        }
        string fName;
        [Size(50)]
        [Persistent(@"name")]
        [ColumnDefaultValue("0")]
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        int fWarehouseSourceID;
        [Indexed(Name = @"IDX_TRANSACTION_CAUSAL_004")]
        [Persistent(@"warehouseSourceID")]
        public int WarehouseSourceID
        {
            get { return fWarehouseSourceID; }
            set { SetPropertyValue<int>(nameof(WarehouseSourceID), ref fWarehouseSourceID, value); }
        }
        int fWarehouseTargetID;
        [Indexed(Name = @"IDX_TRANSACTION_CAUSAL_005")]
        [Persistent(@"warehouseTargetID")]
        public int WarehouseTargetID
        {
            get { return fWarehouseTargetID; }
            set { SetPropertyValue<int>(nameof(WarehouseTargetID), ref fWarehouseTargetID, value); }
        }
        bool fIsDefault;
        [Persistent(@"isDefault")]
        [ColumnDefaultValue(false)]
        public bool IsDefault
        {
            get { return fIsDefault; }
            set { SetPropertyValue<bool>(nameof(IsDefault), ref fIsDefault, value); }
        }
        bool fIsActive;
        [Persistent(@"isActive")]
        [ColumnDefaultValue(false)]
        public bool IsActive
        {
            get { return fIsActive; }
            set { SetPropertyValue<bool>(nameof(IsActive), ref fIsActive, value); }
        }
    }

}
