//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace v4posme_library.ModelsCode
{

    [NonPersistent]
    public partial class VwGerenciaDesembolsosDetalle : XPLiteObject
    {
        string fColaborador;
        [Size(250)]
        [ColumnDefaultValue("0")]
        public string Colaborador
        {
            get { return fColaborador; }
            set { SetPropertyValue<string>(nameof(Colaborador), ref fColaborador, value); }
        }
        string fNombreColaborador;
        [Size(250)]
        public string NombreColaborador
        {
            get { return fNombreColaborador; }
            set { SetPropertyValue<string>(nameof(NombreColaborador), ref fNombreColaborador, value); }
        }
        string fCliente;
        [Size(250)]
        [ColumnDefaultValue("0")]
        public string Cliente
        {
            get { return fCliente; }
            set { SetPropertyValue<string>(nameof(Cliente), ref fCliente, value); }
        }
        string fNombreCliente;
        [Size(250)]
        public string NombreCliente
        {
            get { return fNombreCliente; }
            set { SetPropertyValue<string>(nameof(NombreCliente), ref fNombreCliente, value); }
        }
        string fFactura;
        [Size(50)]
        [ColumnDefaultValue("0")]
        public string Factura
        {
            get { return fFactura; }
            set { SetPropertyValue<string>(nameof(Factura), ref fFactura, value); }
        }
        int fCreditAmortizationID;
        [Persistent(@"creditAmortizationID")]
        [ColumnDefaultValue(0)]
        public int CreditAmortizationID
        {
            get { return fCreditAmortizationID; }
            set { SetPropertyValue<int>(nameof(CreditAmortizationID), ref fCreditAmortizationID, value); }
        }
        DateTime fFechaCuota;
        [ColumnDefaultValue(1980, 1, 1, 0, 0, 0, 0)]
        public DateTime FechaCuota
        {
            get { return fFechaCuota; }
            set { SetPropertyValue<DateTime>(nameof(FechaCuota), ref fFechaCuota, value); }
        }
        string fAnoCuota;
        [Size(4)]
        public string AnoCuota
        {
            get { return fAnoCuota; }
            set { SetPropertyValue<string>(nameof(AnoCuota), ref fAnoCuota, value); }
        }
        string fMes1Cuota;
        [Size(7)]
        public string Mes1Cuota
        {
            get { return fMes1Cuota; }
            set { SetPropertyValue<string>(nameof(Mes1Cuota), ref fMes1Cuota, value); }
        }
        string fMes2Cuota;
        [Size(2)]
        public string Mes2Cuota
        {
            get { return fMes2Cuota; }
            set { SetPropertyValue<string>(nameof(Mes2Cuota), ref fMes2Cuota, value); }
        }
        double fC_BalanceStartCuota;
        [Persistent(@"C$BalanceStartCuota")]
        public double C_BalanceStartCuota
        {
            get { return fC_BalanceStartCuota; }
            set { SetPropertyValue<double>(nameof(C_BalanceStartCuota), ref fC_BalanceStartCuota, value); }
        }
        double fC_InteresCuota;
        [Persistent(@"C$InteresCuota")]
        public double C_InteresCuota
        {
            get { return fC_InteresCuota; }
            set { SetPropertyValue<double>(nameof(C_InteresCuota), ref fC_InteresCuota, value); }
        }
        double fC_CapitalCuota;
        [Persistent(@"C$CapitalCuota")]
        public double C_CapitalCuota
        {
            get { return fC_CapitalCuota; }
            set { SetPropertyValue<double>(nameof(C_CapitalCuota), ref fC_CapitalCuota, value); }
        }
        double fC_BalanceEndCuota;
        [Persistent(@"C$BalanceEndCuota")]
        public double C_BalanceEndCuota
        {
            get { return fC_BalanceEndCuota; }
            set { SetPropertyValue<double>(nameof(C_BalanceEndCuota), ref fC_BalanceEndCuota, value); }
        }
        double fC_ShareCuota;
        [Persistent(@"C$ShareCuota")]
        public double C_ShareCuota
        {
            get { return fC_ShareCuota; }
            set { SetPropertyValue<double>(nameof(C_ShareCuota), ref fC_ShareCuota, value); }
        }
        double fC_RemainingCuota;
        [Persistent(@"C$RemainingCuota")]
        public double C_RemainingCuota
        {
            get { return fC_RemainingCuota; }
            set { SetPropertyValue<double>(nameof(C_RemainingCuota), ref fC_RemainingCuota, value); }
        }
        double fC_shareCapital;
        [Persistent(@"C$shareCapital")]
        public double C_shareCapital
        {
            get { return fC_shareCapital; }
            set { SetPropertyValue<double>(nameof(C_shareCapital), ref fC_shareCapital, value); }
        }
        string fEstadoCuota;
        [Size(250)]
        public string EstadoCuota
        {
            get { return fEstadoCuota; }
            set { SetPropertyValue<string>(nameof(EstadoCuota), ref fEstadoCuota, value); }
        }
        long fDiasAtrazoCuota;
        [Persistent(@"diasAtrazoCuota")]
        public long DiasAtrazoCuota
        {
            get { return fDiasAtrazoCuota; }
            set { SetPropertyValue<long>(nameof(DiasAtrazoCuota), ref fDiasAtrazoCuota, value); }
        }
        string fMoneda;
        [Size(250)]
        [ColumnDefaultValue("0")]
        public string Moneda
        {
            get { return fMoneda; }
            set { SetPropertyValue<string>(nameof(Moneda), ref fMoneda, value); }
        }
        double fTipoCambioActual;
        public double TipoCambioActual
        {
            get { return fTipoCambioActual; }
            set { SetPropertyValue<double>(nameof(TipoCambioActual), ref fTipoCambioActual, value); }
        }
        double fC_CapitalPagado;
        [Persistent(@"C$CapitalPagado")]
        public double C_CapitalPagado
        {
            get { return fC_CapitalPagado; }
            set { SetPropertyValue<double>(nameof(C_CapitalPagado), ref fC_CapitalPagado, value); }
        }
        double fC_CapitalPendiente;
        [Persistent(@"C$CapitalPendiente")]
        public double C_CapitalPendiente
        {
            get { return fC_CapitalPendiente; }
            set { SetPropertyValue<double>(nameof(C_CapitalPendiente), ref fC_CapitalPendiente, value); }
        }
        double fC_IntaresPagado;
        [Persistent(@"C$IntaresPagado")]
        public double C_IntaresPagado
        {
            get { return fC_IntaresPagado; }
            set { SetPropertyValue<double>(nameof(C_IntaresPagado), ref fC_IntaresPagado, value); }
        }
        double fC_InteresPendiente;
        [Persistent(@"C$InteresPendiente")]
        public double C_InteresPendiente
        {
            get { return fC_InteresPendiente; }
            set { SetPropertyValue<double>(nameof(C_InteresPendiente), ref fC_InteresPendiente, value); }
        }
    }

}
