//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace v4posme_library.ModelsCode
{

    [NonPersistent]
    public partial class VwTransaccionMasterConcept232425 : XPLiteObject
    {
        int fTransactionMasterID;
        [Persistent(@"transactionMasterID")]
        [ColumnDefaultValue(0)]
        public int TransactionMasterID
        {
            get { return fTransactionMasterID; }
            set { SetPropertyValue<int>(nameof(TransactionMasterID), ref fTransactionMasterID, value); }
        }
        string fDescripcion;
        [Size(250)]
        [ColumnDefaultValue("0")]
        public string Descripcion
        {
            get { return fDescripcion; }
            set { SetPropertyValue<string>(nameof(Descripcion), ref fDescripcion, value); }
        }
        DateTime fFecha;
        public DateTime Fecha
        {
            get { return fFecha; }
            set { SetPropertyValue<DateTime>(nameof(Fecha), ref fFecha, value); }
        }
        string fDocumento;
        [Size(250)]
        [ColumnDefaultValue("0")]
        public string Documento
        {
            get { return fDocumento; }
            set { SetPropertyValue<string>(nameof(Documento), ref fDocumento, value); }
        }
        string fMoneda;
        [Size(250)]
        [ColumnDefaultValue("0")]
        public string Moneda
        {
            get { return fMoneda; }
            set { SetPropertyValue<string>(nameof(Moneda), ref fMoneda, value); }
        }
        string fConcepto;
        [Size(250)]
        public string Concepto
        {
            get { return fConcepto; }
            set { SetPropertyValue<string>(nameof(Concepto), ref fConcepto, value); }
        }
        decimal fValor;
        [ColumnDefaultValue(0.0000)]
        public decimal Valor
        {
            get { return fValor; }
            set { SetPropertyValue<decimal>(nameof(Valor), ref fValor, value); }
        }
        string fComponente;
        [Size(250)]
        public string Componente
        {
            get { return fComponente; }
            set { SetPropertyValue<string>(nameof(Componente), ref fComponente, value); }
        }
        int fComponentItemID;
        [Persistent(@"componentItemID")]
        public int ComponentItemID
        {
            get { return fComponentItemID; }
            set { SetPropertyValue<int>(nameof(ComponentItemID), ref fComponentItemID, value); }
        }
        string fReferencia1;
        [Size(250)]
        public string Referencia1
        {
            get { return fReferencia1; }
            set { SetPropertyValue<string>(nameof(Referencia1), ref fReferencia1, value); }
        }
    }

}
